### PR TITLE
chore(deps): Update to new Avvio major version

### PR DESCRIPTION
**Pull request by MetCoder95**
**Reminder to update Avvio** to next major release 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I think we could go ahead and land this?

**Comment by kibertoad** [comment]
@mcollina https://github.com/fastify/avvio/pull/145 seems to be the only meaningful change that was not yet released. Are we waiting for anything else, or avvio final could be released?

**Comment by mcollina** [comment]
The new avvio@8.0.0 has been released.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I'm landing this, I don't think there is anything more to do.

**Pull request merged**
