### PR TITLE
add Node 17

### PR DESCRIPTION
**Pull request by Eomm**
Targetting next

Let's try it 🎉

### CODE REVIEW

**Comment by darkgl0w** [comment]
Should be good now with `tap@5.1.1`
for reference: https://node-tap.org/changelog/#151---2021-11-16

**Comment by mcollina** [comment]
Our tests needs some fixes due to the DNS change.

**Comment by mcollina** [comment]
We should target `main` with this change

**Comment by Eomm** [comment]
supersedes by #3456

**Pull request closed without merging**
