### PR TITLE
chore: rename next to done

### PR DESCRIPTION
**Pull request by ryhinchey**
the callback used in fastify plugins is called `done` throughout the docs; however, `next` is used in the Typescript  type. This PR updates the type to be consistent with the documentation

#### Checklist

- [x ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by giulianok** [comment]
@ryhinchey this is awesome! I personally don't really care how the parameter is being called in the application side, but it would be great to have consistency in the docs, examples, code, tests, etc.

Maybe this PR could be used to change all the `next` references to `done`? https://github.com/fastify/fastify/search?p=3&q=next. I found that tests and examples are also using `next`

**Comment by ryhinchey** [comment]
@giulianok yah I'm happy to do that in this PR is the fastify team is on board with a PR changing so many files :)

**Comment by Ethan-Arrowood** [comment]
I'm :+1: for consistency. I don't believe this is a breaking change since its just function arguments (which can be named anything).

**Review by giulianok — APPROVED** [review]

**Comment by Ethan-Arrowood** [comment]
Haha so there seems to be no consistency throughout the repo, nice fix!

**Review by Ethan-Arrowood — APPROVED** [review]

**Review by Eomm — APPROVED** [review]
image

**Review by mcollina — APPROVED** [review]
lgtm

This is massive work, thanks.

LGTM

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by jsumners — APPROVED** [review]
I can't go through this line by line. But I'm on board.

**Pull request merged**
