### PR TITLE
Updated Not found handling

### PR DESCRIPTION
**Pull request by delvedor**
As titled, see https://github.com/fastify/fastify/issues/848 for discussion.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nwoltman** [comment]
This section of documentation needs to be removed: https://github.com/fastify/fastify/pull/1084/files#diff-31032738bcacc769cecf4d9f6989d581R183

**Comment by delvedor** [comment]
What about renaming `reply.notFound` in `reply.callNotFound` or something like this?
I think it would be more expressive.

**Comment by nwoltman** [comment]
@delvedor That sounds good to me 👍. Wondering if @mcollina agrees. [Here's the original discussion](https://github.com/fastify/fastify-static/pull/27#discussion_r158830732) where the name was created.

**Comment by mcollina** [comment]
+1 to whatever you prefer ;).

**Comment by allevo** [comment]
`invokeNotFoundHandler` ?

**Comment by delvedor** [comment]
@allevo too long, personally I like `callNotFound`, but also `invokeNotFound` could do the job.

Put a 👍 if you prefer `callNotFound` or a 🎉 if you prefer `invokeNotFound` :)

**Comment by delvedor** [comment]
Can we land this?

**Comment by mcollina** [comment]
this would require an update to fastify-static for v2.

**Pull request merged**
