### PR TITLE
(v3.x) perf: only check for isEssence once in RegExp for  content-type-parser (#4481)

### PR DESCRIPTION
**Pull request by climba03003**
Backport #4481

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
The error is about the generating certificate for `https` and `http2` test.
No idea why it will fail suddenly.

**Comment by Uzlopak** [comment]
Well the tests fail because of openssl not passing the legacy flag or so.

**Comment by climba03003** [comment]
`main` did use self-sign.
Hmm, maybe I mess up when checking different branches.

**Comment by jsumners** [comment]
> `main` did use self-sign. Hmm, maybe I mess up when checking different branches.

The `3.x` branch is still using `pem` -- https://github.com/fastify/fastify/blob/605303133ee853b9b293d545f210910473ea4553/package.json#L161

https://github.com/fastify/fastify/pull/3711 should be backported to 3.x

**Review by Uzlopak — APPROVED** [review]

**Review by Eomm — APPROVED** [review]

**Comment by Eomm** [comment]
Is @fastify/core willing to bump a new v3 release?

**Comment by climba03003** [comment]
> Is https://github.com/orgs/fastify/teams/core willing to bump a new v3 release?

We still maintaining `3.x` branch as `LTS`. 
Although, `bugfix` or `security patch` are the one focusing on but shouldn't block releasing new version if we have good changes.

**Comment by mcollina** [comment]
yes, I'll ship one with these fixes.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
