### PR TITLE
docs(reply): standardize import style in examples

### PR DESCRIPTION
**Pull request by Tony133**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Proposal:

- Small corrections to update in code snippets in `Reply` section

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]

**Review by jsumners — CHANGES_REQUESTED** [review]
I'm not seeing any changes that relate to the PR title.

**Review by Fdawgs — CHANGES_REQUESTED** [review]
This has just moved requires to the upper scope? Not related to the PR title as jsumners has already noted.

**Comment by Tony133** [comment]
> Did this just move requires to the upper scope? It is not related to the PR title as jsumners already noted.

So if I understand correctly the `const fs = require ( ' node:fs ' )´ is moved inside the `fastify.get()` for scope reasons ? correct ?

because reading the docs description not much specified, please correct me if i'm wrong

**Comment by jsumners** [comment]
I would say that the require is inside the handler function in order to keep the example clear. The example has no surrounding context, but by putting the require outside of the handler, it becomes easy to miss that it is needed for the code to work. At least, that's what I think by looking at the change set.

**Comment by gurgunday** [comment]
My reasoning was that other examples in the same doc page have the `require` at the top, so it'd be more consistent to either put them all within the scope or not

https://github.com/fastify/fastify/pull/5580/files?short_path=efc7e73#diff-efc7e73d03e0de6ce1bcb55aecb8a43777795b115b2221cba794bc34d7ba0f14

**Comment by Tony133** [comment]
Only in two examples the `require('node:fs')` and within `fastify.get()` maybe they can be a little confusing with respect to the other code snippets as it happened to me 😅, maybe writing some comments in the code snippet can be helpful, if you don't want to move the `require('node:fs')` outside of `fastify.get()` 

Let me know if I need to make any changes in this PR 🙂 .

**Review by gurgunday — APPROVED** [review]
like I said, this change, while small, makes things more consistent in the docs

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
