### PR TITLE
[Fix] Change warning message when version appears in route declaration

### LINKED ISSUE #3105: Unclear warning when `version` appears in the route declaration
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.13

### Plugin version

_No response_

### Node.js version

14.16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

if a route definition passed to `fastify.route` contains a `version: 1.0.0` instead of contraints: { version: 1.0.1 }

`(node:187842) [FSTDEP006] FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: %s`

This warning is unclear and appears to incorrectly formatted with the `%s` specifier in the message.  I spent a lot of time investigating plugins and my decoration of the fastify, requests and response until I tracked down the line the warning was being emitted on: https://github.com/fastify/fastify/blob/main/lib/route.js#L230 Which revealed the cause of the warning. 

On a related note all of the docs related to constraints(https://www.fastify.io/docs/latest/Routes/#constraints) contain invalid syntax specifying the constraint member:
The docs show: 
`fastify.route({
  method: 'GET',
  url: '/',
  { constraints: { version: '1.2.0'} },
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  }
})`

when they should show:
`fastify.route({
  method: 'GET',
  url: '/',
  constraints: { version: '1.2.0'},
  handler: function (request, reply) {
    reply.send({ hello: 'world' })
  }
})`
This is repeated through all the examples in the constraints section. 

### Steps to Reproduce

Run the following program:

```
const fastify = require('fastify')();

fastify.route({
  method: 'GET',
  handler: () => {},
  url: '/',
  version: '1.0.1',
  // constraints: { version: '1.0.1' },
});

fastify.listen(3000);
```

### Expected Behavior

This warning should indicate be worded like `You are decorating your routes with version, this property is expected to be in the constraints member`.

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #3105 

Hi @climba03003  / @mcollina! how does this look?

Thank you!

### CODE REVIEW

**Comment by climba03003** [comment]
Can you add an unit test for this warning? It can ensure it won't be emit the wrong one again.

**Comment by rbrishabh** [comment]
Sure @climba03003 ! I can do that!

**Comment by rbrishabh** [comment]
@climba03003  ah it looks like a test case was already there for this use case, I just updated it! Let me know if it looks okay! 
Thank you

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
