### PR TITLE
Updated benchmarks to Fastify 0.27.0 and Node 8.4.0.

### PR DESCRIPTION
**Pull request by mcollina**
@cagataycali @dougwilson  thanks for helping out. Between turbofan and the changes you made the results looks very different now.

### CODE REVIEW

**Comment by dougwilson** [comment]
It's no problem at all :)

I've also in the past few days made changes to Express itself, which weave into the existing builds though dependencies. I have more changes I'm pushing out over the time I have. There is so much low-hanging fruit to fix in Express, the benchmarks helped out a lot \\m/ . My local build has Express at 22,872 req/s and Fastly 26,686 req/s so far (which differs from the published version, especially since some are changes to express package itself).

**Comment by mcollina** [comment]
@dougwilson let me know if you need any help. I'm happy to discuss if you get stuck on some bits, I just want to get Node faster.

Also, turbofan is a game changer, so remember to check also for 6 as it's different from time to time.

**Comment by cagataycali** [comment]
The results look really different. I hope it's easy to test. @dougwilson is very helpful person 🎁

**Comment by dougwilson** [comment]
Yea, I am mainly concerned with 4 and 6. I've been checking 8.4 as well because it is quite different.

**Comment by motss** [comment]
@dougwilson @mcollina Is there much difference between a development Express and a production Express (with `NODE_ENV=production` being set)? I did some tests earlier today and found out that a production Express does perform better. Curious to know if the Express being tested has the flag `NODE_ENV=production` being set.

**Comment by mcollina** [comment]
It's written in the http.Server result.

**Pull request merged**
