### PR TITLE
lib: drop setDefaultRoute and getDefaultRoute methods

### PR DESCRIPTION
**Pull request by RafaelGSS**
Signed-off-by: RafaelGSS <rafael.nunu@hotmail.com>

Following up: #4480 

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]

**Review by climba03003 — APPROVED** [review]

**Comment by mcollina** [comment]
This can land in v4, can you rebase onto main?

**Comment by RafaelGSS** [comment]
> This can land in v4, can you rebase onto main?

Isn't it a breaking change?

**Comment by mcollina** [comment]
ah no, this is the correct one! I mixed the two PRs.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
