### PR TITLE
Add fastify-dynareg to ecosystem doc.

### PR DESCRIPTION
**Pull request by greguz**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by fox1t** [comment]
LGTM

**Review by fox1t — APPROVED** [review]

**Comment by StarpTech** [comment]
@greguz could you have some words on your README what this module really does? I was confused when I first saw it.

**Comment by greguz** [comment]
@StarpTech yeah, you're right. I'll add some words, for those poor humans. :P

**Comment by greguz** [comment]
@StarpTech I've just updated the [README](https://github.com/greguz/fastify-dynareg) file. What do you think about it?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by StarpTech** [comment]
@greguz LGTM

**Comment by greguz** [comment]
Thank you all :+1:

**Pull request merged**
