### PR TITLE
docs: add pubsub-http-handler

### PR DESCRIPTION
**Pull request by cobraz**
#### Checklist

- [ ] ~~run `npm run test` and `npm run benchmark`~~
- [ ] ~~tests and/or benchmarks are included~~
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you put it in alphabetical order?

**Comment by cobraz** [comment]
> Can you put it in alphabetical order?

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
