### PR TITLE
chore: fix flaky test

### PR DESCRIPTION
**Pull request by Eomm**
fixes our win coverage issue:

- https://github.com/fastify/fastify/actions/runs/12182503397/job/33981743111

```
Error: [Error [ERR_TEST_FAILURE]: connect ECONNREFUSED 127.0.0.1:50469] {
  code: 'ERR_TEST_FAILURE',
  failureType: 'testCodeFailure',
  cause: Error: connect ECONNREFUSED 127.0.0.1:50469
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 50469
  }
}
FAILED: D:\a\fastify\fastify\test\post-empty-body.test.js
```

### CODE REVIEW

**Comment by Eomm** [comment]
I deleted the cache and now nix is failing too 

image

**Comment by jsumners** [comment]
> It could be [MoLow/reporters#131](https://github.com/MoLow/reporters/pull/131)

Where does this come from?

```
fastify on  main took 13s
❯ npm ls reporters
fastify@5.1.0 /Users/jsumners/Projects/oss/fastify/fastify
└── (empty)
```

**Comment by jsumners** [comment]
🤬🤬🤬🤬 monorepos 🤬🤬🤬🤬🤬

```
fastify on  main
❯ npm ls @reporters/github
fastify@5.1.0 /Users/jsumners/Projects/oss/fastify/fastify
└─┬ borp@0.18.0
  └── @reporters/github@1.7.2
```

**Comment by jsumners** [comment]
I don't think that reporters bug is the culprit. The offending test ends up requesting `http://127.0.0.1:${fastify.server.address().port}/bug`. That URL does not contain any special characters.

**Comment by climba03003** [comment]
Superseded by #5889

**Comment by Eomm** [comment]
Reopened because I think these edits are legit (we run the test twice in the `ci` coverage check)

**Comment by jsumners** [comment]
> Reopened because I think these edits are legit (we run the test twice in the `ci` coverage check)

https://github.com/fastify/fastify/issues/4887#issuecomment-1627514131

**Comment by Eomm** [comment]
Times After:

image


Timing on main:

image

**Review by jsumners — APPROVED** [review]

**Review by Fdawgs — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by climba03003** [comment]
Seems to added flakiness? Failure on modified file.
https://github.com/fastify/fastify/actions/runs/12312646534/job/34365302838

**Pull request merged**
