### PR TITLE
Update Ecosystem.md

### PR DESCRIPTION
**Pull request by eusunov**
Dear Fastify team,

We use Fastify in our IoT project, which requires a reliable way to broadcast messages from end devices through the base station and application server to the web client and back. The result is our Redis based channels implementation plugin. I think it is useful and worth sharing.  

Thanks!
Kind regards,
:)

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by L2jLiga** [comment]
Can you place it in alphabetical order?

**Review by L2jLiga — APPROVED** [review]
Welcome :)

**Comment by eusunov** [comment]
It is re-ordered.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
