### PR TITLE
Use `http.METHODS`

### PR DESCRIPTION
**Pull request by allevo**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

I've not added tests too: any suggestions?

Test fails: waiting for https://github.com/delvedor/find-my-way/pull/72.

### CODE REVIEW

**Comment by nwoltman** [comment]
Requests for any of the new methods will end up here:
https://github.com/fastify/fastify/blob/70ac47ab8a74d1be753fc82872b02c6fa5d9264c/lib/handleRequest.js#L53

**Comment by delvedor** [comment]
I agree with @nwoltman, while we can support all methods in `find-my-way` here we should also handle them.

**Comment by mcollina** [comment]
I think this could be closed.

**Comment by allevo** [comment]
So we don't want to support all HTTP methods? Why?

**Comment by delvedor** [comment]
@allevo on the contrary, but we can't just add all the methods to the array if our internals does not handle them.
If we want to do that we should also update the `handleRequest` function and handle every HTTP method.

**Comment by mcollina** [comment]
@allevo can you file a PR in the other direction? Like, updating `handleRequest` to support all methods?

**Pull request closed without merging**
