### PR TITLE
Add `formzilla` to community plugin list

### PR DESCRIPTION
**Pull request by FlameWolf**
#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [x] documentation is added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Just wanted to remark that we have @fastify/busboy and @fastify/multipart

**Comment by FlameWolf** [comment]
> Just wanted to remark that we have @fastify/busboy and @fastify/multipart

I know. I made this to address the problem of integration with @fastify/swagger and JSON schema.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

Why didn’t you send a PR to one of the other modules to implement this?

**Comment by mcollina** [comment]
the docs are not listing, could you check CI?

**Pull request closed without merging**
