### PR TITLE
Move @Ethan-Arrowood to Past Collaborator section

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
❤️ I've been inactive long enough on issues/prs/discussions so I think its appropriate I move myself to past collaborators.

Love and appreciate the entire fastify crew. Know that I'll always be around as apart of the Fastify community 🚀

### CODE REVIEW

**Review by zekth — APPROVED** [review]
Thanks for all the contributions

**Review by climba03003 — APPROVED** [review]
Thanks for your past works.

**Review by delvedor — APPROVED** [review]
Thanks for all your work Ethan, the door will always be open for you!

**Comment by mcollina** [comment]
Thanks Ethan!

**Review by Eomm — COMMENTED** [review]
Thanks for your invaluable TS work!

I hope one day you will also teach me how to ski 😄

**Comment by HassanBahati** [comment]
Really inspired by your work @Ethan-Arrowood :clap:

**Pull request merged**
