### PR TITLE
Add fastify-esm-loader to community libs

### PR DESCRIPTION
**Pull request by galvez**
- https://github.com/galvez/fastify-esm-loader

### CODE REVIEW

**Comment by mcollina** [comment]
Would you mind adding some CI to the module?

**Comment by mcollina** [comment]
Also, tests.

**Comment by galvez** [comment]
@mcollina oh sure, will update this PR when it's done.

**Comment by mcollina** [comment]
@galvez any updates?

**Comment by galvez** [comment]
@mcollina nope, not yet, but I should get to it sometime before NYE -- I'll close this PR for now so it doesn't clutter your view. Will reopenThanks.

**Pull request closed without merging**
