### PR TITLE
Type this in RequestHandler

### LINKED ISSUE #1538: `this` is not typed in RequestHandler
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## To Reproduce

Paste your code here:

```ts
fastify.get('/api/xx', function(req, res) {
  this. // no completion and Type checker complains.  
})
```

## Expected behavior

Paste the results here:

```ts
fastify.get('/api/xx', function(req, res) {
  this. // this points to FastifyInstance
})
```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

### PR DESCRIPTION
**Pull request by fuafa**
#### Checklist

- [Y] run `npm run test` and `npm run benchmark`
- [Y] tests and/or benchmarks are included
- [Y] documentation is changed or added
- [Y] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

fixed #1538

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
This is a valid issue, but I do not believe this is the correct change. Function context should be passed through correctly. I've been working locally trying to rewrite our types because I believe the current implementation leads to bugs like this that are hard to track down. I'm going to defer to @evanshortiss as he was a part of the original writing of these types.

**Comment by fuafa** [comment]
@Ethan-Arrowood Thanks for replying, I not familiar with the fastify architecture, just a quick glance at the type definition, feel free to close it if I am doing it wrong.

**Comment by Ethan-Arrowood** [comment]
Took a second look at this and I think I've convinced myself you're correct with this change. 

@mcollina to be clear, a function defined on the route options object should be `this` scoped to the entire FastifyInstance? Is this true for parameters such as `preValidation`, `preHandler`, and `preSerialization` too? These questions go into the type refactor I'm working on.

Additionally, would you consider the following two code bytes equivalent in functionality?
```javascript
fastify.route({
  handler: (request, reply) => {
    this.log.info('hello, fastify')
  }
})
```
```javascript
fastify.route({
  handler: function (request, reply) {
    this.log.info('hello, fastify')
  }
})
```

**Comment by jsumners** [comment]
@Ethan-Arrowood

```js
fastify.route({
  handler: (request, reply) => {
    this.log.info('hello, fastify')
  }
})
```

That is invalid. The `this` reference will be undefined. You want:

```js
fastify.route({
  handler (request, reply) {
    this.log.info('hello, fastify')
  }
})
```

**Comment by Ethan-Arrowood** [comment]
Okay that is what I thought, wanted to be sure. This change LGTM!

**Comment by delvedor** [comment]
We still need to backport this, @Ethan-Arrowood would you do the honors? :)

**Comment by Ethan-Arrowood** [comment]
Will do

**Comment by Ethan-Arrowood** [comment]
@delvedor I don't have npm publish permissions for fastify. I have cherry-picked the commit to 1.x branch, updated the package version to 1.14.6 and tagged as well. I've pushed all of that to the 1.x branch. I think all thats left is a `npm publish` 👍

**Comment by mcollina** [comment]
Don’t worry, I’ll get that out asap. Releases in fastify are cut by @delvedor or myself.

**Comment by Ethan-Arrowood** [comment]
Going forward, should I continue to tag on fastify or leave that to the two of you?

**Comment by mcollina** [comment]
Leave it to us, thanks!

**Pull request merged**
