### PR TITLE
Refactor to ES6 classes

### PR DESCRIPTION
**Pull request by sergiz**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This PR only introduces a syntax change; it refactors constructor functions and modifying prototypes to using ES6 classes. I ran benchmarks a few times there isn't any noticable difference since benchmarks are very inconsistent.

These were ran using nodejs v10.17.0.
"main"

```
[1] ┌─────────┬──────┬───────┬───────┬───────┬──────────┬─────────┬────────┐
[1] │ Stat    │ 2.5% │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max    │
[1] ├─────────┼──────┼───────┼───────┼───────┼──────────┼─────────┼────────┤
[1] │ Latency │ 9 ms │ 20 ms │ 41 ms │ 61 ms │ 19.67 ms │ 10.3 ms │ 182 ms │
[1] └─────────┴──────┴───────┴───────┴───────┴──────────┴─────────┴────────┘
[1] ┌───────────┬─────────┬─────────┬─────────┬────────┬─────────┬─────────┬─────────┐
[1] │ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%  │ Avg     │ Stdev   │ Min     │
[1] ├───────────┼─────────┼─────────┼─────────┼────────┼─────────┼─────────┼─────────┤
[1] │ Req/Sec   │ 35263   │ 35263   │ 55583   │ 56063  │ 49622.4 │ 8279.23 │ 35239   │
[1] ├───────────┼─────────┼─────────┼─────────┼────────┼─────────┼─────────┼─────────┤
[1] │ Bytes/Sec │ 5.78 MB │ 5.78 MB │ 9.12 MB │ 9.2 MB │ 8.14 MB │ 1.36 MB │ 5.78 MB │
[1] └───────────┴─────────┴─────────┴─────────┴────────┴─────────┴─────────┴─────────┘
```

```
[1] ┌─────────┬───────┬───────┬───────┬───────┬──────────┬──────────┬────────┐
[1] │ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max    │
[1] ├─────────┼───────┼───────┼───────┼───────┼──────────┼──────────┼────────┤
[1] │ Latency │ 10 ms │ 21 ms │ 43 ms │ 63 ms │ 20.41 ms │ 10.25 ms │ 176 ms │
[1] └─────────┴───────┴───────┴───────┴───────┴──────────┴──────────┴────────┘
[1] ┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
[1] │ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
[1] │ Req/Sec   │ 34623   │ 34623   │ 52927   │ 53983   │ 47856   │ 7489.29 │ 34616   │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
[1] │ Bytes/Sec │ 5.68 MB │ 5.68 MB │ 8.68 MB │ 8.86 MB │ 7.85 MB │ 1.23 MB │ 5.68 MB │
[1] └───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

"pr/refactor-to-es6-classes"

```
[1] ┌─────────┬───────┬───────┬───────┬───────┬──────────┬──────────┬────────┐
[1] │ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev    │ Max    │
[1] ├─────────┼───────┼───────┼───────┼───────┼──────────┼──────────┼────────┤
[1] │ Latency │ 10 ms │ 22 ms │ 43 ms │ 59 ms │ 21.05 ms │ 10.93 ms │ 151 ms │
[1] └─────────┴───────┴───────┴───────┴───────┴──────────┴──────────┴────────┘
[1] ┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
[1] │ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
[1] │ Req/Sec   │ 34047   │ 34047   │ 50143   │ 52511   │ 46460.8 │ 7062.01 │ 34021   │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
[1] │ Bytes/Sec │ 5.58 MB │ 5.58 MB │ 8.22 MB │ 8.61 MB │ 7.62 MB │ 1.16 MB │ 5.58 MB │
[1] └───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

```
[1] ┌─────────┬──────┬───────┬───────┬───────┬──────────┬─────────┬────────┐
[1] │ Stat    │ 2.5% │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max    │
[1] ├─────────┼──────┼───────┼───────┼───────┼──────────┼─────────┼────────┤
[1] │ Latency │ 9 ms │ 20 ms │ 37 ms │ 60 ms │ 19.04 ms │ 9.52 ms │ 174 ms │
[1] └─────────┴──────┴───────┴───────┴───────┴──────────┴─────────┴────────┘
[1] ┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
[1] │ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
[1] │ Req/Sec   │ 36895   │ 36895   │ 54527   │ 58079   │ 51190.4 │ 7966.28 │ 36895   │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
[1] │ Bytes/Sec │ 6.05 MB │ 6.05 MB │ 8.95 MB │ 9.53 MB │ 8.4 MB  │ 1.31 MB │ 6.05 MB │
[1] └───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

### CODE REVIEW

**Review by jsumners — CHANGES_REQUESTED** [review]
Please ask if such a large change would be welcome before spending time on it.

What does this change provide us?

**Comment by sergiz** [comment]
It's actually a tiny change. Github makes it look gigantic, but if you hide whitespace changes there were only a few lines actually modified.

It makes the code utilize the modern Javascript and it's easier to understand at least to those who started with JS after ES6 was out.

**Comment by zekth** [comment]
> It complicates the code without any tangible benefit.

It doesn't complicates, it uses the modern ES syntax. As stated from [MDN ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes): 

> Classes are in fact "special functions", and just as you can define function expressions and function declarations, the class syntax has two components: class expressions and class declarations.

I have no strong opinion on this, i'd say it's easier to read and onboard new developers. One benefit would be the [Private class features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).

**Comment by jsumners** [comment]
> It doesn't complicates, it uses the modern ES syntax.

The extent of my usage of the `class` keyword in JavaScript is literally summed up by:

```js
'use strict'

const MySet = class extends Set {}

MySet.prototype.find = function find(value) {
  for (const item of this) {
    if (item === value) return item
  }
}

const mySet = new MySet(['foo', 'bar', 'baz'])
console.log(mySet.find('bar'))
```

And that is because the spec requires such nonsense -- https://tc39.es/ecma262/#sec-set-constructor

Otherwise, I am not at all clear what other trickery the `class` keyword introduces that would screw with the typical prototype methodology and find it more difficult to read/work with.

**Comment by MSE99** [comment]
Methods in the class bodies suffer from an extra level of indentation, this is the only negative i see, classes have a lot of differences to regular functions but i doubt that any of them is going to break fastify or one of the plugins.

**Comment by L2jLiga** [comment]
I'm +1 on that. According to my experience IDEs better handle classes than prototypes

**Review by mcollina — CHANGES_REQUESTED** [review]
I don't think we should change this.

Most of the "classes" touched by this are used in complex prototype chains and acts together with our encapsulation behaviors. Using a class sends the wrong signal.

**Comment by RafaelGSS** [comment]
> Most of the "classes" touched by this are used in complex prototype chains and acts together with our encapsulation behaviors. Using a class sends the wrong signal.

Our tests would break if there are any key errors on it, no? I mean, I would like to see a canary release with that refactor, I see a huge benefit for newcomers.

**Comment by Eomm** [comment]
Maybe could we think to use this syntax for those classes that don't use the prototype inheritance?

I mean:
- schemas
- hooks
- content type parser

**Comment by jsumners** [comment]
> Maybe could we think to use this syntax for those classes that don't use the prototype inheritance?

I don't see any reason to mix and match syntax. It would introduce nebulous rules that would be a mystery to contributors and difficult to remember for maintainers.

**Comment by zekth** [comment]
> > Maybe could we think to use this syntax for those classes that don't use the prototype inheritance?
> 
> I don't see any reason to mix and match syntax. It would introduce nebulous rules that would be a mystery to contributors and difficult to remember for maintainers.

I agree with this. Let's just keep on implementation.

**Comment by Eomm** [comment]
I feel guilty right now 😄 

We have a class

https://github.com/fastify/fastify/blob/e4b2a3aad3a4e56ab3c9192aa6bb989316ef7780/lib/schema-controller.js#L29

Have I [misunderstood](https://github.com/fastify/fastify/pull/2755#pullrequestreview-558878398) this review?

**Comment by mcollina** [comment]
This seems a bit stuck without significant progress. I'm going to close it for now.

Feel free to reopen if you are still interested in working on this.

**Pull request closed without merging**
