### PR TITLE
fix: TypeScript route Handlers

### PR DESCRIPTION
**Pull request by zekth**
fix: https://github.com/fastify/fastify/issues/3803

This is unfortunately not working yet. I fixed the assertions in the tests.
So basically a handler should either return a Typed value or the `FastifyReply`; it should never return `void`.

Returning `undefined` or `void` should be prohibited.

mention @climba03003 @sinclairzx81 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by sinclairzx81** [comment]
@zekth Hi. Just had a look at the type definitions and they look ok to me, however removing `void` for the callback return type would disallow the following implementation. 

```typescript
fastify.get<{...}>('/', (req, res) => {  res.send('hello') }) // -> void: not allowed
```
The v3 definitions had hinted at two ways a user could respond with a value, either `res.send(...)` or `return`. I'm guessing if a user called `res.send(...)` (as above) then the expectation would be that the return type should be `void`. The definitions had defined the return type as `ReturnType | void`, with `void` assumed a requirement for `res.send(...)` usage patterns.

Is this a anticipated functional change for v4?

**Comment by zekth** [comment]
maybe it's only in `async` but @climba03003 and i were discussing several issues we had over the fastify project and people wrongly use the handlers sometimes. Leading to confusion. Here is the list:
```ts
// Good - it return reply
async function(request, reply) {
  return reply.status(code).send(payload)
}

// Good - it also return reply
async function(request, reply) {
  reply.status(code).send(payload)
  return reply
}

// Fairly Good - it return the payload
async function(request, reply) {
  reply.status(code)
  return payload
}

// Fairly Bad - it return nothing
async function(request, reply) {
  reply.status(code).send(payload)
}

// Bad / Don't - it return undefined and may return response twice
async function(request, reply) {
  reply.status(code).send(payload)
  return
}

// Bad / Don't - it return send response twice
async function(request, reply) {
  reply.status(code).send(payload)
  return payload
}
```

**Comment by climba03003** [comment]
> 
> Is this a anticipated functional change for v4?

Although some of the usage is valid, it also confuse some of the user when they are mixing `callback` handler and `async-await` handler though out their application.

My point of view is encourage the usages that are valid in both `callback` and `async-await` in TypeScript.

**Comment by zekth** [comment]
@climba03003 any idea how we could solve this?

**Comment by climba03003** [comment]
> @climba03003 any idea how we could solve this?

I will take a look on next week.

**Comment by climba03003** [comment]
Not stale, I am checking this.

**Comment by zekth** [comment]
@climba03003 should we leave this one open?

**Comment by climba03003** [comment]
> @climba03003 should we leave this one open?

Not sure, but I would left it open.
Or is anyone is trying to make any effort on https://github.com/fastify/fastify/issues/4434 which would solve the same issue.

**Comment by jdjkelly** [comment]
@climba03003 @zekth it seems that this is a more immediate, practical solution to the problem of people wrongly using handlers vs. ESLint rules, which would probably be more comprehensive and address other usage problems with Fastify.

Reading this PR, why was it closed? Do you recall the blockers you hit? If I reopened, what would a PR need to do here to become mergable?

**Pull request closed without merging**
