### PR TITLE
chore(scripts): sort alphabetically ascending order

### PR DESCRIPTION
**Pull request by Fdawgs**
Sorted list should allow for quicker reference when looking at scripts.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by zekth — APPROVED** [review]
Good initiative

**Review by L2jLiga — APPROVED** [review]
Like this

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Regarding sorting, you might want to sort out the options in the docs (server.md)

**Pull request merged**
