### PR TITLE
docs(ecosystem): add fastify-event-bus

### PR DESCRIPTION
**Pull request by Shiva127**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by metcoder95 — COMMENTED** [review]
Have you considered delivering the TS types as well? That will enhance the DX when using your plugin. Currently it seems missing but `js-event-bus` seems written in TS so creating an abstraction on top should be straightforward.

**Comment by Shiva127** [comment]
> Have you considered delivering the TS types as well?

Very good idea @metcoder95! Done in version 1.0.1.

**Review by metcoder95 — APPROVED** [review]
LGTM 👍

**Review by Fdawgs — APPROVED** [review]

**Comment by Shiva127** [comment]
Thanks everyone!

**Pull request merged**
