### PR TITLE
fix: reply object not marked as sent for stream payloads

### PR DESCRIPTION
**Pull request by adrian-branescu**
Replication scenario: https://github.com/fastify/fastify-static/issues/232

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Could you add a test for this?

**Comment by adrian-branescu** [comment]
I've added a test case for catching regressions. It fails on _main_ branch and it passes with my fix. 
Please let me know if further changes are needed.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Thanks!

**Pull request merged**
