### PR TITLE
docs: reference new `@fastify/*` modules

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/fastify/issues/3733#issuecomment-1111188683.

The following plugins have not yet been migrated, so have not updated mentions of them:

- `aws-lambda-fastify`
- `fastify-awilix`
- `fastify-csrf`
- `fastify-schedule`
- `middie`
- `point-of-view`
- `under-pressure`

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
👍

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by mcollina** [comment]
Could you backport this to the v3 branch?

**Comment by Fdawgs** [comment]
> Could you backport this to the v3 branch?

Does this just need a `backport` label adding, to trigger the [backport workflow](https://github.com/fastify/fastify/blob/main/.github/workflows/backport.yml)?

**Comment by jsumners** [comment]
> > Could you backport this to the v3 branch?
> 
> Does this just need a `backport` label adding, to trigger the [backport workflow](https://github.com/fastify/fastify/blob/main/.github/workflows/backport.yml)?

https://github.com/fastify/fastify/actions/runs/2239549625

**Comment by Fdawgs** [comment]
Could someone please retrigger https://github.com/fastify/fastify/actions/runs/2239549625 ? 
https://github.com/fastify/fastify/pull/3858 should have fixed this.

**Comment by jsumners** [comment]
Still fails. I recommend doing it manually.

**Pull request merged**
