### PR TITLE
Allow custom object storing to Store instance for future use

### PR DESCRIPTION
**Pull request by allevo**
In some circumstances, plugins should read some properties from route definition.
This PR allows that.

### CODE REVIEW

**Comment by mcollina** [comment]
I would prefer _not_ have a key named `custom`, but rather keep the full option passed to the route in the store, so plugin can access all keys in there.

**Comment by allevo** [comment]
Yea, I completely agree with you.
This PR is about the feature not its implementation.

Do we allow all plugins to access to all properties defined in store ?
Maybe a plugin should export a symbol to make unique the store key, for "privacy" purpose.

**Comment by delvedor** [comment]
> but rather keep the full option passed to the route in the store, so plugin can access all keys in there.

@mcollina why? I don't see how a plugin can use the properties stored there.

I prefer the approach suggested by @allevo, and maybe change the `custom` ket to something more meaningful, such as `config`.

Let's not forget that the `Store` object is an hidden class, so in not that easy add custom properties at runtime, while use a general purpose `config` object could solve the problem easily.
Furthermore we could also add automatically the route string to the config object, so a general purpose plugin could know where is it (I'm thinking about a `preHanlder` hook or a `beforeHandler` utility).

**Comment by mcollina** [comment]
Ok as it is with the config nane instead.

**Comment by allevo** [comment]
> Furthermore we could also add automatically the route string to the config object, so a general purpose plugin could know where is it (I'm thinking about a preHanlder hook or a beforeHandlerutility).

@delvedor I don't understand.

I'll change `custom` to `config`

**Comment by delvedor** [comment]
@allevo we can store inside the config object the route string.
```js
config: {
  route: url // the url is declared few lines above
}
```
In this way a plugin can know in which route is running.

**Comment by allevo** [comment]
@delvedor ok I'll add `url` to config object

**Comment by mcollina** [comment]
LGTM
Il giorno ven 4 ago 2017 alle 20:47 Tomas Della Vedova <
notifications@github.com> ha scritto:

**Pull request merged**
