### PR TITLE
Fix requires in the benchmark scripts

### PR DESCRIPTION
**Pull request by sergiz**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

The https://github.com/fastify/fastify/pull/3048 moved the benchmark scripts, but the requires were not adapted to the new path, so they do not work in the current state. This PR fixes these paths.

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by RafaelGSS** [comment]
Could you rebase to `main`? I think that what broke the CI is some issue already solved.

**Comment by sergiz** [comment]
> 
> 
> Could you rebase to `main`? I think that what broke the CI is some issue already solved.

It is already based on the latest `main` (commit 1c3d4eeb8bae9aafaac29fdda1de5af9abb4bbbb).

It's a problem with types that fails CI and there was an update to `@types/node` released a few hours ago. That might be connected.

**Comment by RafaelGSS** [comment]
Can you rebase `main`, it's fixed now.

**Comment by sergiz** [comment]
> 
> 
> Can you rebase `main`? It's fixed now.

Done.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
