### PR TITLE
custom error handler can be able to handle contentTypeParser's errors

### PR DESCRIPTION
**Pull request by patoi**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added - No documentation change.
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by cemremengu** [comment]
I think this should target `next` and use the error codes introduced in #1168

**Comment by cemremengu** [comment]
Looks like this is already done in next though? :thinking:

**Comment by patoi** [comment]
I think this is a patch to v1.12.

**Comment by patoi** [comment]
Do I need to merge on next branch?

**Comment by cemremengu** [comment]
@mcollina will know better than me about that 😄

**Pull request merged**
