### PR TITLE
Add @gquittet/graceful-server to Ecosystem

### PR DESCRIPTION
**Pull request by gquittet**
👋 Hello everyone

Can I add a suggestion for https://github.com/gquittet/graceful-server?

## Why Graceful Server is useful
- Graceful Server is keeping track of all open connections and signaling them that the server is shutting down.
- Graceful Server is listening system events to safely close your API on interruption to avoid to keep opened ghost connections on your data sources.
- It is coming with the Kubernetes liveness and readiness out of the box.
- It support all NodeJS frameworks.
- Very simple to use.

## Why is it different from existing libraries
- It is a complete solution.
- It is dependency free.
- It has a KISS code base.
- You can customize what you want.
- It is very lightweight.
- It is in active development.

---

Graceful Server is a free and open-source project (MIT license) and it is used by 2 companies and get more downloads each days.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I would note that _tracking each incoming connection slows down throughput significantly_. Anyway, it's not a blocker.

**Comment by gquittet** [comment]
I've run some benchmarks without and with my library. You can find the result below.

The tool I used is [autocannon](https://github.com/mcollina/autocannon).

With these benchmarks I can assure that my library doesn't slow up the Rest API 🎉 

I've run the benchmarks on my MacBook Pro 15 (2019)

```
System: Kernel: Darwin 19.6.0 x86_64
CPU: Topology: 12-Core model: Intel Core i7-9750H
     Speed: 2600 MHz min/max: 400/400 MHz Core speeds (MHz): No speed data found for 12 cores.
Info: Processes: 537 Uptime: 13d 15h 25m Memory: used: Init: launchd Shell: -fish inxi: 3.1.05
```

### Without [@gquittet/graceful-server](https://github.com/gquittet/graceful-server)

#### JavaScript file

```javascript
const fastify = require('fastify')({ logger: true })

// Declare a route
fastify.get('/', async () => {
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

#### Result

##### First run

```
~/temp/test-fastify is 📦 v1.0.0 via ⬢ v14.13.1 took 30s 
❯ npm run bench

> test-fastify@1.0.0 bench /Users/gquittet/temp/test-fastify
> autocannon -c 1000 -d 30 http://localhost:3000/

Running 30s test @ http://localhost:3000/
1000 connections

┌─────────┬───────┬───────┬────────┬────────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5%  │ 99%    │ Avg      │ Stdev    │ Max    │
├─────────┼───────┼───────┼────────┼────────┼──────────┼──────────┼────────┤
│ Latency │ 61 ms │ 69 ms │ 103 ms │ 210 ms │ 74.24 ms │ 25.55 ms │ 684 ms │
└─────────┴───────┴───────┴────────┴────────┴──────────┴──────────┴────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬──────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg      │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼──────────┼─────────┼─────────┤
│ Req/Sec   │ 8087    │ 8087    │ 13735   │ 15623   │ 13395.27 │ 1701.84 │ 8086    │
├───────────┼─────────┼─────────┼─────────┼─────────┼──────────┼─────────┼─────────┤
│ Bytes/Sec │ 1.51 MB │ 1.51 MB │ 2.57 MB │ 2.92 MB │ 2.5 MB   │ 318 kB  │ 1.51 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴──────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

402k requests in 30.17s, 75.1 MB read
15 errors (0 timeouts)
```

##### Second run

```
~/temp/test-fastify is 📦 v1.0.0 via ⬢ v14.13.1 took 30s 
❯ npm run bench

> test-fastify@1.0.0 bench /Users/gquittet/temp/test-fastify
> autocannon -c 1000 -d 30 http://localhost:3000/

Running 30s test @ http://localhost:3000/
1000 connections

┌─────────┬───────┬───────┬────────┬────────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5%  │ 99%    │ Avg      │ Stdev    │ Max    │
├─────────┼───────┼───────┼────────┼────────┼──────────┼──────────┼────────┤
│ Latency │ 63 ms │ 72 ms │ 133 ms │ 193 ms │ 79.35 ms │ 28.34 ms │ 685 ms │
└─────────┴───────┴───────┴────────┴────────┴──────────┴──────────┴────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev  │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────┼─────────┤
│ Req/Sec   │ 6759    │ 6759    │ 12911   │ 15071   │ 12533.4 │ 1950.3 │ 6756    │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼────────┼─────────┤
│ Bytes/Sec │ 1.26 MB │ 1.26 MB │ 2.41 MB │ 2.82 MB │ 2.34 MB │ 365 kB │ 1.26 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┴─────────┘

Req/Bytes counts sampled once per second.

376k requests in 30.17s, 70.3 MB read
46 errors (0 timeouts)
```

### With [@gquittet/graceful-server](https://github.com/gquittet/graceful-server)

#### JavaScript file

```javascript
const fastify = require('fastify')({ logger: true })
const GracefulServer = require('@gquittet/graceful-server')

const gracefulServer = GracefulServer(fastify.server)

gracefulServer.on(GracefulServer.READY, () => {
    console.log('Im ready')
})

gracefulServer.on(GracefulServer.SHUTTING_DOWN, () => {
    console.log('shutdown')
})

gracefulServer.on(GracefulServer.SHUTDOWN, () => {
    console.log('im stopped')
})


// Declare a route
fastify.get('/', async () => {
  return { hello: 'world' }
})

// Run the server!
const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
    gracefulServer.setReady()
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

#### Result

##### First run

```
~/temp/test-fastify is 📦 v1.0.0 via ⬢ v14.13.1 took 30s 
❯ npm run bench

> test-fastify@1.0.0 bench /Users/gquittet/temp/test-fastify
> autocannon -c 1000 -d 30 http://localhost:3000/

Running 30s test @ http://localhost:3000/
1000 connections

┌─────────┬───────┬───────┬────────┬────────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5%  │ 99%    │ Avg      │ Stdev    │ Max    │
├─────────┼───────┼───────┼────────┼────────┼──────────┼──────────┼────────┤
│ Latency │ 62 ms │ 71 ms │ 145 ms │ 165 ms │ 77.47 ms │ 29.14 ms │ 841 ms │
└─────────┴───────┴───────┴────────┴────────┴──────────┴──────────┴────────┘
┌───────────┬────────┬────────┬─────────┬─────────┬──────────┬─────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%     │ 97.5%   │ Avg      │ Stdev   │ Min    │
├───────────┼────────┼────────┼─────────┼─────────┼──────────┼─────────┼────────┤
│ Req/Sec   │ 5243   │ 5243   │ 13415   │ 15055   │ 12840.87 │ 2232.33 │ 5241   │
├───────────┼────────┼────────┼─────────┼─────────┼──────────┼─────────┼────────┤
│ Bytes/Sec │ 980 kB │ 980 kB │ 2.51 MB │ 2.82 MB │ 2.4 MB   │ 418 kB  │ 980 kB │
└───────────┴────────┴────────┴─────────┴─────────┴──────────┴─────────┴────────┘

Req/Bytes counts sampled once per second.

385k requests in 30.18s, 72 MB read
43 errors (0 timeouts)
```

##### Second run

```
~/temp/test-fastify is 📦 v1.0.0 via ⬢ v14.13.1 took 30s 
❯ npm run bench

> test-fastify@1.0.0 bench /Users/gquittet/temp/test-fastify
> autocannon -c 1000 -d 30 http://localhost:3000/

Running 30s test @ http://localhost:3000/
1000 connections

┌─────────┬───────┬───────┬────────┬────────┬──────────┬──────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5%  │ 99%    │ Avg      │ Stdev    │ Max    │
├─────────┼───────┼───────┼────────┼────────┼──────────┼──────────┼────────┤
│ Latency │ 64 ms │ 74 ms │ 113 ms │ 139 ms │ 78.33 ms │ 34.64 ms │ 716 ms │
└─────────┴───────┴───────┴────────┴────────┴──────────┴──────────┴────────┘
┌───────────┬────────┬────────┬─────────┬─────────┬─────────┬────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%     │ 97.5%   │ Avg     │ Stdev  │ Min    │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼────────┼────────┤
│ Req/Sec   │ 4247   │ 4247   │ 13079   │ 14831   │ 12692.6 │ 2066.4 │ 4244   │
├───────────┼────────┼────────┼─────────┼─────────┼─────────┼────────┼────────┤
│ Bytes/Sec │ 794 kB │ 794 kB │ 2.45 MB │ 2.77 MB │ 2.37 MB │ 387 kB │ 794 kB │
└───────────┴────────┴────────┴─────────┴─────────┴─────────┴────────┴────────┘

Req/Bytes counts sampled once per second.

381k requests in 30.16s, 71.2 MB read
34 errors (0 timeouts)
```

**Comment by mcollina** [comment]
The last time I benchmarked this very same approach it showed a significant slowdown. Good to know!

**Pull request merged**
