### PR TITLE
Add missing documentation links

### PR DESCRIPTION
**Pull request by lmammino**
This PR fixes the problems of the documentation website described in https://github.com/fastify/website/issues/61 and https://github.com/fastify/website/issues/62.

Fixes https://github.com/fastify/website/issues/61, Fixes https://github.com/fastify/website/issues/62

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by vincent178** [comment]
it's false alarm, try to rerun ci

**Comment by lmammino** [comment]
Thanks @vincent178, it's all green now. Shall we merge or should we wait for more approvals on the PR?

**Comment by lmammino** [comment]
Sure @delvedor :)

**Comment by lmammino** [comment]
@delvedor, ✅ Done!

Only added Typescript, benchmark section was already there

**Pull request merged**
