### PR TITLE
test: migrated validation-error-handling from tap to node:test

### PR DESCRIPTION
**Pull request by reidn3r**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Proposals:

- [x] migrated all 23 tests from validation-error-handling.test.js file from tap to node:test

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]

**Review by dancastillo — APPROVED** [review]
LGTM

**Review by Eomm — APPROVED** [review]

**Comment by Eomm** [comment]
Could you run `lint:fix`?

**Review by gurgunday — CHANGES_REQUESTED** [review]
lint is failing like @Eomm said

**Comment by reidn3r** [comment]
done! @gurgunday @Eomm

**Review by gurgunday — APPROVED** [review]
thanks for your efforts!

lgtm

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
