### PR TITLE
add GH action benchmark

### PR DESCRIPTION
**Pull request by Eomm**
This action would like to be a utility to check roughly/fastest way the benchmark for some PR (like this one #1929)

So this action will run the bench on master and on the PR branch if we comment on the PR with the text `$run-benchmark`

Here an example of the output: https://github.com/Eomm/fastify/pull/2#issuecomment-602052050

I would test if this utility gives good data or not, but it should since the bench on https://github.com/fastify/benchmarks are run in GH

Ideas welcome!

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
I have implemented a similar action on the Pino repo. The only improvement I would like to make is having the results added as a comment to the thread. However, that won’t work for PRs coming from a fork due to permissions. I’m monitoring a GitHub community discussion about it, but GH staff has yet to respond.

**Comment by Eomm** [comment]
>  However, that won’t work for PRs coming from a fork due to permissions.

Oh, you are right, the `github.ref` [on comments](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts) is the default branch.

It should work if the `ref` will be set like [this](https://twitter.com/ManuEomm/status/1241020793225719809?s=20): `refs/pull/<pull id>/head` with some code to get the ID, I spot this comment about it https://github.com/actions/checkout/issues/58#issuecomment-545769838 I will try it!

Anyway, could you share the discussion with the GH community, please?

**Comment by jsumners** [comment]
https://github.community/t5/GitHub-Actions/quot-Resource-not-accessible-by-integration-quot-for-adding-a/m-p/33925#M1719

**Comment by mcollina** [comment]
Yes! You can also use https://github.com/mcollina/autocannon-compare to compare the two runs.

**Comment by delvedor** [comment]
Please rebase this pr against the new `master` branch, see https://github.com/fastify/fastify/issues/2056#issuecomment-612916945.

**Comment by Eomm** [comment]
Closing because right now this feature is blocked by github actions as pointed out by @jsumners 

I will monitor for updates and in case I will open a new PR 👍

**Comment by jsumners** [comment]
FYI, someone posted a hacky solution to the thread I linked. Basically, add a GH Action that is a cron job to monitor for recent updates and do things.

**Comment by jsumners** [comment]
It looks like GitHub has provided a fix to not being able to attach comments -- https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Pull request closed without merging**
