### PR TITLE
refactor: use `Object.hasOwn`

### PR DESCRIPTION
**Pull request by gurgunday**
Available since node 16

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by metcoder95 — APPROVED** [review]
LGTM, just out of curiosity, did we benchmark it just to see if there's possible performance regression?

**Comment by gurgunday** [comment]
> LGTM, just out of curiosity, did we benchmark it just to see if there's possible performance regression?

Additional note: they are aliases of each other in V8 AFAIK, so performance should be the same or slightly better under stress because of less property accesses

**Comment by jsumners** [comment]
> LGTM, just out of curiosity, did we benchmark it just to see if there's possible performance regression?

It should literally be nothing more than an alias of `Object.prototype.hasOwn.call(anObject, 'field')`.

**Review by jsumners — APPROVED** [review]

**Review by climba03003 — APPROVED** [review]

**Comment by gurgunday** [comment]
@Fdawgs not sure if this is really worth it, but just want to point out that a script could be used here I think :)

In any case, we might want to wait after all the Fastify v5 stuff is released first

**Comment by Fdawgs** [comment]
> @Fdawgs not sure if this is really worth it, but just want to point out that a script could be used here I think :)
> 
> 
> 
> In any case, we might want to wait until all the Fastify v5 stuff is released first

You've lost me.

**Comment by gurgunday** [comment]
A script can be used to transform all Object.prototype.hasOwnProperty calls to Object.hasOwn

**Comment by sourcecodeit** [comment]
> A script can be used to transform all Object.prototype.hasOwnProperty calls to Object.hasOwn for all Fastify repos

I guess a "find/replace in files" should work.

**Comment by Uzlopak** [comment]
You can do it yourself. Just clone all repos and search and replace in vscode.

**Pull request merged**
