### PR TITLE
Fix generic types (incorrect use of const keyword) in route.d.ts and instance.d.ts files.

### PR DESCRIPTION
**Pull request by bilaleren**
#### In main.ts
Ekran Resmi 2023-11-02 15 33 45

#### In types/instance.d.ts
Ekran Resmi 2023-11-02 15 34 17

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Duplicate of #5133

**Comment by bilaleren** [comment]
> Duplicate of #5133

Only the `instance.d.ts` file is available in the specified problem.

**Comment by meyfa** [comment]
`const` in generics was added in TypeScript 5.0 and should be valid like this. Are you perhaps still on TS 4?

**Comment by Uzlopak** [comment]
Closing as stale.

**Pull request closed without merging**
