### PR TITLE
docs: Remove ES module with NodeNext note

### PR DESCRIPTION
**Pull request by melroy89**
https://github.com/fastify/fastify/issues/4241 and https://github.com/smartiniOnGitHub/fastify-healthcheck/issues/20 both seems to be closed. This note can be removed.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
The issue of tracking the problem is
https://github.com/fastify/fastify/issues/4349

**Review by mcollina — APPROVED** [review]
lgtm

or @climba03003 are you blocking this?

I think this works now?

**Comment by climba03003** [comment]
> I think this works now?

For plugins, Yes. All of them should be migrated and works now.

> Are you blocking this?

Not blocking

**Comment by melroy89** [comment]
> For plugins, Yes. All of them should be migrated and works now.

Only a slight issue with the auto load issue. But that just needs to be fixed ASAP. And this comment is unrelated and not the answer anyway. For auto load plugin I need to set VITEST environment variable when using ESM in combination with Ts-Node.

**Comment by mcollina** [comment]
A PR to autoload would be amazing

**Pull request merged**
