### PR TITLE
Support explicitly setting fastify version to fix webpack regression

### PR DESCRIPTION
**Pull request by agramian**
This change allows explicitly setting the fastify version when initializing the instance to provide a workaround for the issue described in #2603. 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

*Note: I tried multiple times but the test run fails when I run locally and it seems to fail on my machine going back several commits on the master branch so it's not caused by this change.*

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I would actually prefer skipping the check if we can't load package.json.

**Review by jsumners — COMMENTED** [review]
👎 users of the library should not be assigning the version of the library.

**Comment by zekth** [comment]
Proper solution to this would be to set a const version in the `fastify.js` file instead of getting it within the `loadVersion` function. Only thing we need to do is ensuring the `package.json` version and the `fastify.js` version are tied in the test stack.

**Comment by mcollina** [comment]
We could also generate a `.js` that is not committed and generated before publish.

**Comment by zekth** [comment]
> We could also generate a `.js` that is not committed and generated before publish.

In this approach this generated file needs to be mocked in our test stack.

**Comment by kibertoad** [comment]
Or we could run generation script as part of test script.

**Comment by zekth** [comment]
> Or we could run generation script as part of test script.

indeed. i can take the point for this PR.

**Pull request closed without merging**
