### PR TITLE
fix: correct repository url in package.json

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Is there a reason we prefixed everything with git+?

**Comment by gurgunday** [comment]
Probably because NPM adds the `+git` prefix when you do `npm pkg fix`

**Comment by gurgunday** [comment]
Don't know if it's a bug or not

**Comment by Uzlopak** [comment]
INTERESTING. Ok, then nevermind.

**Pull request closed without merging**
