### PR TITLE
Make the root fastify instance a plain object

### PR DESCRIPTION
**Pull request by nwoltman**
Supersedes #705 

As @mcollina said in #705, Fastify shouldn't export a function. This PR makes Fastify export a plain object as the root Fastify instance instead of a function.

Adding support for `supertest` can be done separately if it's not too much of a burden.

This makes no difference to benchmarks.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nwoltman** [comment]
@mcollina Is that the kind of test you were looking for?

**Comment by mcollina** [comment]
yes.

**Comment by cagataycali** [comment]
LGTM also.

**Comment by nwoltman** [comment]
@mcollina @delvedor Looking for a merge (since this is labelled as a breaking change).

**Comment by veedeo** [comment]
after this change, how should I fix this code:
`http.createServer(fastify_app);`
It now fails with error:

> TypeError: "listener" argument must be a function
>     at _addListener (events.js:239:11)
>     at Server.addListener (events.js:297:10)
>     at new Server (_http_server.js:269:10)
>     at Object.createServer (http.js:34:10)

**Comment by delvedor** [comment]
@veedeo this change won't support your use case.
You should use the [`serverFactory`](https://github.com/fastify/fastify/blob/master/docs/Factory.md#serverfactory) option, which hasn't been released yet.
You can try it by installing our master branch:
```
npm i git+https://github.com/fastify/fastify.git
```

**Comment by veedeo** [comment]
Thanks @delvedor but Im not sure how to use it correctly.
Im using fastify within AWS lambda, the handler code looks like this:
```
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./app')
const server = awsServerlessExpress.createServer(app);
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```
Is it possible to get handler() method from the fastify app?

**Comment by nwoltman** [comment]
@veedeo You can get the `handler` like this:

```js
const awsServerlessExpress = require('aws-serverless-express')
const Fastify = require('fastify')

const fastify_app = Fastify({
  serverFactory: function (handler) {
    return awsServerlessExpress.createServer(handler)
  }
})
const server = fastify_app.server

exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```

However, this won't work as-is because the `fastify_app` still needs to be initialized by calling [`fastify_app.ready()`](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#ready), which is an asynchronous call. The `aws-serverless-express` module is only designed to work with Express, so it's not easy to make it work with Fastify.

**Comment by veedeo** [comment]
Thanks, now it works, I also added `app.ready(() => console.log('Ready'));` after configuring the routes.

**Comment by mcollina** [comment]
I think we should add some docs on this.Would you like to send a PR?

**Pull request merged**
