### PR TITLE
Use right promise type

### PR DESCRIPTION
**Pull request by orblazer**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Helo,
This PR fix the promise return type of `after`, `close` and `ready`.
And this fix return of `register` (not necessary return `then`).

Thanks

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
These methods are tricky to type since when they are called without callbacks then return the server instance so that they are chainable. And when no callback is provided, they return a promise (so they can be used in an async/await way)

**Comment by fox1t** [comment]
I need to double check this PR with the actual implementation

**Comment by mcollina** [comment]
I have a feeling this does not match our implementation.

**Comment by fox1t** [comment]
I've double-checked this. Our current implementation is correct. @orblazer may I ask you which limitations you faced and what made you open this PR?

**Comment by orblazer** [comment]
@fox1t i have face it because i can't catch the eventual error on ready or close.

**Comment by fox1t** [comment]
OK then substitute `PromiseLike` with `Promise` in the current implementation and it should fix. In fact, the difference between PromiseLike and Promise is that the first has only `then` method, the latter has `catch` too.
PromiseLike: https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es5_d_.promiselike.html
Promise: https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es5_d_.promise.html

**Comment by Ethan-Arrowood** [comment]
Better link to the Promise and PromiseLike definition we are actually using: https://github.com/microsoft/TypeScript/blob/71e881a7ee535b9770303fe96922863fe58421cd/src/lib/es5.d.ts#L1401

**Comment by fox1t** [comment]
> Better link to the Promise and PromiseLike definition we are actually using: https://github.com/microsoft/TypeScript/blob/71e881a7ee535b9770303fe96922863fe58421cd/src/lib/es5.d.ts#L1401

As far as I can it is identical to the two links to the documentation. Am I missing something? Btw nice addition, thanks for sharing.

**Comment by Ethan-Arrowood** [comment]
Yep just like using commit based ones so if people read this PR in the far future they'll retain context to what we are deciding on. 

@orblazer do you want to update this PR with the change proposed by @fox1t ?

**Comment by orblazer** [comment]
Sorry but i haven't understand, we keep `PromiseLike` ? Because initially i have set to `Promise` because the methods could be rejected

**Comment by Ethan-Arrowood** [comment]
> OK then substitute PromiseLike with Promise in the current implementation and it should fix this issue.

**Comment by mcollina** [comment]
Any update on this?

**Comment by orblazer** [comment]
Sorry, i doesn't have time for now to end this.

**Pull request closed without merging**
