### PR TITLE
[Website] First version of website with documentation

### PR DESCRIPTION
**Pull request by lmammino**
Implements complete website including home, documentation, ecosystem, benchmarks.

Live demo here: https://lmammino.github.io/fastify/

Reference #139

### CODE REVIEW

**Comment by mcollina** [comment]
The website looks amazing, it's fantastic. But we need to keep the `docs` folder as it is right now, keeping it browsable from Github. With this change, it's only available through the website.

Also each files has Jekyll metadata, and links are broken in Github.

Can we apply some pre-processing to the files before jekyll? So that we can keep them in github format, and apply changes dynamically?

**Comment by lmammino** [comment]
That's of course up for discussion and i totally understand your concerns @mcollina.

At the current stage i see two possible solutions for having a complete website including documentation:

1. Current proposal (a complete Jenkins website embedded in the project repo)
2. An external project (in another repo) that somehow fetches the files from the docs folder in the project repo.

Let me list some of the pros and cons i see in both solutions, so that can be maybe easier to figure out which one to pick

**Comment by lmammino** [comment]
Anyway, before ditching the Jekyll approach, I have an idea that might allow us to get rid of (almost) all the cons and have then an acceptable setup for everybody. If I have to resume it few steps:

- Move the full Jekyll setup in it's own folder (maybe `/website`) and exclude it from being published to npm with a `.npmignore` and to be scanned by eslint
- Reconfigure Jekyll to read the docs from `/docs` (that should be doable in the config)
- Reconfigure all the links in the doc to follow the same filename that we have on github `/docs/CamelCase.md` (this, in theory should allow us to have cross-compatible links).

(the frontmatter remains, but personally I don't see it as an issue)

I'll have a peek at this probably this evening and let you now my findings ;)

**Comment by lmammino** [comment]
@mcollina @delvedor 

Unfortunately, after some research i couldn't figure out a way to keep the website in one folder and the docs in another (non nested) folder. At this stage i think we can only resort to option 2.

I am not sure if i will have much free time in the next few weeks to keep experimenting with this but here is what i think could be done:

- setup a new repo (fastify/website ? )
- this repo will simply host a build process that contains all the needed resources for creating a static website and the main fastify repo as a submodule (so that the docs markdown files can be used as well).
- we can use any static website generation tool (probably metalsmith being the simplest)
- the build should be triggered by a ci (Travis, circle or something else) everytime there's a change on master **in the fastify/fastify repository**.
- when the static website is built the ci should push the new version into some service that will provide the static website hosting (github pages, S3, etc...), This way the process will be fully automated end to end.

Let me know your views on this and in any case, regardless the tools we end up using, it should be fairly easy to import my design, in case you liked it 😉

**Comment by mcollina** [comment]
So, how about we deploy a fastify server somewhere, that receives a push whenever we do a release on github, and update itself - maybe we can even support the docs for multiple versions.

**Comment by lmammino** [comment]
@mcollina I don't think we will need to manage a *real* server (as you know, I am all about *serverless* these days 😆 ). We can probably get most of the things done with a custom CI pipeline (we can get a long way with Circle CI free plan in my experience, but the choice of a CI system shouldn't make much difference).

So, this is the scenario I have in my head.
Assuming we have a repo with all the needed assets and scripts to build the website, that's the pipeline I imagine:

1. we fetch the website repo (the one with all the assets and the build scripts).
2. we fetch all the releases of fastify using [GitHub APIs](https://developer.github.com/v3/repos/releases/)
3. (optional) filter only the latest patch releases for every minor (e.g. **0.25.3** will be used to generate the documentation for **0.25.X**)
4. (optional) we fetch also the current fastify master and create a special version of the doc for it
5. Move the `docs` folder from every release into the website sources
6. Run the static website builder (metalsmith probably being the most flexible)
7. Copy the build folder to the destination hosting platform (I'd suggest s3 + cloudfront)

How does this sound?

If you like this approach, how could we organise the access to resources (repository, hosting, etc.)? Of course this is not priority as I can, for now, create a demo process on my own spaces and if we are happy with the results we can decide where/how to move it into a *fastify-owned* space.

PS: since this might take me a while (as I would be quite busy in the upcoming weeks) it would be probably smart to use docsify for now (reference: #145)!

**Comment by mcollina** [comment]
That would be fantastic @lmammino, I would say go for it. We are using a similar setup for our new website, and it's working well for us.. so let's do it! I can provide some AWS credentials for this if you need them.

**Comment by lmammino** [comment]
Great, i'll keep you guys posted about my progress. I will start on my own resources and then we can figure out how to migrate to more official ones 😉

Have a good night

**Comment by lmammino** [comment]
Slowly started to play a bit with the latest idea: https://github.com/lmammino/fastify-website I'll update you about my progress

**Comment by mcollina** [comment]
Awesome work!

**Comment by lmammino** [comment]
Progress update:

Here's (again) my current repo: https://github.com/lmammino/fastify-website

And here you have a preview of the current rendered result from the pipeline: http://fastify-website.s3-website-eu-west-1.amazonaws.com/

Even if the code is still very quick'n'dirty, I am already downloading releases and rendering multiple versions of the documentation.

Anyway, there are few things missing before we can consider this ready to be transfered:

 - [ ] Create index pages for the documentation (current /docs is a 404)
 - [ ] Create an error page for 404
 - [ ] Review copy and update pages (benchmark and ecosystem probably are not up to date anymore)

Plese, feel free to help me with the latest point.

PS: if you want a preview of the docs pages (since they are directly accessible through the index pages) have a look [here](http://fastify-website.s3-website-eu-west-1.amazonaws.com/docs/v0.26.x/Reply/). From there you can navigate easily between sections and versions

**Comment by delvedor** [comment]
You are doing an amazing job!

> Review copy and update pages (benchmark and ecosystem probably are not up to date anymore)

How can I help you here?

**Comment by mcollina** [comment]
This is absolutely amazing. You should really do a blog post/tutorial/video on how to do something like this. Congrats!

**Comment by lmammino** [comment]
I am really glad you are appreciating the work. Honestly, i don't think it's rocket science, but I will think about creating one or more articles about it to describe the process (and maybe I'll ask you two to review it 😉 ).

@delvedor (but also @mcollina), you can submit a PR with all the needed changes. Here is a list of the files that might require your attention:

- [metadata.json](https://github.com/lmammino/fastify-website/blob/master/src/website/metadata.json) - Contains some generic metadata used all over the website (it can also be used to specify a google analytics track id, in case you have one you want to use to track website visits.
- [acknowledgements.yml](https://github.com/lmammino/fastify-website/blob/master/src/website/data/acknowledgements.yml) - structured data used to build the acknowledgement list on the home page
- [benchmarks.yml](https://github.com/lmammino/fastify-website/blob/master/src/website/data/benchmarks.yml) - Structured data used to build the benchmark page
- [ecosystem.yml](https://github.com/lmammino/fastify-website/blob/master/src/website/data/ecosystem.yml) - Structured data for the list of plugins, used both on the home page and in the ecosystem page
- [team.yml](https://github.com/lmammino/fastify-website/blob/master/src/website/data/team.yml) - Structured data for the team section on the home
- [error.md](https://github.com/lmammino/fastify-website/blob/master/src/website/content/error.md) - Content for the 404 page
- [home.html](https://github.com/lmammino/fastify-website/blob/master/src/website/layouts/home.html) - Layout for the home page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)
- [ecosystem.html](https://github.com/lmammino/fastify-website/blob/master/src/website/layouts/ecosystem.html) - Layout for the ecosystem page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)
- [docs_page.html](https://github.com/lmammino/fastify-website/blob/master/src/website/layouts/docs_page.html) - Layout for the documentation page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)
- [benchmarks.html](https://github.com/lmammino/fastify-website/blob/master/src/website/layouts/benchmarks.html) - Layout for the benchmark page ([nunjucks](https://mozilla.github.io/nunjucks/) syntax)

In case you want to see the outcome of the changes locally, before submitting the PR you should find all the necessary instructions to do so in the [README](https://github.com/lmammino/fastify-website/blob/master/README.md#build).

**Comment by lmammino** [comment]
For what concerns me I think the website is ready (I added the missing docs index pages and fixed the menu on mobile).

The only things left, because starting to discuss wether to migrate everything into official fastify spaces (github/aws) is to review everything and maybe update the copy as discussed above :)

I'll leave this boring task to you guys and I will look forward to receiving your feedback/PRs.

**Comment by mcollina** [comment]
Is this PR needed? Can we move the discussion to a new one?

Would you mind moving the website to the fastify org?

How is a job kicked off to generate the full website when a new release is out? Or this is a manual step atm?

**Comment by lmammino** [comment]
Hello @mcollina,

> Is this PR needed? Can we move the discussion to a new one?

No, we can definitely close it as soon as we clarify the other points here and reopen the discussion in the website repo.

> Would you mind moving the website to the fastify org?

I just tried to transfer the repo and that's the outcome:

screen shot 2017-08-16 at 10 07 15
 
I Think you should add me into the org (even for a short time) to allow me to transfer the repo.

> How is a job kicked off to generate the full website when a new release is out? Or this is a manual step atm?

Currently the website build is kicked by changes in the website repository. There should be a way to configure GitHub to trigger a build every time there is a change also in the main Fastify repo, but again I think i need to be in the org in order to try that.

**Comment by mcollina** [comment]
@lmammino I've sent an invitation for this org when I've sent the previous comment.

**Comment by lmammino** [comment]
Sorry I missed your invitation before writing my response 😅

Closing this now. I am creating dedicated issues in the new repository.

**Pull request closed without merging**
