### PR TITLE
chore: sync next branch

### PR DESCRIPTION
**Pull request by Uzlopak**
Do NOT SquashMerge.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@fastify/leads 

Can someone of you please merge this not via squash but via normal merge to keep the commit history?

**Comment by jsumners** [comment]
We can't rebase and merge this because there are conflicts.

**Comment by Uzlopak** [comment]
I dont see any conflict.

**Comment by climba03003** [comment]
Why will need the `main-next` branch?

**Comment by jsumners** [comment]
> I dont see any conflict.

fastify - Vivaldi 2023-12-16 09-08-02

🤷‍♂️

**Comment by Uzlopak** [comment]
Maybe you see this because you are lead? I dont see this,

main-next to resolve the merge conflicts. I assume if I dont do this, I would commit into main branch.

**Comment by metcoder95** [comment]
Just to confirm what @Uzlopak says, I can't also see the `conflicts` warning 🤔 

image

**Comment by climba03003** [comment]
> Just to confirm what @Uzlopak says, I can't also see the `conflicts` warning 🤔

You need to change the option to "Rebase and merge" and it has conflict.

image

**Comment by metcoder95** [comment]
Oh, got it; thanks. I kind of believed it was deactivated

**Comment by climba03003** [comment]
I still think it is wrong.
The message show it is merging `next` into `main-next`.
image

For what we want is `main` into `next`.
image

**Comment by Uzlopak** [comment]
I manually merged it.

**Comment by climba03003** [comment]
The Git Tree is odd for me.

Current,
image
Should be,
image

At least it is not clearly see what it intended to do.

**Comment by Uzlopak** [comment]
What should we do? The merge conflicts are getting quite out of hand.

**Comment by climba03003** [comment]
@Uzlopak I created a new branch https://github.com/fastify/fastify/tree/clean-next which requires a force push and cleanup the history.
You can double check if there is any problem.

**Pull request merged**
