### PR TITLE
feat: Add hook name within timeout error message

### LINKED ISSUE #5850: Include hook names in timeout errors if available
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently it is very difficult to debug issues happening within hooks. E. g. if one of the `onReady` hooks is timing out, it is very difficult to understand which exact hook is at fault.
In case a named function was passed as a hook, we actually have useful information that can be used to narrow down the source of the problem. It would be helpful to include it in the error thrown from the fastify side.

### Motivation

It is difficult to debug issues with hooks when it is unclear which hooks are causing issues

### Example

```js
fastify.addHook('onReady', async function NamedOnReadyHook () {
  // Some async code
  await loadCacheFromDatabase()
})
```

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #5850 

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
CI is red, the changes itself look good to me.

**Comment by kibertoad** [comment]
yeah, will fix after I am done flying

**Comment by kibertoad** [comment]
@climba03003 Can you take another look, please?

**Review by climba03003 — APPROVED** [review]

**Comment by Fdawgs** [comment]
Thanks for this btw @kibertoad, looks really useful!

**Pull request merged**
