### PR TITLE
fix: routeShortHandOptions type updated

### PR DESCRIPTION
**Pull request by Gimnath-Perera**
#### Changes 
- missing types to routeShortHandOptions added
- added a fix for #4859 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
```
Suites:   ​128 passed​, ​128 of 128 completed​
Asserts:  ​​​6990 passed​, ​4 skip​, ​of 6994​
```
```
| Stat    | 2.5%  | 50% | 97.5% | 99%  | Avg      | Stdev    | Max  |
|---------|-------|-----|-------|------|----------|----------|------|
| Latency | 4 ms  | 9 ms| 12 ms | 14 ms| 7.83 ms  | 2.86 ms  | 62 ms|

| Stat      | 1%     | 2.5%   | 50%    | 97.5%  | Avg       | Stdev    | Min    |
|-----------|--------|--------|--------|--------|-----------|----------|--------|
| Req/Sec   | 104383 | 104383 | 121087 | 125119 | 119889.07 | 4897.82  | 104352 |
| Bytes/Sec | 19.6MB | 19.6MB | 22.8MB | 23.5MB | 22.5MB    | 922kB    | 19.6MB |

```

- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Would you mind to add a test [here](https://github.com/fastify/fastify/blob/master/test/types/index.ts)?

**Review by climba03003 — CHANGES_REQUESTED** [review]
I would say a NO here. It is the same as https://github.com/fastify/fastify/pull/4655 which cause regression of https://github.com/fastify/fastify/issues/4705

**Comment by Gimnath-Perera** [comment]
> I would say a NO here. It is the same as #4655 which cause regression of #4705

So this change is not needed ??

**Comment by climba03003** [comment]
> So this change is not needed ??

It is needed, but it should not cause the same regression mention above.
Your fix is the same as before means same problem will pop up.

**Comment by Uzlopak** [comment]
Closing due to inactivity.

**Pull request closed without merging**
