### PR TITLE
breaking changes must be merged by a core member

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by delvedor** [comment]
lol, why the coverage has increased? :P

**Comment by allevo** [comment]
But who will attach the labels to an issue?

**Comment by mcollina** [comment]
anyone :).

**Comment by delvedor** [comment]
Why appveyor is taking so much time?

**Comment by jsumners** [comment]
Because Windows.

**Comment by StarpTech** [comment]
Appveyor should ignore these files https://github.com/fastify/fastify/blob/master/appveyor.yml#L17

**Comment by StarpTech** [comment]
Yes, the build was not triggered.

**Comment by delvedor** [comment]
@mcollina @jsumners given what said @StarpTech, could be this related to the "required" step?

**Comment by jsumners** [comment]
Yes. Maybe the requirements can be relaxed in some way?

**Comment by mcollina** [comment]
I have relaxed the checks.

**Pull request merged**
