### PR TITLE
Remove broken link from Server documentation

### PR DESCRIPTION
**Pull request by simonplend**
If this link was working it seems that the page would have been linking to itself, so I've removed it completely.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Ethan-Arrowood — APPROVED** [review]

**Review by jsumners — CHANGES_REQUESTED** [review]
I'd rather see us actually fix this instead of making the documentation less easy to navigate.

https://github.com/fastify/website/issues/189

**Comment by simonplend** [comment]
> I'd rather see us actually fix this instead of making the documentation less easy to navigate.
> 
> https://github.com/fastify/website/issues/189

I'm all for fixing this if that's possible, but where should it be linking to? As far as I can tell this link was intending to link to the page that it was on, which seems a little odd.

**Comment by jsumners** [comment]
> > I'd rather see us actually fix this instead of making the documentation less easy to navigate.
> > [fastify/website#189](https://github.com/fastify/website/issues/189)
> 
> I'm all for fixing this if that's possible, but where should it be linking to? As far as I can tell this link was intending to link to the page that it was on, which seems a little odd.

Yeah, I can see how that is odd.

**Review by jsumners — APPROVED** [review]
LGTM

**Review by L2jLiga — APPROVED** [review]

**Pull request merged**
