### PR TITLE
fix: reply.d.ts missing hijack function

### PR DESCRIPTION
**Pull request by pmjhonwang**
fix reply.d.ts missing hijack funciton

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by pmjhonwang** [comment]
https://github.com/fastify/fastify/blob/master/lib/reply.js#L107

**Review by RafaelGSS — COMMENTED** [review]
Can you add a test over here https://github.com/fastify/fastify/blob/master/test/types/reply.test-d.ts#L23 as well?

**Review by 3imed-jaberi — APPROVED** [review]

**Review by L2jLiga — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
