### PR TITLE
test: refactor logger test

### PR DESCRIPTION
**Pull request by climba03003**
1. Refactor to use `async-await`
2. fix `sonic-boom` never close file

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
I am out of idea why `tap` is keep running. cc @fastify/core 

image

**Comment by Eomm** [comment]
Must say that locally it works 😓 
Will try to suggest something 🤝

**Comment by Eomm** [comment]
I read that the runners have been updated: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

I would get a green pipeline first - then check the diff tbh

**Comment by Eomm** [comment]
@climba03003 It still fails - could it be an issue with something else and not related to the host? 🤔

**Comment by jsumners** [comment]
The issue seems to be this recently added test:

https://github.com/fastify/fastify/blob/d0a1e8c1c9be33aa6cae9631163dd18e2bd3f784/test/route.test.js#L1497-L1509

I had a suspicion at the time that the timeout would be unreliable in CI. The CI environment is not consistent and is very prone to taking an excessive amount of time to execute code. Not sure what to do about it.

**Comment by Eomm** [comment]
image

**Comment by climba03003** [comment]
We should remove `node@20` first.

**Comment by Eomm** [comment]
Hey @climba03003 could we restore the CI?

@fastify/core then could we merge this high priority PR?
Our CI is too much 

> We should remove `node@20` first.

I had node19 failing for 2 runs.. I tried.. This is a poker match 🤦🏼

**Comment by climba03003** [comment]
It seems all good now?

**Comment by climba03003** [comment]
I will do a rebase.

**Comment by Eomm** [comment]
> It seems all good now? I will do a rebase and cleanup.

It requires at least one manual re-run of all the failed job.. I wonder if the issue is that we run too many things

**Comment by climba03003** [comment]
> I wonder if the issue is that we run too many things

We can split the `logger.test.js` into multiple files to see if it helps.

**Comment by climba03003** [comment]
Looks absolutely better.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fdawgs** [comment]
You absolute wizards @climba03003 and @Eomm

**Pull request merged**
