### PR TITLE
docs: add set-cookie special case

### PR DESCRIPTION
**Pull request by genzyy**
#### Fixes [#3409 ](https://github.com/fastify/fastify/issues/3409)
- Added documentation about the `set-cookie` when sending multiple values as cookie.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — CHANGES_REQUESTED** [review]
Please update your local branch and this PR. There are way too many changed files in this PR.

**Comment by genzyy** [comment]
> Please update your local branch and this PR. There are way too many changed files in this PR.

So I should create a new branch with base as main right? and then add the documentation?

**Comment by jsumners** [comment]
> > Please update your local branch and this PR. There are way too many changed files in this PR.
> 
> So I should create a new branch with base as main right? and then add the documentation?

Yes. You have branched off of `next` and are attempting to target the `main` branch. This is should not be done.

**Comment by genzyy** [comment]
> > > Please update your local branch and this PR. There are way too many changed files in this PR.
> > 
> > 
> > So I should create a new branch with base as main right? and then add the documentation?
> 
> Yes. You have branched off of `next` and are attempting to target the `main` branch. This is should not be done.

My bad. I'll create a new branch and I'll request with that one.

**Pull request closed without merging**
