### PR TITLE
Add license badge next to npm badge

### PR DESCRIPTION
**Pull request by trivikr**
#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
why is this needed?

**Comment by trivikr** [comment]
For easy identification of license
Some popular projects like [Vue](https://github.com/vuejs/vue), [react](https://github.com/facebook/react) display it.

**Comment by trivikr** [comment]
Just visited other popular GitHub projects (like bootstrap, webpack, express), and I couldn't find the license badge.

Vue and React might be displaying it as React had an issue with their BSD3 with patents license before they switched to MIT in August 2017
Fastify doesn't need to display license as it's anyway described in LICENSE file and npmjs link also displays it.

**Comment by StarpTech** [comment]
@trivikr is badge-day today? 😄

**Comment by trivikr** [comment]
@StarpTech Yeah, I had reserved this weekend to write more unit tests for Fastify to understand the code better - but it got interfered with other last minute plans with friends.

So, badge day it is! :stuck_out_tongue:

**Pull request closed without merging**
