### PR TITLE
docs: repoint readers to shared `.github` files

### LINKED ISSUE #5241: Drop security, governance, coc, and contributing files from this repo?
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Rather than maintaining/updating two versions of the same document, can we drop `SECURITY.md`, `GOVERNANCE.md`, `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` from this repo so that the shared ones from [`fastify/.github`](https://github.com/fastify/.github) will be used instead?
See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

### PR DESCRIPTION
**Pull request by Fdawgs**
closes #5241 

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]

**Comment by Fdawgs** [comment]
> Help me understand how this complies with our desire to have a complete reproducible project published to npm.

Rest of the Fastify repos/plugins do not have these files published with them, and they are not really documentation files (they're guides on how to contribute to the GitHub repo(s)), so I wouldn't consider them as essential for a reproducible project.

**Review by mcollina — APPROVED** [review]
lgtm

I don't think any of these are actually needed for reproducing the project. However, it would be nice to include them nevertheless.

**Comment by mcollina** [comment]
I'm also ok in not landing this if @jsumners objects.

**Comment by jsumners** [comment]
I'm objecting or blocking. The reasoning works for me.

**Comment by Eomm** [comment]
> I'm objecting or blocking. The reasoning works for me.

I don't get it 😓

**Comment by jsumners** [comment]
> > I'm objecting or blocking. The reasoning works for me.
> 
> 
> 
> I don't get it 😓 

Fixed. Silly keyboard leaving out words.

**Pull request merged**
