### PR TITLE
Add new packages for the fastify ecosystem

### PR DESCRIPTION
**Pull request by kenriortega**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — CHANGES_REQUESTED** [review]
These are not in alphabetical order.

**Comment by climba03003** [comment]
I have checked both plugins, and you are mixing the `async-await` style and `callback` style inside `content type parser`. I think it is better to be fixed before it added to the ecosystem.

https://github.com/kenriortega/fastify-msgpack/blob/dcc1a668ebea6f51c55e700d65d479e2cf76366a/index.js#L25
https://github.com/kenriortega/fastify-protobufjs/blob/5c6ca97fee7755e9f24e801f1abd74af7bcb11d0/index.js#L24

**Comment by StarpTech** [comment]
Much more important is to include tests.

**Comment by kenriortega** [comment]
Thx for yours feedback I try to fix my code and follow all recommendations. I'm working hard for integrate this in you awesome ecosystem.

**Review by jsumners — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
