### PR TITLE
On ready backport

### PR DESCRIPTION
**Pull request by Eomm**
Backport of #2166 
Related #2123 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
It seems CI is failing.

**Comment by Eomm** [comment]
The logger test has changed the output, I remember this issue but can't remember the cause.

If you set await inject all is fine.

I would like to re check better

**Comment by mcollina** [comment]
@Eomm any updates on this one?

**Comment by Eomm** [comment]
> @Eomm any updates on this one?

Done 👍

**Pull request merged**
