### PR TITLE
fix - docs - hooks - error handling

### PR DESCRIPTION
**Pull request by wallasfmorais**
#### Checklist

- [ ] (n/a) run `npm run test` and `npm run benchmark`
- [ ] (n/a) tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by wallasfmorais** [comment]
(1):
```
const result = await asyncMethod()
// Error occurred
if (!result) {
throw new Error('Some errors occurred.')
}
```
or
(2):
```
await asyncMethod()
// Error occurred
throw new Error('Some errors occurred.')
```

**Comment by mcollina** [comment]
1) or even remove completely the throw.

**Comment by wallasfmorais** [comment]
Alright, in a moment.

**Comment by RafaelGSS** [comment]
:confused: I made it https://github.com/fastify/fastify/commit/321c6b62111d0edde861d71a9022f420c6a87450

**Comment by RafaelGSS** [comment]
:confused: In "files changed" show me an alteration that I already did it https://github.com/fastify/fastify/commit/321c6b62111d0edde861d71a9022f420c6a87450.

I think that is a bug of Github.

**Comment by wallasfmorais** [comment]
Same here, I saw just before I send the PR.
Even fork from 1 min before and was the same.

Without knowing what to do, I keeped.

**Comment by wallasfmorais** [comment]
> So, I close this and send another PR or no need?

@mcollina, @delvedor

**Pull request merged**
