### PR TITLE
chore: refactor Error-typings and tests

### PR DESCRIPTION
**Pull request by svrnwnsch**
The error code FST_ERR_VALIDATION is used as an error code in lib/context.js

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Is it doable to add a test that compares the `FastifyErrorCodes` with the error codes https://github.com/fastify/fastify/blob/61b86760019c85afbef6cc0f175c75870381ed04/lib/errors.js#L425 ?

**Comment by Uzlopak** [comment]
Added unit tests, fixed a bug in FST_ERR_ROUTE_REWRITE_NOT_STR

@Eomm PTAL

**Review by Fdawgs — APPROVED** [review]
I think the PR title could be longer, maybe slap the entire works of Shakespeare into it for good measure?

**Comment by Uzlopak** [comment]
Sure. How about: `Errors once made are now rectified.`

Its not shakespeare but should be similar.

**Pull request merged**
