### PR TITLE
add option to disable startup logging

### PR DESCRIPTION
**Pull request by SerayaEryn**
This adds an option, additional to the `disableRequestLogging` option added by #1629, that allows to disable the log message that is being logged after `fastify.listen()` was called.
This allows to log a custom message instead of `Server listening at <address>`.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
While I see the reasoning behind #1629, I'm not sure what harm logging "server listening at" might cause to an application.

**Comment by SerayaEryn** [comment]
Logging „server listing on“ does no harm, I agree. In most usecases it will be just fine.

This just allows to customize that message for example by logging additional information.

**Comment by jsumners** [comment]
Does adding a log via the `ready` callback, or promise resolution, not provide the ability to log such information?

**Comment by SerayaEryn** [comment]
> Does adding a log via the `ready` callback, or promise resolution, not provide the ability to log such information?

Ok, I'll use the `ready` callback then. I'll close this PR.

**Pull request closed without merging**
