### PR TITLE
Adding reference to plugin fastify-response-time

### PR DESCRIPTION
**Pull request by lolo32**

### CODE REVIEW

**Comment by delvedor** [comment]
Hi! Thank you for contributing!
We are working on the `onSend` hook, which will solve also this problem.
Your solution will not work in every case, because if there is an error in some hook before the user handler, in a middleware or during the validation, the `X-Response-Time` header will never be set.
We are very close to finish the `onSend` hook, so if you can wait, it will improve also your plugin :)

**Comment by mcollina** [comment]
@lolo32 what @delvedor means is that using the 'on-headers' as is will _likely_ create some performance issues because it is overriding a method in the original request. A better approach would be to use `onSend`  when it's ready.

**Comment by StarpTech** [comment]
Hint: `onSend` was merged in master

**Comment by lolo32** [comment]
New PR #444 done, with updated plugin version. This PR need to be closed

**Pull request closed without merging**
