### PR TITLE
fastify-route-group

### PR DESCRIPTION
**Pull request by TakNePoidet**
Added the 'fastify-route-group plugin'

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
What does this provide that is not already implemented by `.register()`?

**Comment by TakNePoidet** [comment]
Nothing significant yet. This is another way of making routes, it is shorter.

```typescript
fastify.register(
  (fastify: FastifyInstance, options: any, done) => {
    fastify.get('/posts.get', async () => 'Get posts from API');
    fastify.get('/posts.get.get', async () => 'Get users from API');
    done();
  },
  {
    prefix: '/api/methods'
  }
);

router.namespace('/api/methods', () => {
  router.get('/posts.get', async () => 'Get posts from API');
  router.get('/posts.get.get', async () => 'Get users from API');
});
```

It will be more convenient and understandable if the developer developed in Laravel.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
