### PR TITLE
add fastify-serve-swagger-ui to the list of plugins

### PR DESCRIPTION
**Pull request by PavelPolyakov**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by PavelPolyakov** [comment]
@delvedor 
`fastify-swagger` and [fastify-swagger-ui](https://www.npmjs.com/package/fastify-swagger-ui) read/build swagged specification from the routes definition.

my plugin reads it from the file (in my case I craft it manually) OR just injects the custom url to the `swagger-ui` output.

**Comment by delvedor** [comment]
Ok, why not add this functionality directly to [`fastify-swagger`](https://github.com/fastify/fastify-swagger) instead of build another plugin?

**Comment by PavelPolyakov** [comment]
@delvedor 
I don't mind, I thought that that plugin had some high purpose idea :)

I'll prepare PR there.

**Comment by corbinu** [comment]
@PavelPolyakov I would actually really prefer it was not merged or it was optional. I don't like to host my swagger UI directly out of my api server. I generate the swagger file on my CI and then host the UI in S3. To me these should be two separate plugins.

**Comment by PavelPolyakov** [comment]
@corbinu 
> I would actually really prefer it was not merged or it was optional
What do you mean? Using `fastify-swagger` or any other plugin is already optional.

Of course it will be optional to expose given specification over the automatically gathered one.

**Comment by corbinu** [comment]
Sorry I mean that you not merge fastify-serve-swagger-ui into fastify-swagger as @delvedor suggests. They serve two different purposes. I would rather you go ahead with this PR instead as you originally planned.

**Comment by delvedor** [comment]
@corbinu I think that for the swagger support is better to have a single plugin with all the functionalities instead of many plugins with slightly different names that at the end of the day offers the same thing.
I think that the plugin written by @PavelPolyakov could fit very nicely in `fastify-swagger`, and behave accordingly to the options given as input.

**Comment by PavelPolyakov** [comment]
FYI I'd rather go with joint solution there is a place for the separate module, but if main module maintainer agrees that this functionality could land in `fastify-swagger` it's better to have one module over the many similar with the name `*swagger`.

Here is my WIP PR to the `fastify-swagger`:
https://github.com/fastify/fastify-swagger/pull/30

**Comment by PavelPolyakov** [comment]
functionality is available through the [fastify-swagger](https://github.com/fastify/fastify-swagger)

**Pull request closed without merging**
