### PR TITLE
feat(backport 4.x): add body parsing on copy move mkcol methods

### PR DESCRIPTION
**Pull request by johaven**
- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Already done in version 5, but not available in version 4 (and it's very useful !)

### CODE REVIEW

**Review by metcoder95 — APPROVED** [review]

**Review by jsumners — COMMENTED** [review]
My general review is that whatever architecture is needed to be added such that non-standard methods can be added via a plugin should be added, and then all of the webdav methods removed and added via such a plugin.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Currently it's not possible to specify those via a plugin.

**Comment by jsumners** [comment]
> Currently it's not possible to specify those via a plugin.

Right. I'm suggesting that some interested party take the time to make it so. We can back these changes out once the feature is implemented.

**Review by Eomm — APPROVED** [review]
I'm ok with merging it and open an issue to create an API to let plugins add new HTTP methods

**Comment by johaven** [comment]
Why not check only standard http methods that should not have a body and assume that the others can have a body. 
This is much more open and efficient. 
Most web servers accept all methods without restricting the use of a body. 
Most clients allow adding a body to methods that should not have one.

**Comment by Eomm** [comment]
I think:

- by default we should follow standards
- via APIs, we can provide non-standard behaviour

image

**Comment by jsumners** [comment]
Exactly as @Eomm states.

**Comment by johaven** [comment]
@mcollina Is there a new release planned that includes this feature ?

**Pull request merged**
