### PR TITLE
Reorder Generic Types of FastifyReply

### PR DESCRIPTION
**Pull request by sceccotti89**
Issue: #4414

I didn't feel the need to write new tests since we are just reordering reply types.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
What does @fastify/typescript think of this change?

**Review by climba03003 — CHANGES_REQUESTED** [review]
Re-order is good, but it is not safe to land in `main`.

**Comment by sceccotti89** [comment]
I do agree on that because it might be a breaking change. If you may suggest a different destination branch I'm more than willing to change it.

**Comment by climba03003** [comment]
You can target to `next` branch.

**Comment by sceccotti89** [comment]
Thanks @climba03003. Target changed to `next`.

**Comment by Uzlopak** [comment]
I changed the title to express better what this PR is doing.

**Comment by climba03003** [comment]
Can you check the target to `main` and rebase again.
It included other commit in your PR.

**Comment by sceccotti89** [comment]
Sorry, I think I panicked for nothing. That's not the fastify:next branch but mine.

**Review by climba03003 — APPROVED** [review]

**Comment by sceccotti89** [comment]
@climba03003 I've been finally able to rebase the pull request. Sorry but I don't feel comfortable with rebasing.

**Comment by sceccotti89** [comment]
@climba03003 I don't want to go off-topic, but I'd like to know more about the GUI you're using (is it tortoise, perhaps?). I normally use this command `git rebase -i HEAD~<number>` but, as you said, it's not always user friendly (especially if there has been a merge).

**Comment by climba03003** [comment]
> @climba03003 I don't want to go off-topic, but I'd like to know more about the GUI you're using (is it tortoise, perhaps?). I normally use this command `git rebase -i HEAD~<number>` but, as you said, it's not always user friendly (especially if there has been a merge).

I use `git fork`. You need to use `--onto` if you want to change the base branch.

**Comment by sceccotti89** [comment]
@climba03003 Thanks for the info, I'll take a look at it.
Btw, tests failed. According to logs it should not be related to my latest changes 🙄

**Comment by Uzlopak** [comment]
@climba03003 
can you please add the commits from master to next to have the latest fixes regarding node19 and tap 16.3.1 issues?

**Comment by Uzlopak** [comment]
Uff, I think this also means that all plugins, which decorate fastifyReply need changes.

**Pull request closed without merging**
