### PR TITLE
Fixed broken link Signed-off-by: Bart Kalanski <bkalanski@gmail.com>

### PR DESCRIPTION
**Pull request by bartkalanski**
Docs: link points to missing anchor #2588

Fixed broken link

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by delvedor — COMMENTED** [review]
I don't think this is the right way to fix this.
If you access the link from the markdown docs it will work as expected.
This is only breaking in the website. cc @lmammino

**Comment by mcollina** [comment]
Unfortunately that's not the correct fix as it needs to point to to the `Server.md` file. The final URL is generated with the website.

**Comment by bartkalanski** [comment]
> Unfortunately that's not the correct fix as it needs to point to to the `Server.md` file. The final URL is generated with the website.

Sorry about that, I updated the solution!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
LGTM

**Pull request merged**
