### PR TITLE
Updated Ecosystem page

### PR DESCRIPTION
**Pull request by delvedor**
- Moved from list to table, in this way is easier to read.
- Added `fastify-reply-from` plugin

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by delvedor** [comment]
@lmammino is this ok for the website?

**Comment by mcollina** [comment]
I am -1 to land this massive rewrite, the current structure is fine.
Let's not break the website.

**Comment by delvedor** [comment]
I like the plugin count, but I also prefer the table representation since is easier to read.
Have you got any suggestion on how fix this?

**Comment by mcollina** [comment]
This is _already_ conflicting, so I don't think it's the right moment for this change.
If we land this, we need to have a corresponding PR into the website to land at the same time.

**Comment by mcollina** [comment]
@delvedor are you still interested in see this landed? Should we keep this open?

**Comment by delvedor** [comment]
If we can't make this work with the website we can close it for the moment.

**Pull request closed without merging**
