### PR TITLE
ci: create artifacts in coverage workflows

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Hmm. This doesnt seem right. Before the artifacts were about 35kb. Now they are about 800 kb each.

**Comment by Fdawgs** [comment]
> Hmm. This doesnt seem right. Before the artifacts were about 35kb. Now they are about 800 kb each. 

Try lcovonly?

See https://istanbul.js.org/docs/advanced/alternative-reporters/

**Comment by Uzlopak** [comment]
Checked it again. The 35 kb artifacts are broken. If I compare with older artifacts like https://github.com/fastify/fastify/actions/runs/5216664690 then the size is also about 800 kb.

So this PR fixes that issue correct.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
