### PR TITLE
feat: add any schema type from ajv

### PR DESCRIPTION
**Pull request by ntsd**
- Add any schema type from ajv

unfortunately, it's still in TODO  from https://github.com/ajv-validator/ajv/blob/45583fde112f80c06ba6ad5583b744ef22d0640a/lib/types/index.ts#L27

otherwise, it can be `SomeJSONSchema`  from https://github.com/ajv-validator/ajv/blob/45583fde112f80c06ba6ad5583b744ef22d0640a/lib/types/json-schema.ts#L10

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
@fastify/typescript could you take a look?

**Comment by fox1t** [comment]
I think, I need more context to properly understand this PR. @ntsd would you mind updating the PR with some more information?

**Review by climba03003 — CHANGES_REQUESTED** [review]
I would say a no here, we would fall into the same issue on `fluent-json-schema`.

**Comment by ntsd** [comment]
> I would say a no here, we would fall into the same issue on `fluent-json-schema`

I am not sure the type of this, maybe need to create a new one.

**Comment by ntsd** [comment]
I am closed for now until it's clear.

**Pull request closed without merging**
