### PR TITLE
Added fastify-sentry to Community Plugins

### PR DESCRIPTION
**Pull request by alex-ppg**
Greetings everyone, 

I created this plugin that sets the error handler of `fastify` to forward errors to Sentry via their SDK and respond with a generic `500` error and `Internal Server Error` message. It also adds certain context parameters before reporting the error to Sentry, namely the `ip` and `path` of `req.raw` as a `User` context and `Tag` key-value respectively for more concise error grouping.

Once again, I recently required it for a project and thought that others might find it useful.

Thanks.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by allevo** [comment]
I don't understand the description in README
`This means that it will only work on async functions`.

why?

Maybe `only errors caught by framework will be logged. The uncaught errors are not managed`?

**Comment by alex-ppg** [comment]
@allevo According to the [Error Handling](https://github.com/fastify/fastify/blob/master/docs/Error-Handling.md) doc which references the [`fastify.setErrorHandler`](https://github.com/fastify/fastify/blob/master/docs/Server.md#seterrorhandler) doc, Fastify does not catch any errors thrown within the application apart from Promise rejections. I can re-phrase to better illustrate this though if necessary.

**Comment by mcollina** [comment]
That is not true. The error handler will be called whenever reply.send is called with an error, e.g. reply.send(err).

**Comment by alex-ppg** [comment]
@mcollina Well what I said is actually true as Fastify does not **catch** any errors thrown in synchronous functions. I was unaware that the error handler is invoked when an error is passed to `reply.send` though, I have updated the README. Thanks!

**Comment by alex-ppg** [comment]
@mcollina Fixed `test.js` to be canonical and not rely on hidden variables and also added more customization by setting a custom `errorHandler`.

**Pull request merged**
