### PR TITLE
Merge main into next

### PR DESCRIPTION
**Pull request by Eomm**
supersedes https://github.com/fastify/fastify/pull/3267

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
when landing this make sure to actually create a merge commit instead of squash.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by 3imed-jaberi — COMMENTED** [review]
lgtm

**Comment by Eomm** [comment]
Done manually

(simple merge in GH blocked)

**Pull request closed without merging**
