### PR TITLE
Add constraint strategies outside Fastify constructor

### PR DESCRIPTION
**Pull request by ivan-tymoshenko**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

The motivation of this PR was described here https://github.com/delvedor/find-my-way/issues/272 by @matthyk. The main idea is to add an option to add a custom constraint strategy outside the Fastify constructor, in order to define strategies inside plugins. There is a PR that implements this option https://github.com/delvedor/find-my-way/pull/279.

Before merging it, I want to know your opinion:
- Is it option desirable?
- Are there some trouble spots in Fastify with it?

This PR isn't ready. I didn't add tests, docs, types, etc. I want to know if this option is needed before.

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
It expose the `addConstraintStrategies` means that a plugin can add a `constraints` in this case and it may conflict between different plugins.

It should provide a method to `check` whether the `constraints` is already added.

Edit - 20220519: 
Can you move the logic inside lib/route.js and guard it with throwIfAlreadyStarted?

The main reason is that, I can see addConstraintStrategies will re-built the route, but fastify do not allow to add more route after it start.
Therefore, no route can be added to use the newly added constraints. It also means that there is no meaning to allow constraints added after it start.

**Comment by ivan-tymoshenko** [comment]
https://github.com/delvedor/find-my-way/blob/a4238bf9b8ce371a6fb3cc2b52c99ae1280a9b9d/lib/constrainer.js#L32

**Comment by climba03003** [comment]
> https://github.com/delvedor/find-my-way/blob/a4238bf9b8ce371a6fb3cc2b52c99ae1280a9b9d/lib/constrainer.js#L32

I means something `hasConstraintStrategies`, so a plugin can be
```js
if(!fastify.hasConstraintStrategies('accept')) {
  fastify.addConstraintStrategies({})
}
```

It will prevent conflict with different plugin and conflict with a single plugin.

**Comment by climba03003** [comment]
> I can add this. It's not a problem. I just don't see any sense in this check. If you want to add a new constraint strategy (with a new logic), you probably don't want to use another strategy with the same name.
> 

It make sense because `fastify` share a single router. It means that even a single plugin can register twice, with altered behavior.
The below case should fail if the `check` do not exist and it is a valid use-case of encapsulation.
```js
function auth (fastify, options, done) {
  // 
  fastify.addConstraintStrategies({})
  
  if(options.foo === 'foo') {
    // do somthing
  }
  if(options.foo === 'bar') {
    // do something else
  }
}

fastify.register(function(fastify) {
  fasitfy.register(auth, { foo: 'foo' })
})
fastify.register(function(fastify) {
  fasitfy.register(auth, { foo: 'bar' })
})
```

**Comment by ivan-tymoshenko** [comment]
According to this logic, should I check if a route already exists before inserting it?

```js
function auth (fastify, options, done) {
  if (fastify.hasRoute()) {
    fastify.get('/', schema, function (req, reply) {
      reply.send({ hello: options.foo })
    })
  }

  done()
}

fastify.register(function (fastify, option, done) {
  fastify.register(auth, { foo: 'foo' })
  done()
})
fastify.register(function (fastify, option, done) {
  fastify.register(auth, { foo: 'bar' })
  done()
})
```

**Comment by climba03003** [comment]
> According to this logic, should I check if a route already exists before inserting it?
> 

I will not block if someone check this inside their plugin.

> Let's say I created a strategy and added it with a check you suggested. Then someone can add a top-level plugin and rewrite my strategy. With that check, I even will not know about it.

As plugin provide they can ensure the `constraints` by itself through
```js
let pluginRegistered = false

function checkConstraint(consent) {
  if(consent) return false
  return pluginRegistered === false
}

module.exports = fp(async function(fastify, options) {
  // I can check if the constraint added before me
  // and allow consent to by pass the check, the user can provide a compatible constraint as their will
  if(fastify.hasConstraintStrategy('foo') && checkConstraint(options.consent)) {
    throw Error(`constraints 'foo' is not registered by me, please check if any other plugin registered it before.`)
  }
  // we change the flag as early as possible
  // it ensure we face race condition the less
  pluginRegistered = true
  if(!fastify.hasConstraintStrategy('foo')) {
    fastify.addConstraintStrategies({})
  }
})
```
I really doesn't see any harm to add the check. It provide more flexibility to the plugin creator.

**Comment by ivan-tymoshenko** [comment]
> I will not block if someone check this inside their plugin.

So why does Fastify not have a method to check if a route is already inserted if It provides higher flexibility to the plugin creator.

IMHO, something is wrong with your application if you are trying to add two constraint strategies with the same name, just like if you are trying to add two routes with the same paths.

With this option `fastify.hasConstraintStrategy('foo')`, you will know that there is a constraint strategy with the same name, but not with the same logic. 

If you need this, you can always try/catch this.

**Comment by climba03003** [comment]
> If you need this, you can always try/catch this.

`try / catch` is not a optimal one.
I would consider `addConstraintStrategies` is similar to `decorate`, `decorateReply` and `decorateRequest`.
They all provide a `has<Something>` to check whether it is added or not.
They cannot be duplicated with the same encapsulate context.

Of course `try / catch` can do the job, but it means that every plugin creator that need to add a constraint should wrap a`try / catch` which is horrible.

**Comment by ivan-tymoshenko** [comment]
I can be wrong here, but as I know, decorate will run in its own context. So that will not throw an error, and there would be two different instances of decorating value.

```js
function auth (fastify, options, done) {
  fastify.decorate('key', options.foo)

  setTimeout(() => {
    console.log(fastify.key)
  }, 3000)
  done()
}

fastify.register(function (fastify, option, done) {
  fastify.register(auth, { foo: 'foo' })
  done()
})
fastify.register(function (fastify, option, done) {
  fastify.register(auth, { foo: 'bar' })
  done()
})
```

But you always have the same instance of the router.

**Comment by ivan-tymoshenko** [comment]
With `hasConstraintStrategy` you can create a situation when your strategy will override by another plugin and you wouldn't notice that.

How would you separate the case when it's the same strategy defined the second time or this is another strategy with the same name?

**Comment by climba03003** [comment]
Suggestion back to the code added inside this PR.

Can you move the logic inside `lib/route.js` and guard it with `throwIfAlreadyStarted`?

The main reason is that, I can see `addConstraintStrategies` will re-built the route, but `fastify` do not allow to add more route after it start.
There, no route can be added to use the newly added `constraints`. It also means that there is no meaning to allow `constraints` added after it start.

**Comment by climba03003** [comment]
> > It provide the other logic that is not the same inside each encapsulate context.
> 
> Since you have only one router instance, the logic will be the same for all contexts. There is no encapsulation in this case. If I correctly understand what you mean.

No, a plugin is not restricted to `route` or `constraints` only. 
The other logic means something apart form the `constraints`.

For example, a shared constraints of `permission`.
Different `helper` function added in `FastifyInstance`.

**Comment by ivan-tymoshenko** [comment]
Ok, I will add this option, but I still think that there is something wrong with your application if you register a plugin, that adds a new constraint strategy, twice.

**Comment by climba03003** [comment]
> Ok, I will add this option, but I still think that there is something wrong with your application if you register a plugin, that adds a new constraint strategy, twice.

I do not say it has nothing wrong if the same constraint registered twice.
But, the `check` function allow the plugin to determine if the `constraint` is usable for itself.
They have more choice in this case.

For example,
It is known that plugin A and plugin B can share the same `constrants` logic.
They check the compatibility with `Symbol.for('hello-world')`
In here, the outcome should be the same and I would prefer to do the latter.

```js
// without check function
const sym = Symbol.for('hello-world')
async function A (fastify, options) {
  // it seems like the plugin will always fall into error
  try {
    fastify.addConstraintStrategies({})
  } catch(err) {
    // we safely ignore error in this case
    // because we know we are compatible
    if(!fastify.hasDecorator(sym)) throw err
  }
  fastify.decorate(Symbol.for('hello-world'), true)
}

// with check
async function A (fastify, options) {
  // better readibiltity
  if (fastify.hasConstraintStrategy('foo') && !fastify.hasDecorator(sym)) {
    throw Error('non-compatible constraints found, please make sure constraints "foo" is not registered twice.')
  } else if(!fastify.hasConstraintStrategy('foo')) {
    fastify.addConstraintStrategies({})
  }
  fastify.decorate(Symbol.for('hello-world'), true)
}
```

**Comment by ivan-tymoshenko** [comment]
Why can't you create a plugin that registers a custom constraint strategy and then register any custom logic that you need?
```js
fastify.register(function (fastify, option, done) {
  fastify.register(/* Register constraint strategy */)
  fastify.register(/* Register A */)
  fastify.register(/* Register B */)
  ...
  done()
})
```

**Comment by climba03003** [comment]
> Why can't you create a plugin that registers a custom constraint strategy and then register any custom logic that you need?
> 
> ```js
> fastify.register(function (fastify, option, done) {
>   fastify.register(/* Register constraint strategy */)
>   fastify.register(/* Register A */)
>   fastify.register(/* Register B */)
>   ...
>   done()
> })
> ```

Plugin is not always added by you. Here I mention is added by third-party plugin.
You cannot control others code. But sometimes, they may compatible with each another.
People have more solution in this way.

**Comment by ivan-tymoshenko** [comment]
We have two default constraint strategies: `version` and `host.` You can redefine them until you register the first route that uses one of these constraints. We check this in the find-my-way. So how should `hasConstraintStrategy` work according to that?

If it always returns true for `version` and `host` constraints, you will not know can you redefine them or not.

https://github.com/delvedor/find-my-way/blob/62185a32cd383147e853ace699497d61f6886d0e/lib/constrainer.js#L38

**Comment by climba03003** [comment]
> We check this in the find-my-way. So how should hasConstraintStrategy work according to that?

```js
hasConstraintStrategy(key) {
  return this.hasCustomConstraintStrategy(key) || this.strategiesInUse.has(key)
}
```
Does it not enough for the check?

You cannot registered the `version` or `host` if it used in one route.
It should return `true`.
`plugin` check it does not `registered` before, then it can throw.

If it registered by the `plugin`, it should return `true`.
`plugin` check it does `registered` before, then it do not throw.

I don't see any problem here.

**Comment by ivan-tymoshenko** [comment]
Yes, it will work. It's just not `hasConstraintStrategy` anymore. `hasConstraintStrategy` should always return true for `version` or `host` constreints.  Any suggestions on how we should name this method?

**Comment by climba03003** [comment]
> Yes, it will work. It's just not `hasConstraintStrategy` anymore. `hasConstraintStrategy` should always return true for `version` or `host` constraints. Any suggestions on how we should name this method?

To keep thing simple, I think it is acceptable to use `hasConstraintStrategy`.
`version` and `host` is a special case, so we need to use `strategiesInUse` for checking.

But, if you need a exact name reflect the action.
It can be `isConstraintStrategyAllow` ? I am not good at naming though.

**Review by climba03003 — APPROVED** [review]
LGTM. Once `find-my-way` released this feature.

Thanks for continuing improve how `find-my-way` works. Appreciate

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
