### PR TITLE
Mergeable context config type

### PR DESCRIPTION
**Pull request by wyozi**
I noticed that the route shorthand options `config` is typed on a per-route basis. This means that for instance `fastify-rate-limit` route options are not typed at all. If the config option is extracted as a separate interface, it can be merged into from plugins and dependencies adding more type safety. Does this approach seem viable?

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
cc @fastify/typescript wdyt?

I think we lost this one

**Comment by RafaelGSS** [comment]
To be honest, I didn't understand what's the issue exactly.

**Review by climba03003 — APPROVED** [review]
LGTM.
I think it is a worth PR to improve TypeScript and Plugin DX.
@fastify/typescript Can anyone take a look on it again with my explanation of previous comment?

**Review by RafaelGSS — APPROVED** [review]
I see the address issue. LGTM.

**Pull request merged**
