### PR TITLE
feat: Improve RouteShorthandOptions['constraints'] type

### PR DESCRIPTION
**Pull request by Fcmam5**
As mentioned in the [the documentation](https://fastify.dev/docs/latest/Reference/Routes/#constraints), routes may have [`version`](https://fastify.dev/docs/latest/Reference/Routes/#version-constraints), [`host`](https://fastify.dev/docs/latest/Reference/Routes/#host-constraints) or other custom constraints. This change only extends `RouteShorthandOptions` type with optional `version` and `host` attributes.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fcmam5** [comment]
@mcollina can you check again? seems that the pipelines are pending after I changed my PR title 😬

**Comment by Uzlopak** [comment]
Shouldnt be host and version being string?

**Comment by mcollina** [comment]
This actually needs a test, we use tsd for types

**Comment by Fcmam5** [comment]
@mcollina, @Uzlopak can you check again?

I used the following example to test it locally:

```ts

const fastify: FastifyInstance = Fastify({});

function databaseOperation(field, done) {
  done(null, field);
}

fastify.route({
  method: 'GET',
  url: '/',
  constraints: {
    version: '1.2.3',
    host: 'admin.dz',
    secret: {
      name: 'secret',
      storage: function () {
        let handlers = {};
        return {
          get: (type) => {
            return handlers[type] || null;
          },
          set: (type, store) => {
            handlers[type] = store;
          },
        };
      },
      deriveConstraint: (req, ctx, done) => {
        databaseOperation(req.headers['secret'], done);
      },
      mustMatchWhenDerived: true,
    },
  },
  handler: function (request, reply) {
    reply.send({ hello: 'world' });
  },
});
```

I played with the values/types to see if it still working as expected:

- version:
  - string
  - RouteConstraint

- Host:
  - string
  - RegEx
  - RouteConstraint

And custom constraints must have `RouteConstraint`

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by climba03003** [comment]
I am a bit late here because just notice an error after this landing on `4.25.0`.
`constraints` should accept `any` or `unknown` types instead of  `RouteConstraintType`.
`RouteConstraintType` is used when passing `fastify.addConstraintStrategy`.

**Pull request merged**
