### PR TITLE
fix: allow async hooks in `RouteShorthandOptions` without breaking `request` and `reply` types

### LINKED ISSUE #4859: Support `RouteShorthandOptions` to receive async hooks
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently, `RouteShorthandOptions` type doesn't allow passing async hooks:

```ts
export interface RouteShorthandOptions<
  // ...
> {
  // ...
  onRequest?: onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[];
```

It should be something like that:

```ts
export interface RouteShorthandOptions<
  // ...
> {
  // ...
  onRequest?: onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[]
  // Add these two:
  | onRequestAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>
  | onRequestAsyncHookHandler<RawServer, RawRequest, RawReply, RouteGeneric, ContextConfig, SchemaCompiler, TypeProvider, Logger>[];
```

### PR DESCRIPTION
**Pull request by bienzaaron**
Closes #4859, without breaking `RouteShorthandOptions` in the same way #4655 did (see #4705 for details on that).

The idea is to use an intermediate type to infer the return type of the hook, and determine which hook handler interface to use based on that (sync or async).

A couple things I wanted to call out:
- this new meta hook type is intentionally not exported from the main `fastify.d.ts` file. It's really just an internal helper and shouldn't need to be exported.
- Not a huge fan of the `meta` name - suggestions welcome. I think it would make the most sense to rename the existing hooks `sync` and `async` and then just make the new type `<hook name>HookHandler` (what the sync hook currently is named), but that would be breaking.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
Attn: @fastify/typescript

**Comment by SlyryD** [comment]
Very nice!

**Review by SlyryD — APPROVED** [review]
Looks good!

**Review by Uzlopak — DISMISSED** [review]
Imho not strict enough.

E.g. mixing async and callback is possible.

```ts
  onRequest: async (request, reply, done) => {
    expectType<FastifyRequest>(request)
    expectType<FastifyReply>(reply)
  },
```

It should be investigated if it can be done like in #4945

**Comment by fox1t** [comment]
@Uzlopak good catch!

**Comment by SlyryD** [comment]
> @Uzlopak good catch!

Following this change... any updates?

**Comment by Uzlopak** [comment]
@eomm

The code did not change since my last review. Maybe if I have time tonight I can patch it to my liking, then you can review it.

**Comment by Uzlopak** [comment]
I modified the typings tests to demonstrate the issue ;)

**Review by SlyryD — APPROVED** [review]
Looks good!

**Comment by Uzlopak** [comment]
I removed the most obvious errors. but i couldnt implement the requested change by myself. So I think we should review and merge it as is.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@Uzlopak could you lgtm this?

**Comment by Uzlopak** [comment]
@mcollina i dismissed my review because i modified this PR heavily

**Pull request merged**
