### PR TITLE
Feature/consistent docs formatting

### PR DESCRIPTION
**Pull request by StarpTech**
This PR will use https://github.com/prettier/prettier for markdown files only. It will format markdown and code snippets in a consistent way. The downside: It' not 100% standardjs compliant. It removes the space between function parentheses but I still like it because it's only for docs examples.

Just run

```
npm run format-docs
```

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I do not see the reason for this. But maybe I'm missing some details.

Can you please configure prettier to have the example conform to standardjs?

**Comment by StarpTech** [comment]
The reason is that we don't have to care about how a user formats or which markdown style he will use.

> Can you please configure prettier to have the example conform to standardjs?

This is not easy, because prettier doesn't provide it out of the box.

**Comment by StarpTech** [comment]
We are talking about docs examples and a space between function parentheses. The benefit of consistent docs is greater in my opinion.

**Comment by nwoltman** [comment]
Could [`prettier-standard`](https://github.com/sheerun/prettier-standard) be used instead?

**Comment by mcollina** [comment]
I don't think this is a great idea unless we also apply this to the rest of the code.

I'm generically -1 on adding prettier to the already big list of devDependencies.

**Comment by StarpTech** [comment]
@nwoltman I evaluated it but it doesn't respect standard style in markdown code.

**Pull request closed without merging**
