### PR TITLE
fix(type): add missing `hostname` field to `Request`

### PR DESCRIPTION
**Pull request by SimenB**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

Documented here: https://github.com/fastify/fastify/blob/667d4644eab09f27bc30cad6e7378f5fc82cb9e8/docs/Request.md

### CODE REVIEW

**Comment by mcollina** [comment]
It needs a test :)

**Comment by SimenB** [comment]
@mcollina sure! Which file should I add it to? I don't see any assertions for request types

**Comment by mcollina** [comment]
https://github.com/fastify/fastify/blob/master/test/types/route.test-d.ts should do

**Comment by SimenB** [comment]
Wait, this is better covered by #2299, no? I just made a quick change on GH without searching through other issues/PRs

**Comment by mcollina** [comment]
Yes, closing this then

**Pull request closed without merging**
