### PR TITLE
docs(ecosystem): replace fastify-apollo with fastify-graphql

### PR DESCRIPTION
**Pull request by SimenB**
fastify-apollo has been archived, fastify-graphql is a maintained fork

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
How much of this differs from https://github.com/fastify/fastify/pull/1126 cc @dtex

**Comment by SimenB** [comment]
Ah, I didn't notice that one! I haven't actually used it yet, I was just looking into replacing express with fastify now, and we need graphql to work. Some googling ended up with this PR, but I don't have any context beyond that 🙂

**Comment by dtex** [comment]
It's all very confusing. 

@SimenB's PR is more current than what is up there now and my PR refers to a future state. I haven't tested of course, but I would think that @SimenB's PR (with an additional note regarding which apollo-server versions are supported) is the way to go.

Backstory: That PR (apollographql/apollo-server#1013) was merged into apollo-server 1.4 but was not part of the 2.0 release. I'm not sure when it's going to happen but @addityasingh says they are working on 2.0 support. I imagine that will be the favored option when it lands, since it will be a package in the fastify mono-repo.

@sirsavary Has your fork been updated to work with 2.0? Have you pinged @addityasingh for an update on their work? Maybe y'all could collaborate?

@nfishe Would appreciate any guidance you can offer on all this.

**Comment by codejie** [comment]
maybe try to [fastify-apollo-step](https://www.npmjs.com/package/fastify-apollo-step)~

**Comment by addityasingh** [comment]
Apologies guys for the delay. I have finally created a [WIP PR](https://github.com/apollographql/apollo-server/pull/1760/files) for integrating with V2 of apollo. Currently some tests are failing and I am trying to figure them out. Feel free to add your comments/suggestions/

**Comment by delvedor** [comment]
What's the status on this?

**Pull request closed without merging**
