### PR TITLE
Improve Getting-Started docs regarding fastify-plugin

### LINKED ISSUE #700: document that for decorators to work across plugins you have to use fastify-plugin
ref: https://github.com/fastify/fastify/pull/699 (and others)

### PR DESCRIPTION
**Pull request by nwoltman**
Fixes #700

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nwoltman** [comment]
Yes, it doesn't skip encapsulation all the way back to the root, it's just for the current level. It's hard to explain that concisely though. Any suggestions on a better way to phrase it?

**Comment by jsumners** [comment]
I have no idea.

**Comment by delvedor** [comment]
> Yes, it doesn't skip encapsulation all the way back to the root, it's just for the current level. It's hard to explain that concisely though. Any suggestions on a better way to phrase it?

How about "exposes the decorators, hooks and middlewares declared inside the plugin in the parent scope"?

**Comment by nwoltman** [comment]
Okay I think it should be good now. Good suggestion @delvedor!

**Pull request merged**
