### PR TITLE
doc: add Zekth as contributor

### PR DESCRIPTION
**Pull request by zekth**
As i'm now a contributor, just edited the Readme :)

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Also https://github.com/fastify/fastify/blob/master/package.json#L99

**Review by mcollina — APPROVED** [review]
LGTM, welcome!

**Review by jsumners — APPROVED** [review]
LGTM

**Comment by jsumners** [comment]
Does anyone know why this is happening? 
image

**Comment by mcollina** [comment]
no idea

**Comment by zekth** [comment]
> Does anyone know why this is happening?
> image

i brought the eslint back in https://github.com/fastify/fastify/pull/2536
I'll improve it

**Review by RafaelGSS — APPROVED** [review]
Welcome!

**Comment by Ethan-Arrowood** [comment]
Yeah lets disable that warning; any is used intentionally in our type definitions and I don't want it to clutter the CI.

Also welcome 😉 🙌

**Comment by zekth** [comment]
> Yeah lets disable that warning; any is used intentionally in our type definitions and I don't want it to clutter the CI.
> 
> Also welcome 😉 🙌

=> https://github.com/fastify/fastify/pull/2548

**Pull request merged**
