### PR TITLE
Update Ecosystem.md

### PR DESCRIPTION
**Pull request by tswayne**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi, @tswayne I reviewed your plugin.

**Comment by jsumners** [comment]
@delvedor have you had a chance to review this plugin for ecosystem inclusion?

**Comment by delvedor** [comment]
@jsumners as far as I know @StarpTech was reviewing the plugin, which is still missing unit tests.

**Comment by tswayne** [comment]
Sorry for the late reply, I’m actively working on the tests.  They’ll be done in a few days.

**Pull request merged**
