### PR TITLE
fix: fastify plugin types exports

### PR DESCRIPTION
**Pull request by lundibundi**
These were accidentally removed in https://github.com/fastify/fastify/pull/2554

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Also adds tests to make sure these Types are exported.

### CODE REVIEW

**Review by L2jLiga — APPROVED** [review]
LGTM!

**Comment by fox1t** [comment]
Oh! So sad no one caught this before the merge. I suppose we need ts test instead of tsd (again).

**Review by fox1t — APPROVED** [review]
LGTM

**Comment by lundibundi** [comment]
I think this test is okay, the issue is that it (the fact that these properties are exported from `fastify` itself and not just from `plugin.ts`) was not tested at all before.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Does this needs to be shipped asap in v3.4.1?

**Comment by fox1t** [comment]
Yes!

**Comment by L2jLiga** [comment]
Yes!

**Comment by RafaelGSS** [comment]
@fox1t this is related to https://github.com/fastify/fastify-plugin/pull/106?

**Comment by fox1t** [comment]
@RafaelGSS no. Here we are fixing the fastify-plugin types that are exported by fastify itself. On that PR we had a missing default export: basically fastify-plugin wasn't working in "faux ESM" context (TS, webpack, and so on).

**Comment by mcollina** [comment]
shipped in v3.4.1.

**Pull request merged**
