### PR TITLE
ci: enable caching; split jobs

### PR DESCRIPTION
**Pull request by Uzlopak**
Using now caching by setup-node, which is ensuring, that we cache properly. E.g. currently caching on windows machines was not happening, because the npm cache is not on ~/npm on windows. 

Split some jobs like linter and typescript tests, as they only need to run once and it is enough that they run on lts of node. 

automerge is running after package tests succeeded.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Review by Fdawgs — APPROVED** [review]

**Comment by Fdawgs** [comment]
Will roll this into the shared workflows @Uzlopak, had been using it in my own repos that have package-locks but didn't know you could point this at the package.json!

**Comment by Uzlopak** [comment]
Maybe we should also think about ways to evict caches. 

We could e.g. pin versions of dependencies and/or devdependencies in package.json, so that dependabot changes triggers package.json changes. 

Or see
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

The quoted workflow is actually very interesting, as it deletes the caches of a branch after merging the pr. Maybe makes sense to apply it.

We could write a reusable workflow based on the above workflow which also can be triggered on workflow_dispatch to manually trigger it.
We could schedule also a workflow to delete the cache of main e.g. every 3 days.

**Review by metcoder95 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
