### PR TITLE
Add Promise to 404 handler return type

### PR DESCRIPTION
**Pull request by omothm**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Could you please target `main` and not v3.x. In case we'll backpoort the fix (or ask for a backport PR).

**Comment by omothm** [comment]
> Could you please target `main` and not v3.x. In case we'll backpoort the fix (or ask for a backport PR).

@mcollina Sure. Should I close this PR and open a new one?

**Comment by mcollina** [comment]
You might just try to change the base.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by omothm** [comment]
Does this require any further action on my side to be considered for merging?

**Comment by mcollina** [comment]
CI is failing

**Comment by omothm** [comment]
I have merged upstream into the PR. I believe this might fix the CI failure. Could you please approve the awaiting workflow?

**Review by Eomm — APPROVED** [review]

**Comment by omothm** [comment]
@mcollina Thanks for the merge! I see there was an issue with backporting. Should I carry out the mentioned steps and start another PR for the backport?

**Pull request merged**
