### PR TITLE
Add missing type

### LINKED ISSUE #2358: Error: Property 'setReplySerializer' does not exist on type 'FastifyInstance'
## 🐛 Bug Report

I'm trying to use setReplySerializer() in my Fastify-powered TypeScript project. However, an error is thrown:

`error TS2339: Property 'setReplySerializer' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.`

## To Reproduce

```js
import * as Fastify from 'fastify';

(async () => {
  try {
    const server = Fastify.fastify();

    // Based upon https://www.fastify.io/docs/master/Server/#setreplyserializer
    server.setReplySerializer(function (payload: any, statusCode: any) {
      return `my serialized ${statusCode} content: ${payload}`;
    });

    await server.listen(3000, '0.0.0.0');
  } catch (err) {
    console.error(err);
  }
})();

```

## Expected behavior

No TypeScript error

## Your Environment

- *Node version*: 12
- *Fastify version*: 3.0.0-rc.4
- *TypeScript version*: 3.9.5
- *os*: Linux

### PR DESCRIPTION
**Pull request by chasingSublimity**
Fixes #2358 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by chasingSublimity** [comment]
Hey @Ethan-Arrowood! As mentioned in #2358, I could use a bit of guidance with the tests here. I imagine that a test needs to be added to `instance.test-d.ts`. I'm not quite sure what that test should entail, however. Maybe adding a check that verifies `setReplySerializer` is a valid instance method? 

Thanks!

**Comment by Ethan-Arrowood** [comment]
@chasingSublimity you can use the setErrorHandler types as a template. For your test. And yes that is the correct file.

**Comment by chasingSublimity** [comment]
@mcollina @Ethan-Arrowood I added a few type tests. Let me know if any further changes are needed! 🚀

**Comment by chasingSublimity** [comment]
thanks for the help!

**Pull request merged**
