### PR TITLE
test: improve coverage

### PR DESCRIPTION
**Pull request by simone-sanfratello**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you please add a config in `.taprc` to enforce 100% of lines?

**Comment by simone-sanfratello** [comment]
can't set threshold to 100, still missing something on node 10 and 12

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Happy to ignore lines that are version specific.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
