### PR TITLE
Fix inaccurate type of `setErrorHandler`

### PR DESCRIPTION
**Pull request by chengluyu**
See #2091

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
This should not be `any`. I'd rather you make this `unknown` and instruct the user to use type casting to enforce what they want to come through this handler. Based on the code you provided in your issue, `throw {hello: 'world'}` will result in a type of `{ hello: string }`. If you captured that in a type i.e. `type CustomError = { hello: string }`, then the goal would be to use use that type in `setErrorHandler`. You can achieve this through generics or type casting. I'd suggest supporting both by using a default generic, so something like this:

```ts
setErrorHandler<E = FastifyError>(error: E, ...)
```

**Comment by chengluyu** [comment]
> This should not be `any`. I'd rather you make this `unknown` and instruct the user to use type casting to enforce what they want to come through this handler. Based on the code you provided in your issue, `throw {hello: 'world'}` will result in a type of `{ hello: string }`. If you captured that in a type i.e. `type CustomError = { hello: string }`, then the goal would be to use use that type in `setErrorHandler`. You can achieve this through generics or type casting. I'd suggest supporting both by using a default generic, so something like this:
> 
> ```ts
> setErrorHandler<E = FastifyError>(error: E, ...)
> ```

I agree with you. I've replace `any` with generic type parameter (defaults to `FastifyError`). Therefore, users can specify their own error types.

**Comment by mcollina** [comment]
Can you add a test for the type change?

**Comment by chengluyu** [comment]
> Can you add a test for the type change?

Hi, I've added a test. Please let me know if there's any problem. 😄

**Pull request merged**
