### PR TITLE
WIP: fix: windows flakiness

### PR DESCRIPTION
**Pull request by zekth**
This aimes to fix flakiness on windows noticed by @jsumners .

Not sure if it's the best implementation. Let's make several runs of CI to see if it passes.

edit: DO NOT MERGE.

### CODE REVIEW

**Comment by RafaelGSS** [comment]
I would re-run these tests (on ci) at least 3 times before land

**Review by mcollina — COMMENTED** [review]
lgtm

**Comment by zekth** [comment]
7 clean run so far

**Comment by zekth** [comment]
Ok no it doesn't fix it.

**Comment by zekth** [comment]
Seems like switching to `undici` makes it more resilient

**Review by Eomm — APPROVED** [review]

**Pull request merged**
