### PR TITLE
chore: add autocannon and concurrently as dev dependencies

### PR DESCRIPTION
**Pull request by Uzlopak**
Remove branch-comparer as it can be used via npx like we already with autocannon and concurrently.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
it's better to have them all installed as devDep

**Comment by jsumners** [comment]
I think `npx` was one of the poorest decisions in the history of npm. If a project requires a package, add it to the project. It shouldn't be pulled down through a mysterious runner tool every time it is needed.

**Comment by Uzlopak** [comment]
@mcollina 
@jsumners 

Ok, then the other way round. add missing autocannon and concurrently as dev dependencies.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
