### PR TITLE
add sync-next workflow

### PR DESCRIPTION
**Pull request by Uzlopak**
as discussed here a proposal for a workflow to sync the next branch with main regularly.

I tested it in my github user scope.
see 
https://github.com/Uzlopak/test-auto-sync
and successful run 
https://github.com/Uzlopak/test-auto-sync/actions/runs/5214380428

I needed to activate "Allow GitHub Actions to create and approve pull requests", but I guess this is already active in this repo.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Fdawgs — APPROVED** [review]
👍🏻

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]
Can it run in every other week? 
I believe we do not have such a bandwidth to check and resolve conflict in every week.

We can land it now, but want to know if it able to de-duplicate the same PR if we really not have time to handle it.

**Comment by Uzlopak** [comment]
Chronjob for every other week seems to be not easy https://stackoverflow.com/questions/350047/how-to-instruct-cron-to-execute-a-job-every-second-week

But we could everytime comment out the scheduling and as it has workflow_dispatch, we can run it manually, if necessary.

**Pull request merged**
