### PR TITLE
docs: update v4 codemods

### PR DESCRIPTION
**Pull request by mohab-sameh**
- Added links to provide extra context for codemods
- Switched existing links to Dub links to avoid potential 404s in the future
- Minor wording adjustments

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mohab-sameh** [comment]
@climba03003 @mcollina Minor adjustments to migration guide codemods section.

**Review by gurgunday — APPROVED** [review]
lgtm

**Comment by gurgunday** [comment]
Markdown lint is failing

**Comment by mohab-sameh** [comment]
@gurgunday should be fixed now.

**Review by gurgunday — APPROVED** [review]

**Pull request merged**
