### PR TITLE
Add me to the contributors and plugins teams

### PR DESCRIPTION
**Pull request by airhorns**
🥳 Let me know if this is amiss!

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
Welcome!

**Review by jsumners — APPROVED** [review]
image

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Ethan-Arrowood — APPROVED** [review]
Welcome in 🙌

**Review by delvedor — APPROVED** [review]
Welcome!

**Pull request merged**
