### PR TITLE
chore: bump fast-json-stringify-compiler to v5.0.0

### PR DESCRIPTION
**Pull request by mcollina**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
whut?

```
  test/types/instance.test-d.ts:374:2
  ✖  373:0  Found an error that tsd does not currently support (ts2719), consider creating an issue on GitHub.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  ✖  374:2  Type (this: import("/home/runner/work/fastify/fastify/types/instance").FastifyInstance<import("http").Server<typeof import("http").IncomingMessage, { new (req: import("http").IncomingMessage): import("http").ServerResponse<import("http").IncomingMessage>; prototype: import("http").ServerResponse<any>; ... 29 more ...; Ev... is not assignable to type (this: import("/home/runner/work/fastify/fastify/types/instance").FastifyInstance<import("http").Server<typeof import("http").IncomingMessage, { new (req: import("http").IncomingMessage): import("http").ServerResponse<import("http").IncomingMessage>; prototype: import("http").ServerResponse<any>; ... 29 more ...; Ev.... Two different types with this name exist, but they are unrelated.
  Type boolean is not assignable to type string.  
```

**Review by jsumners — APPROVED** [review]

**Comment by mcollina** [comment]
@Eomm I'm investigating. It happens also on main right now.

**Comment by mcollina** [comment]
I have absolutely no clue why this is happening now. Anyway, here is a PR to tsd to fix it: https://github.com/tsdjs/tsd/pull/220.

In the meanwhile I've pointed fastify to my fork.

@Eomm @jsumners are you still ok to land this? Otherwise I can just commend out those two assertions.

**Review by Eomm — APPROVED** [review]
👍🏼

**Pull request merged**
