### PR TITLE
add node 17

### PR DESCRIPTION
**Pull request by Eomm**
superseded #3381 

Closes #3456

### CODE REVIEW

**Comment by Eomm** [comment]
The error on node17

```
2021-11-17T17:09:51.8868816Z             -http://127.0.0.1:39829
2021-11-17T17:09:51.8869340Z             +http://[::1]:39829
```

Cannot find any breaking change that should impact the server IP listening interface

https://nodejs.org/en/blog/release/v17.0.0/

🤔

**Comment by darkgl0w** [comment]
Was searching for the same changes and stumbled upon this issue: https://github.com/nodejs/node/issues/40537

Seems like there is the `--dns-result-order` command line option that needs to be set in order to control the new behaviour.

**Review by mcollina — CHANGES_REQUESTED** [review]
This will need test fixes

**Comment by mcollina** [comment]
This should be good to land now, tests pass locally. Let's double check it.

**Comment by mcollina** [comment]
cc @targos this the the PR I was talking about.

**Comment by darkgl0w** [comment]
This PR should close https://github.com/fastify/fastify/issues/3428 too

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
