### PR TITLE
fix(2711): expose instance.errorHandler in types

### PR DESCRIPTION
**Pull request by salmanm**
Fixes https://github.com/fastify/fastify/issues/2711

_Please check the update carefully as I'm not so good at writing types_ 😅 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
This needs a test

**Review by fox1t — COMMENTED** [review]
We surely need tests here but I want to wait for a repro repository because of this https://github.com/fastify/fastify/issues/2711#issuecomment-734737949

**Comment by salmanm** [comment]
I'll push tests in sometime.

@fox1t `errorHandler` is exposed in `route.d.ts` but we recently added `fastify.errorHandler` which I confirm isn't exposed in types.

**Comment by fox1t** [comment]
Ok then we should use https://github.com/fastify/fastify/blob/de94d314e940fba2c7021b0e180445a814d4d068/types/route.d.ts#L31 also in https://github.com/fastify/fastify/pull/2712/files#diff-f86d0644c15a00c507413e99f283c1f856275409929539a74b8196a42da25018R318 
Would you mind to add this improvement and also add tests?

**Comment by salmanm** [comment]
Updated the PR with test. Pls guide if you find my typescript terrible.

**Comment by salmanm** [comment]
image

I hope the build isn't failing due to any change in this PR! Tried re-building.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by fox1t** [comment]
The implementation looks good to me, but I don't see any new tests? 🤔

**Review by fox1t — APPROVED** [review]
LGTM

**Pull request merged**
