### PR TITLE
add french documentation

### PR DESCRIPTION
**Pull request by MustaphaHAMADI**
French translation of the Fastify documentation 
Main topics are translated the rest will be in a few weeks

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
Hi @MustaphaHAMADI. We really appreciate the effort you are putting into translating all the docs to French! 

Unfortunately, right now the Fastify repo only provides `docs` in English. So does the website. Like @RafaelGSS  It becomes hard over time to maintain the documentation in different languages and requires a lot of commitment to keep them in sync with future versions.

Maybe we can set a separate repo for this? 🤔

**Comment by MustaphaHAMADI** [comment]
Hi yes I understand, my main idea was to create a separate repo for the french docs. I new to open source contribution so I don't know who to do it. I will assure the maintainability of the separate repo with a friend.

**Comment by jsumners** [comment]
https://github.com/fastify/docs-portuguese exists. And you can see how well maintained it is. I am sorry that you spent so much effort on this already @MustaphaHAMADI, but I think we need much more robust i18n support before we can actually support multiple languages in the documentation.

In particular, it's a bad time to try and write translations because the docs are undergoing a (slow) re-write.

**Comment by MustaphaHAMADI** [comment]
Thanks for your advices

**Comment by Eomm** [comment]
We have the Chinese version as well: https://github.com/fastify/docs-chinese

I would move your work into a repository of yours to keep it and share it

**Pull request closed without merging**
