### PR TITLE
ContentTypeParser remove(): Return false when content type parser was not present for removal

### PR DESCRIPTION
**Pull request by kamilogorek**
It's not clear whether this behavior is desired for the current version, but threw together a quick PR in case it is.

Closes https://github.com/fastify/fastify/issues/4482

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
I am still against to throw for removal.
But, I am fine to return a `boolean` to indicate the result. Just same as `Map`.

**Comment by mcollina** [comment]
better to return false for failure and true in the case of success

**Comment by kamilogorek** [comment]
Sounds good to me. Updated

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you update the PR title?

**Review by Uzlopak — APPROVED** [review]

**Review by Fdawgs — APPROVED** [review]

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
