### PR TITLE
Add fastify-favicon to community plugins list (#806)

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)
----
To ensure it really works (other than usual tests and example) I just used it in a sample webapp: [fastify-example](https://github.com/smartiniOnGitHub/fastify-example)

### CODE REVIEW

**Comment by allevo** [comment]
Hi!

thank you!

Can you move this line to the top scope?

https://github.com/smartiniOnGitHub/fastify-favicon/blob/7d08d34613233941f585a566786178df37f4dc1e/plugin.js#L21-L23

The path can be calculated one time instead of each request

Anyway I don't know which licence is applied to the logo. @mcollina ?

**Comment by smartiniOnGitHub** [comment]
Hi @allevo , yes sure ... thanks for the hint :-) . I'll do today (and publish a new 0.1.2 plugin release in npmjs).

**Comment by jsumners** [comment]
@allevo https://github.com/smartiniOnGitHub/fastify-favicon/blob/7d08d34613233941f585a566786178df37f4dc1e/LICENSE#L205-L235

**Comment by smartiniOnGitHub** [comment]
@jsumners  Hi, is there some problem with (original) favicon file (its license) put there ?

**Comment by jsumners** [comment]
@smartiniOnGitHub no, I was answering @allevo's question.

**Comment by smartiniOnGitHub** [comment]
Ah ok, thanks ... for sure I don't want problems with licensing :-) ...

**Comment by smartiniOnGitHub** [comment]
ok, proposed changes done in the plugin [fastify-favicon](https://github.com/smartiniOnGitHub/fastify-example) and in its real usage test [fastify-example](https://github.com/smartiniOnGitHub/fastify-example) , and uploaded in npmjs at [fastify-favicon - npmjs](https://www.npmjs.com/package/fastify-favicon) .
Thanks a lot for the review and all suggestions :-) . Bye

**Comment by smartiniOnGitHub** [comment]
Hi all, any news on tis ? Thanks :-)

**Pull request merged**
