### PR TITLE
ci: fix broken ci by skipping tests if node v > 18.19.0

### PR DESCRIPTION
**Pull request by Uzlopak**
I guess in 18.19.0 the PR which has something to do with closeIdleConnections got backported and thus breaking our CI. 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
I think there is something broken in 18.19.0. I have been trying to determine a problem at work around this. The only difference is the runtime changing from 18.18.2 to 18.19.0:

+ https://github.com/newrelic/node-newrelic/actions/runs/7139368895/job/19442594855
+ https://github.com/newrelic/node-newrelic/actions/runs/7143082288/job/19453786267

I'd rather we pin to 18.18.2 until we can determine the issue and hopefully get an 18.19.1. That, or make the exclusion check for `=== 18.19.0`.

**Comment by jsumners** [comment]
FYI: this has shown up in today's CI because of https://github.com/actions/runner-images/commit/e11b8781168918b6fe9990f434b2adb2b4bf7abd

**Comment by Uzlopak** [comment]
Can you please take this task over? I will not at my PC for the next few hours.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
