### PR TITLE
docs(Plugins): removed prefix from list with fastify-plugin

### PR DESCRIPTION
**Pull request by RafaelGSS**
reference: #1818 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by RafaelGSS** [comment]
> The currently supported list of Fastify specific options is:

That shows what options work with `fastify-plugin`. So, if both not work, we should write **An note bold**.  right?

**Comment by mcollina** [comment]
Change it to:

```
The optional `options` parameter for `fastify.register` supports a predefined set of options that Fastify itself will use. This options object will also be passed to the plugin upon invocation, regardless of whether or not the plugin has been wrapped. The currently supported list of Fastify specific options is:

+ [`logLevel`](https://github.com/fastify/fastify/blob/master/docs/Routes.md#custom-log-level)
+ [`prefix`](https://github.com/fastify/fastify/blob/master/docs/Plugins.md#route-prefixing-options)

Those options will be ignored when used with fastify-plugin.
```

Or something similar.

**Comment by Eomm** [comment]
Do we have a test for this?

**Comment by RafaelGSS** [comment]
> Do we have a test for this?

The tests with `skip-override` do not cover it?

**Comment by Eomm** [comment]
> > Do we have a test for this?
> 
> The tests with `skip-override` do not cover it?

I don't think so, a test like this one is missing:

```
test('plugin metadata - ignore prefix', t => {
  t.plan(1)
  const fastify = Fastify()

  plugin[Symbol.for('skip-override')] = true
  fastify.register(plugin, { prefix: 'foo' })

  fastify.inject({
    method: 'GET',
    url: '/'
  }, (err, res) => {
    t.error(err)
    t.equals(res.payload, 'hello')
  })

  function plugin (instance, opts, next) {
    instance.get('/', async () => 'hello')
    next()
  }
})
```

**Comment by RafaelGSS** [comment]
@Eomm what file do you think that is better insert it? `plugin.test.js`

sorry for the delay, damn new software xD

**Comment by Eomm** [comment]
> what file do you think that is better insert it? 

Yes, this one is ok: \test\plugin.test.js

**Comment by RafaelGSS** [comment]
Oh! I'll fix it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RafaelGSS** [comment]
Done! Guys, How I can run the pipeline locally? before commit

**Comment by RafaelGSS** [comment]
Anyone can merge?

**Comment by mcollina** [comment]
Thanks!

**Pull request merged**
