### PR TITLE
docs(ecosystem): add 2 new fastify v3.x+ plugins

### PR DESCRIPTION
**Pull request by WNemencha**
This commit/PR adds the following plugins to the community section of the plugins' list:

- [`@ethicdevs/fastify-custom-session`](https://github.com/EthicDevs/fastify-custom-session)
- [`@ethicdevs/fastify-git-server`](https://github.com/EthicDevs/fastify-git-server)

Hope you'll like them 😛

#### Checklist

- [ ] ~run `npm run test` and `npm run benchmark`~ (not applicable)
- [ ] ~tests and/or benchmarks are included~ (not applicable)
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Could you check the CI?

It tells us:

> @eropple/fastify-openapi3 not listed in alphabetical order

**Comment by WNemencha** [comment]
@Eomm done ;)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Fdawgs — APPROVED** [review]

**Comment by WNemencha** [comment]
Thanks guys! 🙏

**Pull request merged**
