### PR TITLE
Add fastify-opentelemetry to ecosystem doc.

### PR DESCRIPTION
**Pull request by HW13**
#### Summary
We recently open-sourced our fastify-opentelemetry plugin and thought it might be a useful addition to the Fastify ecosystem.

#### Related Issues
 - #2097 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
This module is currently released as UNLICENSED, i.e. proprietary. It's not really suitable for being added to this page.

It might be that your intention is to release it under an Open Source license. In that case, let us know what you pick!

(Good work on the module)

**Comment by HW13** [comment]
Thanks @mcollina. My bad on the license, it's been switched it to MIT 👍

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by HW13** [comment]
Thanks! 😎 👍

**Pull request merged**
