### PR TITLE
chore: use automerge actions

### PR DESCRIPTION
**Pull request by salmanm**
- Use new automerge action

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
cc @fastify/fastify I would like to ask @salmanm to move the github action in the org. Wdyt?

**Comment by zekth** [comment]
Seems like a good thing yeah. Also one thing would be to add `exception` packages, like some we want to have a manual review on.

**Comment by mcollina** [comment]
@salmanm could you add that?

(note that we don't have any here).

**Comment by salmanm** [comment]
Ok, I can add the exclusion list as input to the action. Since we're moving it to the org, I'll do this enhancement after.

**Review by zekth — APPROVED** [review]
lgtm

**Pull request merged**
