### PR TITLE
feat: add mkcalendar and report methods

### PR DESCRIPTION
**Pull request by keyservlad**
Related to [#9](https://github.com/fastify/fastify/issues/9) and [PR #3836](https://github.com/fastify/fastify/pull/3836)

Includes support for `MKCALENDAR` and `REPORT` methods which are both part of the webDAV protocol.

I need to use these methods in a project that deals with contacts and calendars sync (CARDDAV / CALDAV).

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by gurgunday** [comment]
> Support for MKCALENDAR on the server is only RECOMMENDED and not REQUIRED

Just adding context, but it’s fine I think

**Comment by gurgunday** [comment]
Do you know if there are other missing methods

**Review by Uzlopak — APPROVED** [review]
RSLGTM

**Review by gurgunday — APPROVED** [review]
https://icalendar.org/RFC-Specifications/CalDAV-Access-RFC-4791/

**Comment by metcoder95** [comment]
Tests seems failing

**Review by Eomm — APPROVED** [review]
TIL https://datatracker.ietf.org/doc/html/rfc4791#section-5.3.1

**Comment by gurgunday** [comment]
@keyservlad can you open a PR to `next` to add them there as well?

https://github.com/fastify/fastify/blob/ad8925010af809cf136ba0864b39f74418e7cc42/lib/httpMethods.js#L13-L29

**Comment by keyservlad** [comment]
> @keyservlad can you open a PR to `next` to add them there as well?
> 
> https://github.com/fastify/fastify/blob/ad8925010af809cf136ba0864b39f74418e7cc42/lib/httpMethods.js#L13-L29

Hey @gurgunday i just created the new pr #5444 but for some reason some tests are failing if you can help me figuring out why ¯\_(ツ)_/¯

**Pull request merged**
