### PR TITLE
feat: updated router types

### LINKED ISSUE #4376: Wrong typings for hooks on route options
The in the snippet below, the hook types are a union of two identical types like `onRequestHookHandler<...> | onRequestHookHandler<...>` etc, and this excludes the async hook type, which should be valid to use here, right?

Are these supposed to be <code>onRequestHookHandler<...> | onRequest<em><b>Async</b></em>HookHandler<...></code>, etc?

https://github.com/fastify/fastify/blob/5c75f4993255a7e3fc5afbdc4b8171be52ecb618/types/route.d.ts#L48-L56

### PR DESCRIPTION
**Pull request by ismailmmd**
Fixes #4376 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
Can you add unit test for your changes?

**Review by imnitin28 — APPROVED** [review]

**Comment by mcollina** [comment]
Tests are failing, too

**Review by imnitin28 — CHANGES_REQUESTED** [review]
Needs Improvement as tests are failing too. Need to add unit tests.

**Comment by Eomm** [comment]
Supersedes by https://github.com/fastify/fastify/pull/4655

**Pull request closed without merging**
