### PR TITLE
Added type definition for allowUnsafeRegex

### PR DESCRIPTION
**Pull request by xijdk**
[allowUnsafeRegex](https://www.fastify.io/docs/latest/Reference/Server/#allowunsaferegex) option caused an error with TS, now it's fixed

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Please add a typings test.

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test? We use tsd.

**Comment by Uzlopak** [comment]
@mcollina 

Added typing tests. PTAL

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
