### PR TITLE
types: Export preClose hook types

### PR DESCRIPTION
**Pull request by matthyk**
Exports the types of the preClose hook.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you add a test? We use tsd for our types

**Comment by matthyk** [comment]
My description of the PR was probably not detailed enough. You can currently import the two types for the `preClose` hook from `fastify/types/hooks`, but actually the types should be imported directly from `fastify`, like all other hook types. Should we really test the correct export? There are no tests for the export of the other hook types either.

**Comment by matthyk** [comment]
I simply imported the two types into the test. The test would fail if the two types were not exported.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
