### PR TITLE
Rename types/tsconfig.json to types/tsconfig.eslint.json to avoid hoisting by vscode

### PR DESCRIPTION
**Pull request by nopeless**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

My vscode picks up this tsconfig. Regardless of me fixing this or not, I don't think you should be publishing this either

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
This is not the correct solution.

rename types/tsconfig.json to types/tsconfig.eslint.json and set in types/.eslintrc.json "project" to "./types/tsconfig.eslint.json".

Then you vscode should not pick it up, and we have still working linting.

**Comment by nopeless** [comment]
@Uzlopak thanks for the reply, but I think there was a misunderstanding

I am not developing fastify. tsconfig was picked up while it was in node_modules, which is a weird behaviour from typescript lsp plugin. Still, the final distributed packagebshouldn't contain a tsconfig.

If I am missing a crucial point, let me know

**Comment by Uzlopak** [comment]
I made the changes I suggested. We will still publish the file, but your issue should be gone, because tsconfig.json is now named tsconfig.eslint.json.

**Review by climba03003 — COMMENTED** [review]
Interesting, TypeScript should ignore the `node_modules` by default? or am I missing anything?

If the configuration is picked up, should it be a bug on the LSP?

**Comment by nopeless** [comment]
> Interesting, TypeScript should ignore the `node_modules` by default? or am I missing anything?
> 
> If the configuration is picked up, should it be a bug on the LSP?

It is indeed a bug on the LSP.

**Comment by nopeless** [comment]
> > Interesting, TypeScript should ignore the `node_modules` by default? or am I missing anything?
> > If the configuration is picked up, should it be a bug on the LSP?
> 
> It is indeed a bug on the LSP.

Thinking about it, it might be eslint (I use typescript-eslint). But fastify was the only module causing this issue so

**Comment by Uzlopak** [comment]
Imho it does not hurt to apply this change.

**Review by climba03003 — APPROVED** [review]
Yes, it doesn't hurt.
Better to see a linked issue to TypeScript ESLint for tracking.

**Pull request merged**
