### PR TITLE
Use outlined logo, visible at dark

### PR DESCRIPTION
**Pull request by laSinteZ**
Add white outline to a fastify logo so it's visible in the dark mode. Should be merged after https://github.com/fastify/graphics/pull/8

Demo:
https://github.com/laSinteZ/fastify
https://www.npmjs.com/package/lasintez-fastify-but-i-just-test-readme

Screenshot 2021-04-24 at 10 52 22

Screenshot 2021-04-24 at 10 52 16

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — APPROVED** [review]
😍

**Review by mcollina — APPROVED** [review]
lgtm

**Review by zekth — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
