### PR TITLE
Log to logger

### PR DESCRIPTION
**Pull request by allevo**
As titled

NB: this is a breaking change

### CODE REVIEW

**Comment by delvedor** [comment]
Why?

**Comment by allevo** [comment]
1. in `fastify` instance the logger is under `logger` not under `log`
2. `log` is an action not an object. `logger` is the object that is able to log

**Comment by delvedor** [comment]
Why not rename `fastify.logger` in `fastify.log`?

If we talk about semantics I think about log as an action.
`fastity.log.info` => fastify log an information
`fastity.log.warn` => fastify log a warning

**Comment by allevo** [comment]
It is the same for me but... commonly it is named `logger` not `log`

Hapijs uses `log` as server method.
`bunyan` use `createLogger` but in the documentation calls `logger` `log`.

I don't know which rename is better.

**Comment by allevo** [comment]
I don't like (I'm thinking to `console.log` and `console.error`) but the most important thing is to keep the same name in `fastify` instance and in `req`.

Tomorrow I'll update this PR to change `fastify.logger` in `fastify.log`

**Comment by delvedor** [comment]
Closed by https://github.com/fastify/fastify/pull/436.

**Pull request closed without merging**
