### PR TITLE
Use themed SVG instead of PNG

### PR DESCRIPTION
**Pull request by laSinteZ**
This way, users who've set their system theme as dark/light and github theme as "As in system" will see logo

We should merge https://github.com/fastify/graphics/pull/7 first.

## Possible drawbacks
As was mentioned in https://github.com/fastify/fastify/issues/2779#issuecomment-825638310, users who have "dark" github theme but "light" system theme and "light" github theme but "dark" system won't see the logo. I am not sure if we want that. 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by laSinteZ** [comment]
I'll close this since this change will break the logo in NPM

**Comment by mcollina** [comment]
> I'll close this since this change will break the logo in NPM

unfortunately so :(

**Comment by laSinteZ** [comment]
https://github.com/fastify/fastify/issues/2779#issuecomment-826051804 @mcollina I can open a PR for this instead.

**Comment by mcollina** [comment]
that seems better!

**Pull request closed without merging**
