### PR TITLE
fix for fastify-guard plugin position

### PR DESCRIPTION
**Pull request by hsynlms**
I did a mistake and put the `fastify-guard` plugin in the core plugin list. Sorry about that.

See: https://github.com/fastify/fastify/pull/2524

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by hsynlms** [comment]
@mcollina it looks like my 2 commits merged in a wrong way. fyi.

**Comment by mcollina** [comment]
what do you mean?

**Comment by hsynlms** [comment]
I just move the plugin from Core plugin list to Community list but after merge, it seems the plugin does exist in both lists.

**Comment by mcollina** [comment]
Can you please send a PR to fix? Thanks

**Comment by hsynlms** [comment]
sure!

**Pull request merged**
