### PR TITLE
Add express middleware compatibility notice

### LINKED ISSUE #1276: Questions about mounting Express App
#### You have already researched for similar issues?
yes i have similar problems are present but Im looking for more of an example since I cant get things working right. 

#### Are you sure this is an issue with the fastify or are you just looking for some help?
https://github.com/fastify/fastify/issues/306
Talks about a similar issues so does
https://github.com/fastify/fastify/issues/1175

What im trying to do is use 
https://github.com/bee-queue/arena#readme
inside a fasitfy app.  When i use 

fastify.use (arena) 
 
I get a working sub app but my other routes do no work.  Similary if I disable the arena sub app all my other routes work.  

Can anyone please advise or demonstrate mounting an express sub app.  I seem to always get in a position where the sub app works and the rest of the application hangs on requests.  If i disable the sub app everything works as expected but I have disabled the sub app. 

Thanks

### PR DESCRIPTION
**Pull request by cemremengu**
Closes #1276 

Let me know if we can improve this.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by cemremengu** [comment]
@mcollina Could you help me with the examples part? I am not very experienced with express middleware and most important ones are already available natively in Fastify

**Comment by mcollina** [comment]
as an example, it's not possible to use `res.sendFile()` or `res.send()`, those are express-specific functions. Also, any usage of `new express.Router()` is not supported.

**Comment by cemremengu** [comment]
I am not sure if `multer` is compatible on a second thought

**Comment by mcollina** [comment]
Forget `multer`.

Compatible: `cors`
Non-compatible: `passport`

**Comment by dougwilson** [comment]
Express does not add res.end, FYI. As far as I know that is just part of Node.js core and res being a writable stream.

**Comment by delvedor** [comment]
@dougwilson you are right, we have missed that, thank you for pointing it out!

@cemremengu would you like to fix this? :)

**Comment by mcollina** [comment]
PR is already there: https://github.com/fastify/fastify/pull/1327.

**Pull request merged**
