### PR TITLE
Docs: Update Server#logger to discuss custom logger option

### LINKED ISSUE #1542: Update Server#logger to discuss custom logger option
The [Server#logger](https://www.fastify.io/docs/latest/Server/#logger) doc section lists 3 options for the logger server option. I believe the `pinoInstance` option should be expanded (or a new, 4th option should be added) to tell the user they can define or use their own custom logger as long as it follows the rules set forth by our code (I believe it needs a certain list of methods and an optional serializer list for `req`, `res`, and `err`).

### PR DESCRIPTION
**Pull request by dave-oo**
Added a fourth option under server logging discussing a custom logger. Closes #1542.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
@mcollina I know Bunyan has the `child` method but I’m not sure about log4js.

**Comment by mcollina** [comment]
We should add Bunyan

**Comment by Eomm** [comment]
> We should add Bunyan

@mcollina Do you mean in this PR as example, instead of the one provided by @dave-oo ?

**Comment by mcollina** [comment]
> @mcollina Do you mean in this PR as example, instead of the one provided by @dave-oo ?

I would like to add link to Bunyan somewhere, not a blocker. Let's land this and maybe open a new issue with "good first contribution"

**Pull request merged**
