### PR TITLE
Update Ecosystem.md - Add fastify-impressions to the list

### PR DESCRIPTION
**Pull request by manju4ever**
`fastify-impressions` is a plugin used to track impressions on the routes. 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation for plugin is updates
- [x] commit message and code follows the [Developer's Certification of Origin]

### CODE REVIEW

**Review by luisorbaiceta — CHANGES_REQUESTED** [review]
Please, follow alphabetical order

**Comment by manju4ever** [comment]
Sure @luisorbaiceta , i'll do the required changes.

**Review by luisorbaiceta — APPROVED** [review]
lgtm

**Review by xtx1130 — APPROVED** [review]
LGTM with a suggestion: I think it's better to put  [plugin.spec.js](https://github.com/manju4ever/fastify-impressions/blob/main/plugin.spec.js) in `/test` folder

**Comment by manju4ever** [comment]
@xtx1130 , i've moved the tests to separate folder. Optimized deps too. Pushed to `1.0.5`

**Comment by manju4ever** [comment]
Is there something pending with this request ?

**Comment by jsumners** [comment]
> Is there something pending with this request ?

Patience.

**Comment by manju4ever** [comment]
Good one. My bad 😀

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by manju4ever** [comment]
Thank you so much @mcollina.

**Pull request merged**
