### PR TITLE
Add plugin test showing non-scoped plugins

### PR DESCRIPTION
**Pull request by jsumners**
See subject.

### CODE REVIEW

**Comment by mcollina** [comment]
@delvedor what do you think about this?

**Comment by jsumners** [comment]
Changing `plugin` to `register` and `addServerMethod` to `decorate` results in this test failing. Did I misunderstand the changes to the API?

**Comment by delvedor** [comment]
Did you update your local branch to the latest changes done in #53?

**Comment by jsumners** [comment]
@delvedor yes.

**Comment by jsumners** [comment]
If `fastify-plugin` must be used, then this test is no longer valid. The point of this test was to show how the built-in plugin mechanism works.

**Comment by delvedor** [comment]
I don't agree, this test is useful to demonstrate that the plugins declared inside ancestors are available in the sons, the test suite done in #53 is not checking this.

**Comment by jsumners** [comment]
I see how it works now. It's more complicated than the previous API. Which led to some confusion on my part.

I have updated the test to pass with the new API.

**Comment by delvedor** [comment]
Thanks for the help and feedback! :)
In my opinion the new api is less complicated, since the user that will use fastify will use register for everything, either plugins or routes.

The fastify-plugin module is a tool for the plugin developers, that will add the 'skip-override' hideen property and, if needed, check the version of fastify, in this way you can set a bare minimum fastify version for your plugin.

I can agree that using all inside the same code could be a bit confusing, but (in theory) it will not happen.

**Pull request merged**
