### PR TITLE
Docsify support

### PR DESCRIPTION
**Pull request by mcollina**
This commit adds [docsify](https://docsify.js.org) support to our docs. Test with

- `npm install docsify-cli -g`
- `docsify serve .`

cc @lmammino @delvedor 

What do you think? This might be pretty much no-maintenance.

### CODE REVIEW

**Comment by delvedor** [comment]
I love it! Very nice UI.

*ps We should update the various links in the documentation to avoid redirect to the repo.*

**Comment by lmammino** [comment]
Wow i didn't know this one. It looks extremely promising. Anyway i still think jekyll could give us a bit more flexibility in building a complete website with multiple sections (not just docs, but also benchmark, ecosystem, etc.). I think i can have a demo proposal In a couple of days, then i supposed we can decide if we like a jekyll setup or not 😉

**Comment by mcollina** [comment]
Definitely! I would still prefer a jekyll approach, as it would mean better
SEO. Feel free to lift the changes to the md files. I moved them from
absolute links to relatives, it should be better for jekyll if I remember
correctlyz
Il giorno dom 23 lug 2017 alle 16:20 Luciano Mammino <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
I think we can close this.

**Pull request closed without merging**
