### PR TITLE
Add fastify-appwrite plugin

### PR DESCRIPTION
**Pull request by Dev-Manny**
A fastify plugin for interacting with Appwrite backend server

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by Dev-Manny** [comment]
Add fastify-appwrite plugin

**Comment by mcollina** [comment]
For compatibility with other plugins and apps, I would recommend to wrap all the decorated services into a single property. They should be accessed via `fastify.appwrite.user` or similar.

**Comment by Dev-Manny** [comment]
> For compatibility with other plugins and apps, I would recommend to wrap all the decorated services into a single property. They should be accessed via `fastify.appwrite.user` or similar.

I agree with you @mcollina. I will make the necessary changes.

**Comment by Dev-Manny** [comment]
@RafaelGSS @mcollina  I have made the necessary changes.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by mcollina** [comment]
Thanks! Great to see!

**Pull request merged**
