### PR TITLE
ts missing headers routeschema #1378

### LINKED ISSUE #1378: Fastify Typescript RouteSchema missing headers?: JSONSchema
Hello

Thank you for the great Fastify project. We're moving from Express to Fastify, because of async/await support and schema driven approach.

While using fastify v2 with typescript the following code:

```js
  const endpointsSchemas: fastify.RouteSchema = {
    querystring: '#schema-id-1#',
    headers: '#schema-id-2#',
    response: {
      200: '#schema-id-3#',
    },
  };
```

produces ts error:

```sh
error TS2322: Type '{ querystring: string; headers: string; response: { 200: string; }; }' is not assignable to type 'RouteSchema'.
  Object literal may only specify known properties, and 'headers' does not exist in type 'RouteSchema'.
         headers: '#schema-id-2#',
```

fix seems simple:
instead of https://github.com/fastify/fastify/blob/master/fastify.d.ts#L185
```js
  interface RouteSchema {
    body?: JSONSchema
    querystring?: JSONSchema
    params?: JSONSchema
    response?: {
      [code: number]: JSONSchema,
      [code: string]: JSONSchema
    }
  }
```

it should be

```js
  interface RouteSchema {
    body?: JSONSchema
    querystring?: JSONSchema
    params?: JSONSchema
    headers?: JSONSchema
    response?: {
      [code: number]: JSONSchema,
      [code: string]: JSONSchema
    }
  }
```

If that is correct I'd be happy to open PR with the fix.

Meanwhile we're using self declared type.

### PR DESCRIPTION
**Pull request by mandaputtra**
I also got the same problem as #1378. Seems like the fix already on the discussion. Closes #1378 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by mandaputtra** [comment]
Okay

**Comment by delvedor** [comment]
Hello! Any update on this one?

**Comment by cemremengu** [comment]
I think @mandaputtra is already AFK as he [mentioned](https://github.com/fastify/fastify/issues/1378#issuecomment-453729590) so this might be stalled for some time

**Comment by delvedor** [comment]
I would like to land this asap since we are very close to the final rc.
@mandaputtra @reposandermets  If you don't have time to continue the work please let us know, and we will finish the job :)

**Comment by reposandermets** [comment]
> I would like to land this asap since we are very close to the final rc.
> @mandaputtra @reposandermets If you don't have time to continue the work please let us know, and we will finish the job :)

@delvedor unfortunately I don't have permissions to push directly the type test code into @mandaputtra's branch. What would you recommend, should I open a separate Pull Request where I can easily include both fix and test code?

**Comment by delvedor** [comment]
Let's give some time to @mandaputtra to answer, and if he doesn't send an answer by tomorrow, you can go ahead and open a separate pr :)

**Comment by reposandermets** [comment]
> Let's give some time to @mandaputtra to answer, and if he doesn't send an answer by tomorrow, you can go ahead and open a separate pr :)

alright, going to check this thread after 24h

**Comment by Ethan-Arrowood** [comment]
You can give @mandaputtra commit co-authorship on your pr @reposandermets 
https://help.github.com/articles/creating-a-commit-with-multiple-authors/

**Comment by reposandermets** [comment]
> You can give @mandaputtra commit co-authorship on your pr @reposandermets
> https://help.github.com/articles/creating-a-commit-with-multiple-authors/

@Ethan-Arrowood thank you for the info. I didn't use this tip though, because authorship in #1393 seems correct. Please let me know if anything needs to be changed in #1393.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify/pull/1393.

**Pull request closed without merging**
