### PR TITLE
Add fastify-no-icon to ecosystem list

### PR DESCRIPTION
**Pull request by jsumners**
Adds the https://www.npmjs.com/package/fastify-no-icon module to the ecosystem list.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Aren't we returning a 404 by default if a route does not match?

**Comment by jsumners** [comment]
Yes, we return a 404. But the plugin solves the following:

1 term screen-256color-bce tmux -2 tmux 2018-01-17 10-37-56

**Comment by jsumners** [comment]
1 term screen-256color-bce tmux -2 tmux 2018-01-17 10-40-27

**Comment by mcollina** [comment]
Ahum, we should probably log with lower severity not found errors.

**Pull request merged**
