### PR TITLE
fix: potential bug in content type parser

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — DISMISSED** [review]
Please add a test that fails without this change.

**Comment by Uzlopak** [comment]
First I want to see if the CI/CD pipeline fails or not. I have locally issues with running the tests, some unrelated tests fail.

**Comment by Uzlopak** [comment]
Ok, it seems like my expectation was met and the codechange did not make it fail the ci pipeline. 

I guess the unit test passes because it falls back to the json parser. Will provide a unit test asap.

**Comment by climba03003** [comment]
> I guess the unit test passes because it falls back to the json parser. Will provide a unit test asap.

Interesting, it is not failed because `this.name === this.type` in essence check.
And `toString` method do the trick.

```js
var a = { toString() { return 'a' } }
'abc'.indexOf(a) // it is actually 0 
```

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by Uzlopak** [comment]
Added 3 Unit tests.

**Comment by climba03003** [comment]
Why we would like to support a content type with leading and trailing space?
It should be a side effect of using parser.

Just a reminder, it is breaking change.

**Review by Eomm — APPROVED** [review]
I don't think it is breaking because the headers are trimmed and the spaces are preserved only if the user set the header value as `"   application/json"` (with double quotes)

**Comment by climba03003** [comment]
> I don't think it is breaking

It is a breaking change because here change from `.name` check to `.type` check.
Please read the first comment.

**Comment by climba03003** [comment]
Consider the below case currently supported, but not documented.

```js
test('allow partial content-type', async t => {
  t.plan(1)

  const fastify = Fastify()
  fastify.removeAllContentTypeParsers()
  fastify.addContentTypeParser('json', function (request, body, done) {
    t.pass('should be called')
    done(null, body)
  })

  fastify.post('/', async () => {
    return 'ok'
  })

  await fastify.inject({
    method: 'POST',
    path: '/',
    headers: {
      'content-type': 'application/json; foo=bar; charset=utf8'
    },
    body: ''
  })
})
```

**Comment by Eomm** [comment]
I tested only the spacing cases, not the `fastify.addContentTypeParser('json'` 👍🏽

**Comment by Uzlopak** [comment]
I doubt that that works, because content-type parser will filter out media-types without / in it as invalid.

**Review by mcollina — DISMISSED** [review]
lgtm

**Comment by climba03003** [comment]
> I doubt that that works, because content-type parser will filter out media-types without / in it as invalid.

Don't mix-up supported content-type and incoming content-type.
Your change affect the supported content-type (which is given by the developer and doesn't require to be a fully specified content-type.), the current state which is allowed by checking the `name`.
Incoming content-type never affected which require to be a valid content-type.

**Review by climba03003 — CHANGES_REQUESTED** [review]
Blocking, to be sure everyone know it is a breaking change before land.
One possible plugin that break would be [`@fastify/multipart`](https://github.com/fastify/fastify-multipart/blob/2f77fdd4d251c8ddf0b5140028dfd9c7d52af32c/index.js#L194)

Or, use `this.name = contentType.trim()` which does the same without breaking change.

**Comment by Uzlopak** [comment]
hmm. it seems to me, that the implementation in fastify/multipart is wrong in the first place. It should be multipart/form-data and not multipart.

**Comment by Uzlopak** [comment]
Well, should we target the next branch for this PR?

**Comment by mcollina** [comment]
@climba03003 @Uzlopak could you reach an agreement on the couple of PRs open on this? I don't understand the conflict and what will break.

**Comment by climba03003** [comment]
> @climba03003 @Uzlopak could you reach an agreement on the couple of PRs open on this? I don't understand the conflict and what will break.

You can see the example in this comment.
https://github.com/fastify/fastify/pull/4477#issuecomment-1364500523

From what I can tell, `this.name = contentType.trim()` does the same with the case I mention and the test included in this PR.

**Comment by mcollina** [comment]
Could you send a PR with that test https://github.com/fastify/fastify/pull/4477#issuecomment-1364500523? So we know it's supported.

**Comment by Uzlopak** [comment]
I added the unit test of @climba03003 to this PR. tests pass

**Comment by climba03003** [comment]
Please update the text to the following one. You are actually added a parser that would match all `content-type`.
When parsing a partial is failed, it return `''` empty string for the `.type` and `.indexOf('') !== -1` is always `true`.

```js
test('allow partial content-type', async t => {
  t.plan(1)

  const fastify = Fastify()
  fastify.removeAllContentTypeParsers()
  fastify.addContentTypeParser('json', function (request, body, done) {
    t.pass('should be called')
    done(null, body)
  })

  fastify.post('/', async () => {
    return 'ok'
  })

  await fastify.inject({
    method: 'POST',
    path: '/',
    headers: {
      'content-type': 'application/json; foo=bar; charset=utf8'
    },
    body: ''
  })

  await fastify.inject({
    method: 'POST',
    path: '/',
    headers: {
      'content-type': 'image/jpeg'
    },
    body: ''
  })
})
```

**Comment by Uzlopak** [comment]
What about now?

**Comment by climba03003** [comment]
Look better, but still I believe more problem would cause than a fix when we allow trimming.

Consider the following is allowed but the developer have no idea which one should be matched (Should be the third one).
Some plugin maybe overriding with an extra `space`, than the `content-type` parser is actually replaced without notice.
```js
fastify.addContentTypeParser('   application/json   ', function (request, body, done) {
  done(null, body)
})
fastify.addContentTypeParser('application/json   ', function (request, body, done) {
  done(null, body)
})
fastify.addContentTypeParser('   application/json', function (request, body, done) {
  done(null, body)
})
```

And which one should be removed? Currently, none of them.
```js
fastify.addContentTypeParser('   application/json   ', function (request, body, done) {
  done(null, body)
})
fastify.addContentTypeParser('application/json   ', function (request, body, done) {
  done(null, body)
})
fastify.addContentTypeParser('   application/json', function (request, body, done) {
  done(null, body)
})
fastify.removeContentTypeParser('application/json')
```

**Comment by mcollina** [comment]
@Uzlopak are you still pursuing this?

**Comment by Uzlopak** [comment]
As we never agreed on how to solve this issue, i can not finalize this PR.

**Comment by Uzlopak** [comment]
@gurgunday 
@climba03003 

Is this PR finally obsolete? Of are there still some things we can derive from this? Can we close it?

**Comment by climba03003** [comment]
> Is this PR finally obsolete? 
Is https://github.com/fastify/fastify/pull/4509 answered your problem trying to fix in this PR.
As I remembered it was made for this PR.

**Comment by gurgunday** [comment]
> The next thing we need to consider is https://github.com/fastify/fastify/pull/4477#issuecomment-1378545312

See #5329, this is no longer possible 🙏

I want to actually look at increasing matches though, right now it seems like a Content-Type header like this: `        text/html` won't match the added parser, which is why we should be trimming it

**Comment by climba03003** [comment]
>See https://github.com/fastify/fastify/pull/5329, this is no longer possible 🙏

It partially addressed, you need to do the same to `.has` and `.remove`.

**Comment by climba03003** [comment]
I believe it covers by #4509, #5329 and #5372.

**Pull request closed without merging**
