### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
This adds a badge to the `README.md` file to display the npm install size

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by styfle** [comment]
Hi @delvedor 
I think this information is still relevant.

The `micro` team was able to make their package smaller after discovering the npm publish size was much larger than expected: https://github.com/zeit/micro/issues/234

The same with the `typescript` team here: https://github.com/Microsoft/TypeScript/issues/23339

**Comment by delvedor** [comment]
Still 👎, I don't see this as an issue.
The name of the service (*packagephobia*) says it all :D

**Comment by mcollina** [comment]
Thanks for your contribution, but it is very unlikely that we will accept this change.

**Comment by rictorres** [comment]
for reference: https://github.com/fastify/fastify/pull/1147#issuecomment-454585050

**Pull request closed without merging**
