### PR TITLE
Docs reorganization

### PR DESCRIPTION
**Pull request by jsumners**
Given the work done by @luisorbaiceta to implement partitioning of our documentation, a.k.a. implementing "Guides" support, this PR is intended to reorganize our documentation by splitting out the informal guides, e.g. "Getting Started", from our reference documentation, e.g. "Decorators". The intention of this PR **is not** to refactor the language of the reference docs to match the style of Decorators. That would be a subsequent PR.

However, I have come to a stopping point. As I was reorganizing the "Server" doc I discovered that we link to that document in a variety of ways. The ones I've noticed are (see the changed files):

+ `[foo](Server.md)`
+ `[foo](Server.md#section)`
+ `[foo](./Server.md)`
+ `[foo](./docs/Server.md)`

There is _sooooo_ much room for error in this. Not only error in making sure we hit all of the references for the re-org, but room for error in ongoing documentation efforts. We need a better way to cross reference docs within our documentation. This goes directly to issues like [website #291](https://github.com/fastify/website/issues/291). I don't know if we need to solve this problem before completing this PR, but it's one we need to solve at a high priority. Whatever system we adopt needs to support proper cross references.

As an example, Hugo does it like (https://gohugo.io/content-management/cross-references/):

```md
Please see our [Server docs]({{< ref "Server.md" >}}) for more information.
Specifically [some anchor]({{< ref "Server.md#some-anchor" >}}.
```

As Hugo builds the site it sees such short codes and recognizes the linked document from its built tree of documents and inserts an appropriate link. You can see this in my [most recent blog post](https://jrfom.com/posts/2021/11/17/career-path/) -- https://github.com/jsumners/jrfom.com/blob/c6080b4233459a587dfcaf8cf1ba2a58c6c2f00b/content/posts/2021/11/17/career-path.md?plain=1#L13-L21. The short code references in there are links to documents that are each in completely different parts of the source tree. I merely needed to know the name of the document I wanted to reference.

~All of that said, we can continue this PR if people are willing to help me. What I need are pull requests that target this pull request in which documents are moved into their correct category and links are updated throughout the doc set. Ideally, such pull requests would focus on a single document. ***I do not have time to complete this on my own.***~ Thank you @lachlancollins for all of the assistance in getting this PR ready.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
> Not only error in making sure we hit all of the references for the re-org, but room for error in ongoing documentation efforts. We need a better way to cross reference docs within our documentation. This goes directly to issues like website #291. I don't know if we need to solve this problem before completing this PR, but it's one we need to solve at a high priority. Whatever system we adopt needs to support proper cross references.

An important goal we should have is to keep the documentation consumable from GitHub. 

https://github.com/remarkjs/remark-validate-links _should_ solve the problem.

**Comment by jsumners** [comment]
> An important goal we should have is to keep the documentation consumable from GitHub.

In my opinion, this should no longer be a goal. We have too much documentation with too many, necessary, cross references. I think maintainability should take precedence at this point. Validating links exist is only part of the problem. The biggest problem is being able to easily write the references and know that they will work.

**Comment by lachlancollins** [comment]
In terms of the current work on [website-next](https://github.com/fastify/website-next/tree/main/docs), I've sourced it from this branch (the docs are currently stored in the repo until we write the script to clone the docs from this repo). To make Docusaurus compile, I had to make 2 key changes:

-  Fixing all the broken links (there were many)
- Moving (or removing) header hyperlinks - there needs to be a new line above headers ("true" Markdown styling). There was no problem if the hyperlinks were directly below the headers.

image

This raises a problem for any solution we adopt - we cannot go back to old versions and fix their links (or metadata). Since we are already favouring only displaying docs for major versions, I propose a new structure to docs in the main repo:

- /docs
  - /v1
  - /v2
  - /v3

This would allow us to go back and fix any links, add any metadata, etc. to the older versions. It would also make it easier to write a script to import the docs into the website generator.

**Comment by luisorbaiceta** [comment]
I have started with the docs processing scripts. The result would be a folder as we had in the previous version, with one nested folder per version. `process.js` already takes care of remapping links to the correct version, but there is some work to do with the multiple link types we can find right now. Is this ok for docusaurus? Do we need some special linking convention to follow in future docs? @lachlancollins 

I think unifying the links as suggested by @jsumners should be enough. Is that correct?

**Comment by lachlancollins** [comment]
Hi @luisorbaiceta, there's no special linking required in Docusaurus, and while I'm not familiar with what `process.js` currently does I think I get what you're saying - that probably isn't necessary with Docusaurus either :) I'm happy to explain what would be needed in the scripts if we migrate to Docusaurus, but we should probably do that over on the `website-next` repo.

**Comment by jsumners** [comment]
Please keep this discussion strictly about the documentation. Yes, this work impacts whatever is done for website generation, but the focus here should be on the docs.

**Comment by jsumners** [comment]
> This raises a problem for any solution we adopt - we cannot go back to old versions and fix their links (or metadata). Since we are already favouring only displaying docs for major versions, I propose a new structure to docs in the main repo:
> 
> * /docs
>   
>   * /v1
>   * /v2
>   * /v3
> 
> This would allow us to go back and fix any links, add any metadata, etc. to the older versions. It would also make it easier to write a script to import the docs into the website generator.

Maybe I am misunderstanding you, but I disagree with this proposal as it sounds like it will make maintaining the documentation very cumbersome. It sounds like the majority of documentation would need to be duplicated and maintained in multiple places.

**Comment by lachlancollins** [comment]
@jsumners yes you're 100% right, I wasn't a massive fan of the solution, luckily someone suggested an alternative at #3942.

I've found [this vscode package](https://marketplace.visualstudio.com/items?itemName=mathiassoeholm.markdown-link-updater) which should make it easy to move docs into the Guide/Reference folders now that I have links working well (I don't think I've pushed my updated links yet). I'll be able to try this tomorrow!

**Comment by luisorbaiceta** [comment]
I agree that keeping current way of handling versions is better for users targeting previous fastify builds. I could make the processing scripts just take the latest of 1.x, 2.x, etc. But I don't see why if we have the chance to go in depth we simplify the docs that much... Besides, current scripts take the gzipped releases for further processing, It's not downloading on a per branch basis

**Comment by jsumners** [comment]
> I agree that keeping current way of handling versions is better for users targeting previous fastify builds. I could make the processing scripts just take the latest of 1.x, 2.x, etc. But I don't see why if we have the chance to go in depth we simplify the docs that much... Besides, current scripts take the gzipped releases for further processing, It's not downloading on a per branch basis

This question is about website maintenance. Please take it to an existing, or new (preferred), thread in that repository.

**Comment by jsumners** [comment]
@luisorbaiceta are you able to help confirm that this branch will result in the desired rendering of the website? I don't know how to test it.

**Comment by luisorbaiceta** [comment]
> @luisorbaiceta are you able to help confirm that this branch will result in the desired rendering of the website (with the current code)? I don't know how to test it.

I'll test this tomorrow. I will see If I can provide an easy way for people to test it too.

**Comment by jsumners** [comment]
> > @luisorbaiceta are you able to help confirm that this branch will result in the desired rendering of the website (with the current code)? I don't know how to test it.
> 
> I'll test this tomorrow. I will see If I can provide an easy way for people to test it too.

Thank you.

**Comment by luisorbaiceta** [comment]
everything is working as expected @jsumners 

image

**Comment by jsumners** [comment]
awwwwwwww-excited

However, I'm not seeing the text of `/docs/index.md` rendered there?

**Comment by jsumners** [comment]
> If there is no section selected we could show the `/docs/index.md` you are suggesting with the toc sidebar. User can already select the version from the breadcrumb and we are defaulting to the latest version anyway. Doing this would simplify the user flow a lot.

I think this scenario is what I am expecting.

**Comment by luisorbaiceta** [comment]
I'll wait for the final migration decision to open a PR for this

**Comment by jsumners** [comment]
> I'll wait for the final migration decision to open a PR for this if we decide to stick with current website. If we migrate then we'll have to see how this is achievable with the new stack. @lachlancollins

This PR should not be blocked by the `website-next` project. I have tried above, repeatedly, to make that clear. This PR can feed into that project, but it is meant to be completely independent of it.

**Comment by luisorbaiceta** [comment]
I know. I just wanted to highlight this to @lachlancollins so he can think about it when working in parallel in the other project. Didn't mean to discuss it here, sorry.

**Comment by jsumners** [comment]
> I know. I just wanted to highlight this to @lachlancollins so he can think about it when working in parallel in the other project. Didn't mean to discuss it here, sorry.

👍 

To get back to my question: do we need to do anything to the current website to support this PR fully? I am willing to accept:

+ https://github.com/fastify/fastify/pull/3474#issuecomment-982943091
+ with https://github.com/fastify/fastify/pull/3474#issuecomment-982840295

if the rest of @fastify/core is.

**Comment by luisorbaiceta** [comment]
> IMO, a good solution would be to remove the `/docs` (the one with the versions), and the `/docs/${version}` page, and directly point the `docs` link to this page:
> 
> image
> 
> If there is no section selected we could show the `/docs/index.md` you are suggesting with the toc sidebar. User can already select the version from the breadcrumb and we are defaulting to the latest version anyway. Doing this would simplify the user flow a lot.

This is the go-to solution if we want to simplify user flow. But for this I'll need to find some time and I don't think I will any time soon.

We first need @fastify/core approval

**Comment by mcollina** [comment]
Thanks for taking it to this point. I had not much time to follow up on this and I won't for another week or two.

Can you prepare a rollout plan of things that should happen to bring this to production?

(Note that whenever we land a change in Fastify we rebuild the website by triggering CircleCI.

**Comment by luisorbaiceta** [comment]
Do you want me to open an issue with the steps? @mcollina

**Comment by jsumners** [comment]
> Do you want me to open an issue with the steps? @mcollina

I think that would be helpful.

**Comment by Eomm** [comment]
I agree to land this pr as is. the website-next is an ongoing project and I can't see any blocker for this reorg

**Comment by jsumners** [comment]
Taking this back to draft mode. I forgot that the `index.md` files are not complete yet.

**Comment by luisorbaiceta** [comment]
> everything is working as expected @jsumners
> 

Or so I thought... 😬

I have been trying every link in the page with this branch and I get some 404s. I assume that as this is a work in progress this is expected behaviour. But as the goal of this PR is to make linking consistent, I will wait for it to be over to clean up the [`remapLinks`](https://github.com/fastify/website/blob/944247a26dd331f34bb5dfaf240fdff34badc87f/src/scripts/processReleases.js#L176) method in the scripts.

**Comment by jsumners** [comment]
> > everything is working as expected @jsumners
> 
> Or so I thought... 😬
> 
> I have been trying every link in the page with this branch and I get some 404s. I assume that as this is a work in progress this is expected behaviour. But as one of the goals of this PR is to make linking consistent, I will wait for it to be over to clean up the [`remapLinks`](https://github.com/fastify/website/blob/944247a26dd331f34bb5dfaf240fdff34badc87f/src/scripts/processReleases.js#L176) method in the scripts.

I think the docs are as re-organized as they are going to get. Now I need to find time to finish the index files. So if you are finding broken links, a PR targeting this branch would be really helpful.

**Comment by luisorbaiceta** [comment]
Linking problem is caused by current scripts not supporting [reference-style links](https://www.markdownguide.org/basic-syntax/#reference-style-links) when remapping @jsumners

**Comment by jsumners** [comment]
> Linking problem is caused by current scripts not supporting [reference-style links](https://www.markdownguide.org/basic-syntax/#reference-style-links) when remapping @jsumners

I see. Thank you for finding this issue.

**Comment by jsumners** [comment]
@luisorbaiceta is this PR blocked by https://github.com/fastify/website/issues/298?

**Comment by luisorbaiceta** [comment]
I'm afraid yes. I will try to find time to get hands on this next week. In the meantime, If anyone is fluent with regex this can be addressed easily

**Comment by mcollina** [comment]
@luisorbaiceta @jsumners  what should I land on the website repo to make this work?

**Comment by luisorbaiceta** [comment]
Website repo is good to go. The build process downloads the releases from this repo. Merging this and retriggering the build should be enough

**Comment by mcollina** [comment]
@luisorbaiceta can you check the website build? After this change it’s now failing.

**Comment by luisorbaiceta** [comment]
I'm fixing it right now. As `Ecosystem.md` has been moved, there is a minor tweak that needs to be made.

**Comment by luisorbaiceta** [comment]
This will be visible the next time there is a release. Maybe detaching docs changes from releases would be a good PR...

**Comment by jsumners** [comment]
I'm sorry @lachlancollins that the squash and merge lost the references to your contributions. I didn't know that would happen. Your work on this is very much appreciated.

**Comment by delvedor** [comment]
Amazing work everyone!

**Pull request merged**
