### PR TITLE
add missing route shorthands

### LINKED ISSUE #4405: Please add route shorthand declarations for the remaining supported http methods.
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

(Similar but not identical to issue #9)

### 🚀 Feature Proposal

Currently, the Fastify shorthand declarations are limited to:
`fastify.get(path, [options], handler)`
`fastify.head(path, [options], handler)`
`fastify.post(path, [options], handler)`
`fastify.put(path, [options], handler)`
`fastify.delete(path, [options], handler)`
`fastify.options(path, [options], handler)`
`fastify.patch(path, [options], handler)`

Please add shorthand methods for the other valid route methods:
'SEARCH', 'TRACE', 'PROPFIND', 'PROPPATCH', 'MKCOL', 'COPY', 'MOVE', 'LOCK' and 'UNLOCK'

### Motivation

My organization has planned to begin using the search http method and phase out the use of POST for routes that query with a JSON body.  We currently use the shorthand declarations and would like to be able to maintain that consistency, as we also are phasing out and migrating from Express.js to Fastify.

### Example

```
const fastify = require('fastify')({ logger: true })

fastify.search('/', async (request, reply) => {
  return { found: 'world' }
})

const start = async () => {
  try {
    await fastify.listen({ port: 3000 })
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

### PR DESCRIPTION
**Pull request by Uzlopak**
Closes #4405 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — CHANGES_REQUESTED** [review]
Not convinced to land in `main`, but `next` is fine.
`search`, `trace`, `copy`, `move`, `lock` and `unlock` is a common wording that easy to conflict with the community.

**Comment by Uzlopak** [comment]
Just to clarify:

I am not eager to merge it into main. Just fixing a reported issue. I am totally fine to add it to next or v5.x

**Comment by Uzlopak** [comment]
changed target to next

**Review by jsumners — CHANGES_REQUESTED** [review]
You need to rebase this.

**Comment by climba03003** [comment]
I have merged `main` into `next` branch.
You can rebase on top of it.

**Review by Fdawgs — APPROVED** [review]

**Comment by Uzlopak** [comment]
@climba03003 
Thanks. I am always struggling with rebasing on github :/

**Review by climba03003 — APPROVED** [review]

**Review by jsumners — APPROVED** [review]

**Pull request merged**
