### PR TITLE
docs: Fix Pino docs link

### PR DESCRIPTION
**Pull request by BoscoDomingo**
More info here: https://sembr.org/

I updated the Pino docs link as the previous one was broken and took advantage to use Semantic Line Breaks for easier updates in the future without changing the formatting

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by BoscoDomingo** [comment]
Not sure if the commit message should be chore or docs. I came to the realisation after making the PR. Can easily change it if needed

**Review by Uzlopak — CHANGES_REQUESTED** [review]
I am against the use of semantic line breaks. It totally hurts my eyes to read the markdown.

**Comment by BoscoDomingo** [comment]
> If this is semantic line breaks, than I am against the use of semantic line breaks. It totally hurts my eyes to read the markdown.

Totally understandable. It is meant to be previewed and since nowadays that's fairly simple (e.g. VS Code's previewer syncs immediately and follows cursor) I thought it a decent thing to implement to avoid hard-to-track changes such as code and links. If undesired, the revert is simple and we can go with just the link fix 👍🏼

**Comment by Uzlopak** [comment]
Well, lets wait what the other maintainers say to this. 

I myself use vscode. But I dont expect anybody else use it. Maybe the vim fraction is also not happy about this.

**Comment by Fdawgs** [comment]
> If this is semantic line breaks, than I am against the use of semantic line breaks. It totally hurts my eyes to read the markdown.

Yeah, +1 on this, horrible to review. 🤮

**Review by jsumners — CHANGES_REQUESTED** [review]
Please limit this PR to the content fixes. It is very difficult to determine the substance of this PR from the formatting suggestion.

**Comment by BoscoDomingo** [comment]
Will do. TY for the feedback!

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by BoscoDomingo** [comment]
@Uzlopak kind reminder 🙏🏼

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
