### PR TITLE
Add myself to collaborators list

### PR DESCRIPTION
**Pull request by nwoltman**
As titled.

### CODE REVIEW

**Comment by StarpTech** [comment]
LGTM

**Comment by nwoltman** [comment]
😄

**Comment by lmammino** [comment]
@nwoltman, welcome on board 😉 

Can add yourself also [on the website](https://github.com/fastify/website/blob/master/src/website/data/team.yml)?

**Comment by nwoltman** [comment]
@lmammino Thanks! Sure, I'll have a PR ready soon :)

**Pull request merged**
