### PR TITLE
perf: optimize split params

### PR DESCRIPTION
**Pull request by Connormiha**
`split` has optional second argument. Since only the first argument of the array is used, you can interrupt parsing the string after the first match.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I learned something today, thx!

**Comment by Uzlopak** [comment]
Yeah, what? There is a second parameter for split??? Wow. It is even in the documentation on MDN.

**Review by gurgunday — APPROVED** [review]

**Comment by mcollina** [comment]
Tests seems to be failing

**Comment by Connormiha** [comment]
> Tests seems to be failing

Failed coverage-nix, coverage-win. I checked other PRs. The same tests failed.

**Comment by Fdawgs** [comment]
image

**Pull request merged**
