### PR TITLE
docs: add fastify-formdiable

### PR DESCRIPTION
**Pull request by climba03003**
My first plugin posted on Ecosystem.

The main different between this and `fastify-multipart` is their dependency.

`fastify-multipart` currently rely on `busboy` which is relatively inactive and it's overall architecture make it hard to integrate with `fastify-swagger`.

This plugin use `formidable` for multipart parsing and provide an easier way to handle files and integration.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]

**Comment by RafaelGSS** [comment]
Would it not be an update on `fastify-multipart`?

**Comment by climba03003** [comment]
> 
> 
> Would it not be an update on `fastify-multipart`?

`fastify-multipart` have it's own advantage of handling files in `asyncIterator` and which should generally use less memory.
Also, it can directly absorb the file stream but not saving it to disk.

I can't balance should we scarify the advantage and updated it as a totally different program.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

Code looks good and it provides a different take on the problem. I would use fastify-multipart anyway, but it's true that this option might have its own appeal.

**Pull request merged**
