### PR TITLE
Export error codes

### PR DESCRIPTION
**Pull request by fitiskin**
Handling https://github.com/fastify/fastify/discussions/3842 and https://github.com/fastify/fastify/issues/4250.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by fitiskin** [comment]
@mcollina Can you please suggest what this unit test should check? 

I see a lot of checks for error codes in current test cases like:

```javascript
t.equal(err.code, 'FST_ERR_SCH_VALIDATION_BUILD')
```

I can update them to depend on exported `errorCodes`:

```javascript
t.ok(err instanceof Fastify.errorCodes.FST_ERR_SCH_VALIDATION_BUILD)
```

if it makes sense.

I can add new tests but can't find a test case for them since it is just an export.

**Comment by fitiskin** [comment]
I see that not all error codes [listed in the documentation](https://www.fastify.io/docs/latest/Reference/Errors/#fastify-error-codes). I could add missed ones, but it's hard to provide a meaningful description because I am not familiar with them.

**Comment by mcollina** [comment]
> I see that not all error codes [listed in the documentation](https://www.fastify.io/docs/latest/Reference/Errors/#fastify-error-codes). I could add missed ones, but it's hard to provide a meaningful description because I am not familiar with them.

Add them even with a minimum description!

**Comment by fitiskin** [comment]
> Add them even with a minimum description!

Done :)

**Comment by leppaott** [comment]
Any way to get string representations exported? This doesn't seem very easy to use `instanceOf` with dozens of error codes. Would like simple like `error.code === errorCodes.FST_ERROR_X` so we can do `switch (error.code) { case: FST_ERROR }`?

Something like:
```
const ErrorStrings = {
  FST_ERR_NOT_FOUND: 'FST_ERR_NOT_FOUND',
  FST_ERR_CTP_ALREADY_PRESENT: 'FST_ERR_CTP_ALREADY_PRESENT',
  FST_ERR_CTP_INVALID_TYPE: 'FST_ERR_CTP_INVALID_TYPE'
} as const;

// Extending current implementation
type FastifyErrorCodes = Record<keyof typeof ErrorStrings, FastifyErrorConstructor>;```

**Pull request merged**
