### PR TITLE
fix: cb is not a function at fallbackErrorHandler

### PR DESCRIPTION
**Pull request by DzenDyn**
This fixes error if cb is not a function at fallbackErrorHandler:
image

Tests:
image

Benchmarks:
image

**Cheklist**:
- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks for opening a PR! Can you please add a unit test?

**Comment by DzenDyn** [comment]
I'm sorry, but I'm afraid I'm not quite sure how to do this.
I have not yet found how to trigger this error and at what point there may not be a callback, but Sentry caught an unhandled exception and the commit I proposed should fix it.

**Comment by metcoder95** [comment]
I'm starting to guess if your error handler is bad set, I couldn't reproduce it easily.
What I found instead, is that we are not validating properly the error handler when setting `fastify.setErrorHandler` in contrast to what we do at a route level, where indeed fails if a bad handler is passed.

```shell
TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.setErrorHandler (/Users/metcoder/Documents/Workspace/MetCoder/Fastify_Core/fastify.js:847:71)
    at Object.<anonymous> (/Users/metcoder/Documents/Workspace/MetCoder/Fastify_Core/playground.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
```

**Comment by Uzlopak** [comment]
Yes, should throw an error when setting the value.

**Comment by Uzlopak** [comment]
Closed as it was superseeded by #5317

**Pull request closed without merging**
