### PR TITLE
feat: remove `req.id` in serializer

### LINKED ISSUE #1029: Duplicate req id in incoming request log
The default logger output request id twice in the "incoming request" log record. As the request id may be not so short, this is a waste of log size.

A sample log is below, where the req id is generated by `nanoid` module.

```
{"level":30,"msg":"incoming request","reqId":"zvTdkL3H_Pm3NeSgG0ByD","req":{"id":"zvTdkL3H_Pm3NeSgG0ByD","method":"GET","url":"/ping","remoteAddress":"127.0.0.1","remotePort":61820},"v":1}
```

I think the `req.id` field could be removed to retain the `reqId` field to keep accorded with "request completed" log. 

#### Context

* *node version*: 10
* *fastify version*: ^1.7.0
* *os*: Mac

### PR DESCRIPTION
**Pull request by zhaoyao91**
resolve #1029

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by zhaoyao91** [comment]
test updated

**Comment by delvedor** [comment]
If we want to be zealous, it might be.

**Comment by delvedor** [comment]
I spoke with @mcollina and we prefer to release this in the next major release of the framework, since it could break the code of some user.

Thank you for contributing!

**Comment by mcollina** [comment]
I've updated this to the `next` branch, and I'm landing it.

**Pull request merged**
