### PR TITLE
add option to disable/ignore request-id header

### LINKED ISSUE #4192: Option to disable 'request-id' header
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add a option to disable `requestIdHeader` overwriting `genReqId`

### Motivation

As far as I understand, fastify will by default use the value of the `requestIdHeader`,if such a header is present in the request, over the `genReqId` value.

Now, one does not necessarily know that a server is a fastify server, and one can change (obfuscate) the header key, but essentially a malicious actor could pass the same request-id for all requests and therefore reduce the quality of the logs. If one is trying to investigate an incident multiple requests now share the same id.

This is of low impact I'd assume, still I think it would be nice to disable this behaviour in a proper way instead of relying on obfuscation.  

### Example

```
const fastify = require('fastify')({
  requestIdHeader: false // (disabled instead of default value)
})
```

### PR DESCRIPTION
**Pull request by philippviereck**
fixes #4192

This way it should not break anything, just allow for `requestIdHeader` to be ignored by setting it explicitly to `false`
```
  const fastify = Fastify({
    requestIdHeader: false,
  })
```

(I am not sure if I updated all those config validation and typescript files correctly.)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Could you update the documentation as well?

then it LGTM 👍🏽

**Comment by philippviereck** [comment]
@Eomm  Yeah, I can probably do that. (update the docs)

So, the current PR implementation does not break anything, and `undefined` still defaults to 'request-id'.
In my opinion this is unexpected behaviour. I think it should be `false` by default and you should opt-in rather than opt-out.

Also, setting requestIdHeader to `true` instead of a string will result, in the same behaviour as `false` because 
`false | string` is expected, should this be handled specifically or is it the users fault?

PS: here is why:
```
 const fastify = Fastify({
    requestIdHeader: true,
  })

const requestIdHeader = (options.requestIdHeader === false) ? false : (options.requestIdHeader || defaultInitOptions.requestIdHeader) 
// => requestIdHeader = true

...
const id = requestIdHeader === false ? genReqId(req) : (req.headers[requestIdHeader] || genReqId(req))
// req.headers[true] is undefined, so genReqId(req) will be used
```

**Review by mcollina — CHANGES_REQUESTED** [review]
Good work, could you add this new option to the docs?

**Comment by philippviereck** [comment]
sorry, didn't mean to close the branch. I updated the docs

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]

**Pull request merged**
