### PR TITLE
docs(ecosystem): add http-wizard

### PR DESCRIPTION
**Pull request by flodlc**
Add http-wizard in the community ecosystem.
More information here:
https://http-wizard.vercel.app

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — DISMISSED** [review]
-1,

not a fastify specific package.

**Comment by jsumners** [comment]
Thank you for the submission, but the document being modified is a list of Fastify specific modules. A generic HTTP client does not fit that description.

**Comment by flodlc** [comment]
Thanks for the reply!
Actually it's made first for Fastify but not only. 
If you had a look on my work and have feedback I would appreciate a lot 🙏

**Comment by jsumners** [comment]
I'm sorry, I do not understand how this tool is specific to Fastify. Can you provide some clarification?

**Comment by flodlc** [comment]
Sure, here is the doc example.

The `props` argument in the handle callback aligns directly with the` fastify.route` options.
It includes the `method`, `url`, and `schema`. These properties are also used by the `http-wizard.createRoute` method.
Using the same API as `fastify.route` ensures high compatibility with Fastify (that's intentional 🤝).

Http-wizard main goal is to have a tRPC-like DX for Fastify and bridging the gap between the back and the front.

```typescript
export const getUsers = (fastify: FastifyInstance) => {
  return createRoute("/users", {
    method: "GET",
    schema: {
      response: {
        200: z.array(User),
      },
    },
  }).handle((props) => {
    fastify.route({
      ...props,
      handler: (request) => {
        const users = await db.getUsers();
        return users;
      },
    });
  });
};
```

**Comment by metcoder95** [comment]
I've mixed feelings about it. It seems not really a plugin, but more a tool mount on top of `fastify` (which is pretty good), but I believe the `plugin` section is not the right place. Maybe create a new one?

**Comment by flodlc** [comment]
Thanks all for your replies, it's good to see there is an interest !
I understand your thought, a new section would be great 👍

**Comment by Uzlopak** [comment]
Erm.. i still dont see it. Not from the and not from the readme of http-wizard i see any connection to fastify. 

For me it is a generic http client.

Also the description of the plugin in this PR is kind of misleading.

**Comment by flodlc** [comment]
Got it! Thanks for you time though 👍

**Comment by kibertoad** [comment]
I don't mind it being added under separate section, if project documentation is revised to make the trpc-for-fastify aspect more explicit.

If it can be useful for someone in our ecosystem, why not?

**Comment by flodlc** [comment]
Http-wizard is really Fastify first, so I can easily turn the doc to make it more obvious in the next days

**Comment by flodlc** [comment]
Done ! Hope it helps. 
Would you like me to create a new section ?

**Review by Eomm — CHANGES_REQUESTED** [review]
> Would you like me to create a new section ?

Nope. A new section for 1 item would be odd.

I would merge this tool after the plugin tagging stuff: https://github.com/fastify/fastify/pull/4938

That PR is stale, would you mind to push it over the finish line?

**Comment by flodlc** [comment]
Sure, I wait for the https://github.com/fastify/fastify/pull/4938 to be merged. 
I can take some time I guess 🕐

**Comment by flodlc** [comment]
Fastify got mentionned on the official react-query doc thanks to http-wizard 👍  

image

**Comment by Uzlopak** [comment]
@Eomm 
Is it ok to merge?

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by kibertoad — APPROVED** [review]

**Review by Eomm — APPROVED** [review]

**Pull request merged**
