### PR TITLE
docs(ecosystem): add fastify-204

### PR DESCRIPTION
**Pull request by Shiva127**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
May I ask why it has the version of 4.0.1? This pluginis like 2 hours old.

**Comment by Shiva127** [comment]
> May I ask why it has the version of 4.0.1? This pluginis like 2 hours old.

I was not sure of this choice. I may have made a mistake (my first public _semver_ use). I have tagged it 4.x to follow the Fastify version number cause I have old projects using old version of Fastify and want to be able to make version 3.x of this plugin for version 3 of Fastify if needed (I have not checked the compatibility for the moment).

**Review by Fdawgs — CHANGES_REQUESTED** [review]
It's great that you've created a plugin for Fastify. As @Uzlopak  has pointed out, the semver misuse may confuse users, which isn't what we'd want to encourage.

**Comment by Eomm** [comment]
As a suggestion, I started to write a `compatibility` table on my plugins:

https://github.com/Eomm/fastify-overview#compatibility

**Comment by mcollina** [comment]
I don't think there is much to do know on the semver side, as v4 went out.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fdawgs** [comment]
> I don't think there is much to do know on the semver side, as v4 went out.

Aight, well then LGTM

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
