### PR TITLE
fix(#5180): close secondary bindings after primary is closed

### LINKED ISSUE #5180: Websocket connections to secondary server prevents server from shutting down
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

_No response_

### Node.js version

20.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.1

### Description

When a websocket connection is connected to a secondary server (e.g. when we are listening to both 127.0.0.1 (secondary) and ::1 (primary) and a client connects to 127.0.0.1), we don't run the preClose operations prior to closing the secondary server. This causes the server close hook to hang indefinitely since the websocket connection is still live.

I tried debugging the issue and it appears to be related to this line (https://github.com/fastify/fastify/blob/main/lib/server.js#L178) where Fastify attaches a onClose handler that tries to close the secondary server without calling any preClose hooks unlike the primary server (https://github.com/fastify/fastify/blob/main/fastify.js#L433). This means that @fastify/websocket is unable to shutdown the sockets appropriately leading the secondary server to stall the close process indefinitely.

I was wondering if it was on @fastify/websocket side to fix, but I don't see a way they can solve this without a fix on Fastify's side since it appears the Fastify close process is hanging before any plugin can do any clean up.

### Steps to Reproduce

I created a minimal reproduction repository here: https://github.com/kingston/fastify-websocket-repro

1) Run `node index.js`
2) Open `index.html`
3) Ctrl-C the node process

### Expected Behavior

Fastify shuts down cleanly without timing out

### PR DESCRIPTION
**Pull request by metcoder95**
Closes #5180

I tried to add a small test to reproduce it, it does covers the case but open to any suggestion to improve it.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by tchapacan** [comment]
Hello, sorry I’m quite new to the ecosystem (few weeks) but on my spare time I try follow some issues here and there and would be happy to help if needed.

Following initial work on this fix, after pulling this branch and playing arround, it seems the issue is still present using the reproduction example [https://github.com/kingston/fastify-websocket-repro](https://github.com/kingston/fastify-websocket-repro)

Even after the fix I still encounter the issue :

- Without connection: (still OK)

```
Closing main server
NET 35039: SERVER _emitCloseIfDrained
NET 35039: SERVER: emit close
Closing secondary server
NET 35039: SERVER _emitCloseIfDrained
NET 35039: SERVER: emit close
```


- With connection:  (KO)

```
Closing main server
NET 34756: destroy
NET 34756: close
NET 34756: close handle
NET 34756: has server
NET 34756: SERVER _emitCloseIfDrained
NET 34756: SERVER handle? true   connections? 1
NET 34756: SERVER _emitCloseIfDrained
NET 34756: SERVER handle? false   connections? 1
NET 34756: emit close
HTTP 34756: server socket close
```

If seems that in the callback function of the preClose hook, not all statement are evaluated using the `else if` causing the first true to be resolved and exit.
As far as I have understand (sorry I'm really new and don't manage all the codebase), to properly close the server we need absolutely all connection to be terminated before, so switching to multiple if statement might solved the issue ? 

- Before : https://github.com/fastify/fastify/blob/fix/5180/fastify.js#L434-L452

- After (one possible proposition) :

```js
if (fastify[kState].listening) {
    /* istanbul ignore next: Cannot test this without Node.js core support */
    if (forceCloseConnections === 'idle') {
      // Not needed in Node 19instance.server.closeIdleConnections()
      instance.server.closeIdleConnections()
    }
    if (serverHasCloseAllConnections && forceCloseConnections) {
      instance.server.closeAllConnections()
    }
    if (forceCloseConnections === true) {
      for (const conn of fastify[kKeepAliveConnections]) {
        // We must invoke the destroy method instead of merely unreffing
        // the sockets. If we only unref, then the callback passed to
        // `fastify.close` will never be invoked; nor will any of the
        // registered `onClose` hooks.
        conn.destroy()
        fastify[kKeepAliveConnections].delete(conn)
      }
    }
  }
```

Now it seems connection are properly close and server as well :

```
Closing main server
NET 35164: destroy
NET 35164: close
NET 35164: close handle
NET 35164: has server
NET 35164: SERVER _emitCloseIfDrained
NET 35164: SERVER handle? true   connections? 1
NET 35164: destroy
NET 35164: close
NET 35164: close handle
NET 35164: has server
NET 35164: SERVER _emitCloseIfDrained
NET 35164: SERVER handle? true   connections? 0
NET 35164: SERVER _emitCloseIfDrained
NET 35164: SERVER: emit close
Closing secondary server
NET 35164: SERVER _emitCloseIfDrained
NET 35164: SERVER: emit close
```

Does it seems correct to you ?

I can pull and push on top of this branch if needed or I can let you handle and update the code (test seems to pass on my local env)

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by metcoder95** [comment]
>With connection: (KO)

It seems the log for the secondary server is missing, it never triggered in order.

**Comment by tchapacan** [comment]
- Here logging for the failed scenario : (with some console.log at some keepoint in the logic)

```
$ NODE_DEBUG=net,http,timers node index.js
...
{"level":30,"time":1702373258116,"pid":1713,"hostname":"lalala","msg":"Received SIGINT signal. Shutting down..."}
start closing main server
start flushing idle connection
NET 1713: destroy
NET 1713: close
NET 1713: close handle
NET 1713: has server
NET 1713: SERVER _emitCloseIfDrained
NET 1713: SERVER handle? true   connections? 1
end flushing idle connection
NET 1713: SERVER _emitCloseIfDrained
NET 1713: SERVER handle? false   connections? 1
NET 1713: emit close
HTTP 1713: server socket close
{"level":50,"time":1702373263118,"pid":1713,"hostname":"lalala","err":{"type":"Error","message":"Shutdown timed out","stack":"Error: Shutdown timed out\n    at Timeout._onTimeout (/Users/lalalala/nodejourney/fastify-websocket-repro/index.js:25:23)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)"},"msg":"Shutdown timed out"}
```

- Here logging after proposition of modify the `else if` into a multiple `if` statement in the preClose callback function

```
$ NODE_DEBUG=net,http,timers node index.js
{"level":30,"time":1702373627585,"pid":1985,"hostname":"lalalala","msg":"Received SIGINT signal. Shutting down..."}
start closing main server
start flushing idle connection
NET 1985: destroy
NET 1985: close
NET 1985: close handle
NET 1985: has server
NET 1985: SERVER _emitCloseIfDrained
NET 1985: SERVER handle? true   connections? 1
end flushing idle connection
start flushing all connection
NET 1985: destroy
NET 1985: close
NET 1985: close handle
NET 1985: has server
NET 1985: SERVER _emitCloseIfDrained
NET 1985: SERVER handle? true   connections? 0
end flushing all connection
NET 1985: SERVER _emitCloseIfDrained
NET 1985: SERVER: emit close
start closing secoundary server
NET 1985: SERVER _emitCloseIfDrained
start flushing connection
end closing secoundary server
end closing main server
NET 1985: SERVER: emit close
```

I was suspecting that all connection wasn't properly flushed before closing the main server, causing the timeout in the first scenario. And the secondary server to never being properly close ? The `else if` statement was my suspect here : https://github.com/fastify/fastify/blob/71385a761d25b51c300863e0fc092af17ecfd5a0/fastify.js#L434-L452

But if you aren't able to reproduce it anymore with your fix then it might be my local setup maybe sorry!

> Note that i try to reproduce the scenario here [https://github.com/kingston/fastify-websocket-repro](https://github.com/kingston/fastify-websocket-repro) and i close the server immediately after having established a session with the browser, i don't let the socket die by entering in timeout

**Comment by Uzlopak** [comment]
@metcoder95 What about the remark of @tchapacan ?

CI is green. Ready to merge?

**Comment by metcoder95** [comment]
>But if you aren't able to reproduce it anymore with your fix then it might be my local setup maybe sorry!

No worries @tchapacan, nothing to worry about it is helpful what you provide so I can thoroughly test the fix. Sadly I couldn't reproduce the problem it after this fix, and it behave exactly the same as we were deleting the `else/if` from your xample:

```shell
node index.js
closing primary
secondary server closed
```

Using `DEBUG`:
```shell
NET 20920: setupListenHandle ::1 3000 6 0 undefined <- primary
NET 20920: setupListenHandle: create a handle
NET 20920: bind to ::1
NET 20920: setupListenHandle 127.0.0.1 3000 4 0 undefined <- secondary
NET 20920: setupListenHandle: create a handle
NET 20920: bind to 127.0.0.1
NET 20920: onconnection
NET 20920: _read
NET 20920: Socket._handle.readStart
HTTP 20920: SERVER new http connection
(node:20920) Warning: Setting the NODE_DEBUG environment variable to 'http' can expose sensitive data (such as passwords, tokens and authentication headers) in the resulting log.
(Use `node --trace-warnings ...` to show where the warning was created)
HTTP 20920: SERVER socketOnParserExecute 533
HTTP 20920: SERVER upgrade or connect GET
HTTP 20920: SERVER have listener for upgrade
^Chello world! undefined
NET 20920: SERVER _emitCloseIfDrained
NET 20920: SERVER handle? false   connections? 1
NET 20920: _final: not ended, call shutdown()
NET 20920: _read
NET 20920: afterShutdown destroyed=false
NET 20920: destroy
NET 20920: close
NET 20920: close handle
NET 20920: has server
NET 20920: SERVER _emitCloseIfDrained <- primary
NET 20920: SERVER: emit close
NET 20920: SERVER _emitCloseIfDrained <- secondary
NET 20920: SERVER: emit close
```

I believe the PR should be okay to go for now, we can always open a new issue if we face the same happening.

**Pull request merged**
