### PR TITLE
Update Ecosystem.md

### PR DESCRIPTION
**Pull request by applicazza**
Add link to @applicazza/fastify-nextjs community plugin

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by RafaelGSS — COMMENTED** [review]
What is the difference between https://github.com/fastify/fastify-nextjs and your plugin?

**Comment by applicazza** [comment]
As stated in README, Original fastify-nextjs doesn't pass response through Fastify's pipeline thus hooks that you may need won't work. For example it won’t attach/detach cookies that are managed by fastify. 

This package is using JavaScript's Proxy to intercept calls to NodeJs http.ServerResponse and pass it to Fastify.

Moreover, it allows to access to original fastify request and reply from within Next.Js by providing ‘IncomingMessage.fastify’ and ‘OutgoingMessage.fastify’ that can be utilized for example in ‘getServerSideProperties’

**Comment by RafaelGSS** [comment]
It sounds like an important bug in `fastify-nextjs`. @fastify/plugins someone has thoughts on it? I'm not a user of `fastify-nextjs`

**Comment by mcollina** [comment]
Why forking and not contributing back?

**Comment by applicazza** [comment]
I wouldn't call it a bug. The main problem with Fastify and Next.js integration is that latter is sending response back to client via Node http module (writes to ServerResponse stream) and has no public API that could return just string.

That's why I've ended up using Proxy to intercept calls to Node `IncomingMessage` and `OutgoingMessage` that does the job.

**Comment by applicazza** [comment]
> Why forking and not contributing back?

It was not forked. My plugin is written from zero in Typescript and is using a little bit different approach to serve content. For example it requires `fastify-static` to serve Next.js static resources and gives more freedom (at least I believe it does) to end-user.

If you believe that submitting PR to original plugin would be a better case I'd happily do it, but it will be backward incompatible and will require at least to bump it's major version.

In my opinion having another option is a good case, but again, decision is up to you. I'll get along with it :-)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — APPROVED** [review]
LGTM.

Let's see the adoption of the community, as you said, if needed we can merge both :smile:

**Pull request merged**
