### PR TITLE
Fix Markdown list alignment

### PR DESCRIPTION
**Pull request by pgcalixto**
When a list item has more than one line, the subsequent lines after the first one should begin in the same column that the first line content began.

Example:

image

This is a very subtle/minimal change, but the way it was before can lead to users copying code from the documentation and having to re-adjust it. This may cause friction for the user, since he/she may not be happy by just copying and pasting the examples.

There are 2 examples taken from https://www.fastify.io/docs/latest/TypeScript:

- In this example for an under-indented markdown list item, it leads to the first indentation level being 1 space instead of 2 spaces:

Screenshot from 2020-10-26 23-46-35

- In this example for an over-indented markdown list item, all the lines have 1 extra space in the beginning of the line:

image

---

Edit: I built and ran the [website project](https://github.com/fastify/website) using the aligned markdown and yes it did solve the problems regarding the missing/extra spaces in the examples.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by pgcalixto** [comment]
There may be other documentation files with have the same issue, but I only looked at Typescript.md because I was validating that the `import`s in TypeScript's documentation are correct (https://github.com/fastify/website/pull/209).

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by pgcalixto** [comment]
I didn't know where to comment this, but:

This repository had the topic "hacktoberfest", but today I this topic was removed and the hacktoberfest website removed my contributions for Fastify :/

**Comment by jsumners** [comment]
😕

It is no longer October. The topic should no longer be applied. The labels are still present and should still be applied to any PRs relating to the event.

**Comment by pgcalixto** [comment]
It's because the PRs require at least a maturity time of 14 days before being marked as valid after the first approval. Some of my PRs were still some days close to the period of 14 days to be counted towards the goal. By removing the topic hacktoberfest, they changed from Pending to Ineligible and I had 5/4 PRs and now I have 3/4 PRs :/

For instance, this PR was first approved 9 days ago and was just 5 days away until moving from Pending to Accepted, but now is Ineligible:

https://github.com/fastify/fastify/pull/2648

I still have some PRs from other repositories that are waiting the 14 days period before counting as valids.

I guess it probably will count again if the topic hacktoberfest is re-added to the repository or the label hacktoberfest-accepted is added to the PR.

Screenshot_20201102-225023_Chrome Beta

Screenshot_20201102-225054_Chrome Beta

Screenshot_20201102-225106_Chrome Beta

**Comment by pgcalixto** [comment]
PR count was 4/4 in October 27th:

Screenshot_20201027-073146_Chrome Beta


PR count decreased to 3/4 today:

Screenshot_20201102-224951_Chrome Beta

**Comment by mcollina** [comment]
I'm sorry this has caused some issues for you, but this is waiting a review from the @fastify/typescript team. We'll land as soon as that is ok.

**Comment by pgcalixto** [comment]
The issue is not about this PR not being merged yet. I had one that was merged and was waiting for the 14 day period to count as valid, but now that the repository does not have the hacktoberfest topic anymore, it is ineligible (this one: #2648).

If that's no trouble for you guys, could someone add the label "hacktoberfest-accepted" to one of these PRs, please? Maybe they'll come back to being to the Pending status (waiting 14 day to count as Valid).

- https://github.com/fastify/fastify/pull/2648
- https://github.com/fastify/website/pull/209

**Comment by pgcalixto** [comment]
Also maybe there are other PRs from other people that changed to Invalid now, because they were still waiting for the 14 day period.

I guess the hacktoberfest topic was safer to be removed on November 15, for the case which a person had its PR accepted on October 31 (I doesn't need to be merged. If a maintainer marks it as accepted ✅, it starts counting 14 day period to validation).

**Comment by mcollina** [comment]
Tagget both

**Pull request merged**
