### PR TITLE
Add fastify-doc plugin to ecosystem

### PR DESCRIPTION
**Pull request by dnlup**
Hi 👋🏻 ,
I would like to propose another plugin to add to the ecosystem (if you find it useful). It's a small wrapper for sampling process metrics like `cpu`, `eventLoopUtilization`, and so on. Its aim is to simplify the implementation of a custom reporter for health metrics.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
I think there are too much similar plugin already.
For example,
https://github.com/fastify/under-pressure
https://github.com/gkampitakis/fastify-custom-healthcheck

**Comment by dnlup** [comment]
> I think there are too much similar plugin already.
> For example,
> https://github.com/fastify/under-pressure
> https://github.com/gkampitakis/fastify-custom-healthcheck

Thank you for the quick feedback, I understand 👍🏻

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I would not block if for being a duplicate.

**Pull request merged**
