### PR TITLE
chore: add @gurgunday to the Core Team

### PR DESCRIPTION
**Pull request by gurgunday**
🎉

Side note: `gurgun.dayioglu@icloud.com` is no longer in use and will be deactivated shortly

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Uzlopak** [comment]
Wasnt there something to add regarding the github user id so that it shows properly on the website?

**Review by metcoder95 — APPROVED** [review]

**Comment by gurgunday** [comment]
> Wasnt there something to add regarding the github user id so that it shows properly on the website?

[There was something for the website](https://github.com/fastify/website/blob/208d49513a0b3be189de4982c23112ccc8dd60b4/static/data/team.yml#L128-L133), is there something else?

**Comment by Uzlopak** [comment]
I dont think so. Should be fine.

**Pull request merged**
