### PR TITLE
Feat: Add support for clearing routes

### PR DESCRIPTION
**Pull request by tysonrm**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
Thanks for the PR @tysonrm, could you please update the appropriate section in the documentation too with this new functionality?

**Comment by tysonrm** [comment]
> Thanks for the PR @tysonrm, could you please update the appropriate section in the documentation too with this new functionality?

No problem.

**Comment by tysonrm** [comment]
Updated the docs.

**Comment by tysonrm** [comment]
Feature is useful for dynamically updating controllers. Must get rid of the old bindings.

**Review by Eomm — CHANGES_REQUESTED** [review]
> Feature is useful for dynamically updating controllers. Must get rid of the old bindings.

I don't get it - could you explain a bit more with some real case example?

Right now:

- if the server is started, the clear func removes all the routes and you can't add new ones
- if the server is not started, the clear func removes all the routes added previously (in this case, why the developer should have add the routes then? 😕 )

**Comment by tysonrm** [comment]
> > Feature is useful for dynamically updating controllers. Must get rid of the old bindings.
> 
> I don't get it - could you explain a bit more with some real case example?
> 
> Right now:
> 
> * if the server is started, the clear func removes all the routes and you can't add new ones
> * if the server is not started, the clear func removes all the routes added previously (in this case, why the developer should have add the routes then? 😕 )

The use case is hot reloading, in which case the server is started and remains started.

**Comment by Eomm** [comment]
> The use case is hot reloading, in which case the server is started and remains started.

You can't add routes when the server is started.
If you comment the `app.get('/', () => { })` you will get 200 and then 404.

```
const fastify = require('./fastify')
const app = fastify()

app.get('/', async (request, reply) => {
  app.clearRoutes()
  app.get('/', () => { })
  return { hello: 'world' }
})

async function run () {
  {
    const res = await app.inject('/')
    console.log(res.statusCode)
  }
  {
    const res = await app.inject('/')
    console.log(res.statusCode)
  }
}

run()

```

Please provide a complete example with a test attached.

**Review by mcollina — CHANGES_REQUESTED** [review]
I actually did not thought this well when I checked it on the first time. I don't think we should support clearing routes.

**Comment by tysonrm** [comment]
> > The use case is hot reloading, in which case the server is started and remains started.
> 
> You can't add routes when the server is started. If you comment the `app.get('/', () => { })` you will get 200 and then 404.
> 
> ```
> const fastify = require('./fastify')
> const app = fastify()
> 
> app.get('/', async (request, reply) => {
>   app.clearRoutes()
>   app.get('/', () => { })
>   return { hello: 'world' }
> })
> 
> async function run () {
>   {
>     const res = await app.inject('/')
>     console.log(res.statusCode)
>   }
>   {
>     const res = await app.inject('/')
>     console.log(res.statusCode)
>   }
> }
> 
> run()
> ```
> 
> Please provide a complete example with a test attached.

There's no example using fastify yet because one of the first steps is to clear the old bindings, as shown in the express example at the url above. 

So I am hearing that Fastify can't support this capability? Downtime and disruption of client connections is unavoidable?

**Comment by Uzlopak** [comment]
What you maybe want to look at is

**Comment by tysonrm** [comment]
> What you maybe want to look at is https://github.com/fastify/restartable

Thanks, @Uzlopak . That should do the trick. Closing this PR.

**Pull request closed without merging**
