### PR TITLE
fix: remove http version check

### PR DESCRIPTION
**Pull request by beyazit**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Node.js issue [#43115](https://github.com/nodejs/node/issues/43115) has been resolved so I have removed this check.

### CODE REVIEW

**Comment by jsumners** [comment]
I suspect this is a major version change and should thus target the `next` branch.

**Comment by 0bl** [comment]
> I suspect this is a major version change and should thus target the `next` branch.

I changed pull request base to `next` branch.

**Review by climba03003 — CHANGES_REQUESTED** [review]
> I changed pull request base to next branch.

You need to rebase your changes on top of the `next` branch, so it would not include all the unnecessary commits.

**Comment by 0bl** [comment]
damn

**Comment by Uzlopak** [comment]
I merged main into next and updated this branch. The commits are still the same ,but  a squash merge should fix all the issues.

**Comment by Uzlopak** [comment]
@climba03003 
PTAL

**Comment by Uzlopak** [comment]
Maybe should also remove 

https://github.com/fastify/fastify/blob/main/docs/Reference/Routes.md#--http-version-check

@climba03003 

Well, lets say the underlying PR got merged into node code. Is it safe to remove this check already?

**Comment by climba03003** [comment]
I still prefer a clean history even on PR.

> Maybe should also remove

Yes

>  Is it safe to remove this check already?

Yes, I have double checked the changes is landed on 16, 18 and 20.

**Comment by Uzlopak** [comment]
@beyazit 

Are you still actively working on this PR?

**Comment by Uzlopak** [comment]
@climba03003 

I guess, @beyazit abandoned this PR.

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
