### PR TITLE
fix: add logger.setBindings for mocked logger

### PR DESCRIPTION
**Pull request by mattyod**
Add the setBindings() to the stub methods for Pino logger when no logger is specified during Fastify instantiation. Allowing that method to be called in components during testing.

Also added an optional type for this method.

Closes https://github.com/fastify/fastify/issues/5605

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mattyod** [comment]
related: https://github.com/fastify/fastify/pull/5607

**Review by climba03003 — CHANGES_REQUESTED** [review]
For me, I would like to keep the null logger as minimal as possible.
I would like to see the others opinion on it. @fastify/core 

Note that the types change implies we add `setBinding` as a must for fastify minimal logger interface for TypeScript users. (If it turns out can be undefined, I have no idea why it is not adding in the consumer code base only.)

**Comment by mattyod** [comment]
I'm only really trying to address the issue of not being able to access methods on the default logger Pino when using the null logger. Similar to a stub of child is provided but wouldn't necessarily exist on a custom logger.

**Comment by jsumners** [comment]
> For me, I would like to keep the null logger as minimal as possible.
> I would like to see the others opinion on it. @fastify/core

I agree. I have no idea what the issue actually is. We don't use that method:

```sh
fastify on  main took 2s
❯ rg '\.setBindings'

fastify on  main
❯
```

**Comment by mattyod** [comment]
@jsumners this is for people (like me) who are using Fastify and it's default logger Pino, not to assist core development. At the moment I can use Pino methods such as `info()`, `error()` * `child()` in a file under test and no error will be thrown. If I wish to take advantage of Pino's `setSiblings()` method, one is thrown.  This tries to address that.

**Comment by jsumners** [comment]
> @jsumners this is for people (like me) who are using Fastify and it's default logger Pino, not to assist core development. At the moment I can use Pino methods such as `info()`, `error()` * `child()` in a file under test and no error will be thrown. If I wish to take advantage of Pino's `setSiblings()` method, one is thrown. This tries to address that.

The only way to get the null logger is to disable logging, e.g.:

```js
const server = fastify({ logger: false /* the default */ })
```

If you require a Pino instance, set an appropriate configuration, e.g.:

```js
const server = fastify({ logger: { level: 'info' } })
```

**Comment by mattyod** [comment]
This is what we are doing. We use `fastify({ logger: true })` when instantiating the app to run and `fastify({})` when initialising for tests that use `fastify.inject()` so that their output is cleaner.

If people need a custom logger other than Pino I'm assuming they'd want a mock and types specific to that. If there's something I've changed in the TS definitions that prevents this are there further changes I can make?

**Comment by jsumners** [comment]
> This is what we are doing. We use `fastify({ logger: true })` when instantiating the app to run and `fastify({})` when initialising for tests that use `fastify.inject()` so that their output is cleaner.
> 
> If people need a custom logger other than Pino I'm assuming they'd want a mock and types specific to that. If there's something I've changed in the TS definitions that prevents this are there further changes I can make?

Then your tests are not using the same logger. Either use `fastify({ logger: { level: 'silent' } })`, pass in a destination stream that outputs the way and where you want, or provide your own Pino instance.

**Comment by mattyod** [comment]
ok I'll close this. Thanks for putting in the time to take a look.

**Comment by mattyod** [comment]
Though it does still mean we are having to extend the FastifyBaseLogger interface to use a method on Fastify's default logger.

```
declare module "fastify" {
  interface FastifyBaseLogger {
    setBindings(bindings: Bindings): void;
  }
}
```

**Comment by jsumners** [comment]
I really don't understand the issue. The null logger is not meant to be used outside of Fastify's internals. It is literally there just to no-operation all log methods used by Fastify because the user said they don't want any logging.

**Comment by mattyod** [comment]
Yes but if the user uses a documented method on Fastify's default logger such as `.setBindings()` they get a type error because no type has been defined for the method. Like thus:

Screenshot 2024-08-08 at 6 54 02 PM

**Comment by climba03003** [comment]
I would say we knows the issue but no solution on this currently.
See https://github.com/fastify/fastify/issues/5382, https://github.com/fastify/fastify/pull/5397, https://github.com/fastify/fastify/pull/5244

**Pull request closed without merging**
