### PR TITLE
test for issue #2148 where typedefs for query params object were wrong

### PR DESCRIPTION
**Pull request by rburgst**
this is a breaking test that illustrates #2148 . It should pass once the issue is fixed
#### Checklist

- [x] run `npm run test` and `npm run benchmark` (fails obviously)
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Could you send a PR to https://github.com/fastify/light-my-request?

**Comment by rburgst** [comment]
once https://github.com/fastify/light-my-request/pull/76 is merged this test should go through

**Comment by rburgst** [comment]
waiting for next release of https://github.com/fastify/light-my-request, now that https://github.com/fastify/light-my-request/pull/76 was merged

**Comment by rburgst** [comment]
who will merge this PR? I dont have the permissions.

**Comment by mcollina** [comment]
Thanks!

**Pull request merged**
