### PR TITLE
Add overloads for { parseAs: "string" } or { parseAs: "buffer" }

### PR DESCRIPTION
**Pull request by jineshshah36**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jineshshah36** [comment]
Here's a second, more thorough pass. It should make it as strict as possible.

**Comment by jineshshah36** [comment]
The CI seems to be complaining about type overloads since they use the same name.

**Comment by allevo** [comment]
I'm not a ts guy but I think it can be written like
```
type CallbackedBodyParser = a type
type PromisedBodyParser = another type
type BodyParser = PromisedBodyParser | CallbackedBodyParser
```

**Comment by jineshshah36** [comment]
you can but is there a reason overloads are not allowed in your linter?

**Comment by jineshshah36** [comment]
closing, reopened at #1162

**Pull request closed without merging**
