### PR TITLE
feat: delete var syntax

### PR DESCRIPTION
**Pull request by zekth**
As we no longer support Node 8, moving `var` to `let` and `const` has no performance impact and make the code fit the latest standards.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I'll do some benchmarks to verify this change, but I'm overall positive.

Can you also bump the standard dependency?

**Review by jsumners — APPROVED** [review]

**Comment by L2jLiga** [comment]
Regarding to benchmarking.. I'm also wondered if there some difference when use semicolon or no, I know JS has ASI but how it impacts... 🧐🙄

**Review by RafaelGSS — APPROVED** [review]
Since we are supporting `node >= 10`. LGTM! (Waiting benchmarks as well)

**Review by fox1t — APPROVED** [review]
LGTM!
<3

**Comment by mcollina** [comment]
Unfortunately we regress on Node.js v10:

master:

```
~/repositories/fastify (master)
$ autocannon -c 100 -p 10 localhost:3000
Running 10s test @ http://localhost:3000
100 connections with 10 pipelining factor

┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 7 ms  │ 7 ms │ 1.09 ms │ 2.58 ms │ 52 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Req/Sec   │ 78655   │ 78655   │ 86847   │ 87039   │ 85977.6 │ 2457.71 │ 78641   │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Bytes/Sec │ 12.9 MB │ 12.9 MB │ 14.2 MB │ 14.3 MB │ 14.1 MB │ 401 kB  │ 12.9 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

860k requests in 10.03s, 141 MB read
```

delete_var:

```
~/repositories/fastify (master)
$ autocannon -c 100 -p 10 localhost:3000
Running 10s test @ http://localhost:3000
100 connections with 10 pipelining factor

┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 8 ms  │ 8 ms │ 1.18 ms │ 2.98 ms │ 94 ms │
└─────────┴──────┴──────┴───────┴──────┴─────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬──────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg      │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼──────────┼─────────┼─────────┤
│ Req/Sec   │ 53727   │ 53727   │ 81599   │ 82559   │ 79058.91 │ 8040.6  │ 53725   │
├───────────┼─────────┼─────────┼─────────┼─────────┼──────────┼─────────┼─────────┤
│ Bytes/Sec │ 8.81 MB │ 8.81 MB │ 13.4 MB │ 13.5 MB │ 13 MB    │ 1.32 MB │ 8.81 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴──────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.

870k requests in 11.03s, 143 MB read
```

From some other experience, `for(let k = i; k < length; k++)` is problematic. Maybe we can try reverting only those and check.

There is no slowdown on v12.

**Review by mcollina — CHANGES_REQUESTED** [review]
blocking until we can assess where the slowdown is coming from.

**Comment by mcollina** [comment]
That's it. I'll push a fix with a few ignores. Essentially don't use `for(let k`... in node v10.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by feross** [comment]
Good to know that `var` is still faster on Node 10 in this one situation. Thanks for investigating this, @mcollina! Btw, we made the `no-var` rule into a warning in `standard` 16.0.1, so there's no immediate urgency to port code over. :)

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
