### PR TITLE
Removing Travis from Master

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
#1744 👋

This may also require some admin work to remove Travis from the repo/org

### CODE REVIEW

**Comment by lmammino** [comment]
Are we triggering the website build in the new pipeline?

This is currently done in travis with:

```yaml
after_script:
  - ./tools/website.sh
```

**Comment by mcollina** [comment]
We aren't :/. I think we configured it some ages ago and then turned it off.. maybe @StarpTech remembers.

**Comment by lmammino** [comment]
Then we should update the current pipeline definition as part of this PR as well

**Comment by Eomm** [comment]
@StarpTech friendly ping, do you remember something about this https://github.com/fastify/fastify/pull/1749#issuecomment-513894026 ?

**Comment by StarpTech** [comment]
During the migration to Azure @mcollina [configured](https://github.com/fastify/fastify/pull/1226#issuecomment-432312600) the `CIRCLECI_TOKEN` token and we [run](https://github.com/fastify/fastify/pull/1226/commits/0f22342da541bad5ac2bcc1bf908ffd83e8a4ce3) the website build script on master only. This was removed because travis already worked. @Eomm you only need to add [this](https://github.com/fastify/fastify/pull/1226/commits/0f22342da541bad5ac2bcc1bf908ffd83e8a4ce3) again.

**Comment by Eomm** [comment]
#1853 should close this PR right?

**Comment by StarpTech** [comment]
yes

**Pull request closed without merging**
