### PR TITLE
Fixed credits

### PR DESCRIPTION
**Pull request by mcollina**
As titled.

I've added all of you in the README, as it should be:

@allevo 
@jsumners 
@lmammino 
@evanshortiss 

I hope all your details are correct, please verify and let me know.

### CODE REVIEW

**Comment by mcollina** [comment]
also have a look at https://github.com/fastify/fastify/pull/287.

**Comment by StarpTech** [comment]
What's the requirements to be listed? We have 23 contributors and 10 Team members I can see four names.

**Comment by mcollina** [comment]
@StarpTech have a look at https://github.com/fastify/fastify/pull/287.

Everybody on that list has sent significant contributions to this library, with the exception of @lmammino, who did https://github.com/fastify/website, which is a different repo only because of technicalities.

I think that you qualify.

**Comment by delvedor** [comment]
We could also update the [`contributors`](https://github.com/fastify/fastify/blob/master/package.json#L32) field in the `package.json`.

**Comment by mcollina** [comment]
@delvedor definitely.

@fastify/fastify can you do it yourself even here or in another PR? I don't think I have the emails of everybody.

**Comment by StarpTech** [comment]
LGTM

**Comment by jsumners** [comment]
Emails are not necessary for the `package.json`. Since it would be silly to open so many PRs for such an addition before this one is merged, I will list mine here so you can add it if you desire (following @delvedor's lead):

```
{
  "name": "James Sumners",
  "url": "https://james.sumners.info"
}
```

**Comment by allevo** [comment]
mine:
```json
{
      "name": "Tommaso Allevi",
      "email": "tomallevi@gmail.com"
}
```

**Comment by StarpTech** [comment]
mine
```
{
      "name": "Dustin Deus",
      "email": "deusdustin@gmail.com"
}
```

**Comment by evanshortiss** [comment]
Thanks @mcollina. Here are my detail also:

```
{
      "name": "Evan Shortiss",
      "email": "evanshortiss@gmail.com"
}
```

**Pull request merged**
