### PR TITLE
fastify-apollo has been merged into apollo-server

### PR DESCRIPTION
**Pull request by dtex**
As of [this PR](https://github.com/apollographql/apollo-server/pull/1013), fastify-apollo is no longer a standalone module and the repo has been archived.

@nfishe Can you add a note on your repo also? It would be helpful for anyone who stumbles across it.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Awesome! I'll merge this once that is released, is that ok?

https://www.npmjs.com/package/apollo-server-fastify is still 10 months old.

**Comment by delvedor** [comment]
@dtex what I mean is, instead of removing the line, just update it with the new plugin :)

**Comment by dtex** [comment]
@delvedor Oh, gotchya. Yes, once it goes live that is the right thing to do.

**Comment by codejie** [comment]
maybe you can try to [fastify-apollo-step](https://www.npmjs.com/package/fastify-apollo-step)~

**Comment by delvedor** [comment]
What's the status on this?

**Comment by darkgl0w** [comment]
Since the release of apollo-server@2.4.2, fastify support has officially landed (related PR: https://github.com/apollographql/apollo-server/pull/2280)

I think this PR just needs an update to reference the official package (by pointing to this link : https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-fastify and referencing the package as `apollo-server-fastify`) ^^

**Comment by delvedor** [comment]
@darkgl0w would you like to open a new pr with the correct link?

**Comment by dtex** [comment]
Thank you @darkgl0w Closing this in deference to #1524

**Pull request closed without merging**
