### PR TITLE
Update TypeScript ServerOptions with new(ish) options

### PR DESCRIPTION
**Pull request by fileformat**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`: n/a
- [ ] tests and/or benchmarks are included: n/a
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Please update the test file too

**Comment by fileformat** [comment]
Not sure what you mean: this is just updating the type definitions to match existing functionality.  The functionality already existed and had tests:

- genReqId in genReqId.test.js
- requestIdHeader and requestIdLogLabel in logger.test.js
- serverFactory in custom-http-server.test.js

**Comment by Ethan-Arrowood** [comment]
I meant the typescript test file

**Comment by Eomm** [comment]
@fileformat we mean [this one](https://github.com/fastify/fastify/blob/master/test/types/index.ts)

Let us know if you are willing to add those test 💪

**Pull request closed without merging**
