### PR TITLE
types refactoring (WIP)

### PR DESCRIPTION
**Pull request by climba03003**
cc @sinclairzx81
Just let you know that I am start working on refactoring the old types into a single generic param.
It will be a large change on the ecosystem and may not be doing so fast.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I'm planning to start cutting v4 releases soonish. What's your ETA on finishing this work @climba03003 ?

**Comment by climba03003** [comment]
> I'm planning to start cutting v4 releases soonish. What's your ETA on finishing this work @climba03003 ?

I assume it will be done on next week.

**Comment by mcollina** [comment]
no worries, I think we can wait a bit.

**Comment by climba03003** [comment]
I think most of the original types is done. Now, I am facing the issue of it breaks the TypeProvider type resolve.
@sinclairzx81 Do you have time to look at which part I am doing wrong?

**Comment by RafaelGSS** [comment]
I'm planning to look at it soon (Today or tomorrow).

**Comment by sinclairzx81** [comment]
@climba03003 Hi, good work on the refactorings. It's a big job.

Just had a quick look at the branch. I think there could be an issue with the Schema (formally `SchemaCompiler`) not propagating through the types correctly. To test, I added the `genericType` and `schemaType` properties to the `FastifyRequest<...>` type to see what they were resolving to...as follows.

```typescript
export interface FastifyRequest<
  Optional extends FastifyInstanceRouteGenericInterface = DefaultFastifyInstanceRouteGenericInterface,
  Generic extends FastifyInstanceRouteGenericInterface = OverrideRouteGeneric<Optional, DefaultFastifyInstanceRouteGenericInterface>,
  RequestType extends FastifyRequestType = ResolveFastifyRequestType<Generic>
> {
  // **added**
  genericType: Generic,
  schemaType: GetRouteSchema<Generic>

  
  id: any;
  params: RequestType['params'];
  raw: GetRequest<Generic>;
  query: RequestType['query'];
  headers: GetProp<GetRequest<Generic>, 'headers'> & RequestType['headers']; // this enables the developer to extend the 
  // ... omitted
}
```
Then created a implementation on the on the type provider tests to see what they were.

```typescript
interface NumberProvider extends FastifyTypeProvider { output: number } // all schemas are numbers

expectAssignable(server.withTypeProvider<NumberProvider>().get(
  '/',
  {
    schema: { body: '' }
  },
  (req) => {
    const G = req.genericType // DefaultFastifyInstanceRouteGenericInterface: expected specialized interface type
    const S = req.schemaType  // FastifySchema: expected { body: '' }
  }
))

```
The Type Providers will need to see the schema provided by the user, however `GetRouteSchema<Generic>` is returning just a `FastifySchema`. Also the `Generic` argument is resolving to `DefaultFastifyInstanceRouteGenericInterface` (where I'd have imagined this to be generic, or mapped with the `NumberProvider` somewhere in its generic arguments). 

There was a brief mention to the FastifySchema vs SchemaCompiler mapping requirements here https://github.com/fastify/fastify/pull/3397#issuecomment-952590207, but I think the trick will be ensuring that the schema appropriately gets passed through the types such that the Type Provider can see and resolve from it.

Hope that helps!

**Comment by climba03003** [comment]
> 
> Hope that helps!

I think I will go for updating the route option and split the `schema` type outside of generic, then merge it back.
Your information does help on identify the what should be done next.

**Comment by climba03003** [comment]
Here comes another problem and why it is always the `default` value.
Since the generic is using `unknown`, it is actually matching all types.
Then, if we try to override a single prop inside the generic, it will always return `default`.

https://github.com/microsoft/TypeScript/issues/38456

**Comment by sinclairzx81** [comment]
@climba03003 I've put together a small prototype for the object generics and taken a bit of a look at the current overloads for `register()`. Posting [here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyYCgSgKIA8CGBbABwBsBTdMFK6m2+VVAYwHsA7AZwBdQBLDz3K0alQAXlAAzXFx4SAngAoAlAxb9QhAE7MAbjwAmpTQEExvfoOEA6AO49OACwAqcwqQAK2vYc0AeAOQubgBCzNhBHl4GRv4AfMqgGITM7Ow8AEbEcqCGWqSMuJyk+uaSuDrMmqDMEqB2jgDipKxGPIzsyqpsXBpRPsFmWrrRJrb2Dk0tmm3svgDeoADKRjpGAFyg-gCKAK5t-gA0oBGewz4b-gBS7GyLjA6k+LhOzE7s-qAAvvEqqHxFmikwlA7mIOwA5nwAPKETg8bqgBb4UipXDg0gbLjTVjgr4MaRyISSHZCOFsDRgyGsBR8LiWDGgABi0jh8gAkhYhKR5ksVutNrt9kcTn1+Vcbqw7g8ni83h9vkdmLD4RwNqCIdDld0lIjUKB9YkwAbjSbTWbzRbLQA9XncTjMUAkgDWrGYNlYvFqjhEJA1Hv0zBRrH83AKmhEuHSzB2nD1BowlsTSeT5twjGEqT4uPYfKqQzcmjhKKscf1tIEXKsSrJHFL5jplZzmlWmjr5fpVk4rkiZyMqE+DCG3iMwSs4chXCMCl9VKOSJR7DRDP8D2IxAdNkqxH08p1GChTo2ADlmEVQI5CueHhS-aAALIAVUWTlAT049yvIjS4NYhR24brFMgOA00MBqT96wraxjgcHh2F4eDcHPbtQEXCQRHBHZcE0Ep7VAZp2H-cgQJI0jDQgmc+FAcNhB4VZ4O9UBcEIfNpkKH1tALIt4NIbBkhzfRALI4SLQwdJskYpsW2QtwrFADkIPbLkKMpKiAyDEMhJE7TjQwMNSCORjlmbIxQHRKY2iYzRMORVhQ0EUB0i-Ug7QdZ1XXdEsGAwOhfL8-zwAoJYeHwHhiGw88HShdIACt8k4KxpG-akBGslyjhuf9hCUI4bAecMzOaVpGF6JUjG40ACg9JzQCC5iSB4Ypqmk3i4LhHFCoskrmFi+LSq4xr2BLHyAtGsaEAYXjkkLGSRGiuLGE4YxMx-XwnGw9FOCORZo00YRYjMBQ5jrABtABpUonVIORwPWtLOAAXXAAB+DYLt4opWH0eCrpu2odqykRnqWXbhHOh7QA2O7NvB-tQAAMl1Y1zsu67wIBvbSAejYMbBs6Hv7HUPuab7zHQqoACVQGB47kYuqjfvAinsdACnYc+DYWhbbzKHGvn+aCimUWYYh6Pw8ZTMYqEW2mQxqiqAARUgpB2Ygtvlx1WBdN0PVkUBfvw7A2vgqiWgl1sRv5q2AsmvjKjtFChZuUWey4uRfDO66jiVlW1aOaWjFl0gDvEOtPeyYmvp+tHagDzQg+p0AT1YI9VfCzJuTjoPzuuh6DrWMPrsNz7ScZ2ofdwVXuET5PU7XSMyF8Cuq5zuQ8-1AvjXcnWeYga3+8CjBmRkeR1SpIKB-723podtxWeFl3h9ZOQx81Gt4LW4uSfgpfZBX1TWAAdXGGF198QQ5FiEOQWwggXKMWYnFiE6AEYCdQKb7dmpkWT31ej5PlqDgvg6zuFvsiAEPFsAlx3r-dknJhBgM0HfSBZhm5q13vAhsiDwH300OwA4dZT4qnggaSOpML5mAvqga+NIEEMkwXIDk2DuRIJQQ-WIiogHsA2MQ7UYgDqnFCjmXwFQDAHQAD6gDEYJD+dsZpdjnow-+IDjRsIgQ-LeUcf4jyYfQ9ReD4LiHQZwRhzCoIeFwZAmhh0lLCA2GY+hvgDGQNiDqUQgjtDCO5DIyR0jmAGAYL3Se1sgqOJYRPEJAs5Ez3MACIEIhwkWJcQ-VRBo+EcFNOQxCrBsjiAvoQ40xlpJZOgdvJiuSqG5MKQaEUvYqjZIqXkppNjabpO4a9U0GSCF1mKUYTppo+maBqfqOpw5NCdLGSMfs08v6KJECYpJ9IUn4LMEsrkKzZh1n8CY7phxQJgBeAGDYQsSBphEPUBwoATGgG6ccbs2yTFDP2Qc44zBjnzzOcCS51zlaVzVryEyVQIiPL+VXKZPgPjkSOcwE5pAvkXPGL8323AIgglFMCh5sRZkzX+EYBJOjl7mPpGk-UABhf84Y7KbK0aTdZODkEaNWcYsFGC4F6JYZskZtzuGmnEE7EWqxThuwCHso4JpFnsuJRsqxD8jgUvjs0TgmzOG9NzGaflC8hWcXKu7fwzzxUStZaYqV+jZX4PlZSpVKruUQtMpq522qyqFj1XazQ+zJW6OlQy9hFrQAKqpcq817BVUHTafqDATgHg5isiIfKIgJCVHPCidquI2BZDrNWEhGwTTdLrFJfkgzcx1nmaccZUNuxlumXWDASC4S4DXNkJ4hB4LmWKlZGySqGIOiQi0GwkhKj4DkieM8F5uA2AjCtD0jFGBWrsv1cqg1mqS2vC0aBC7CxLsIh+MdNawCMXDJwf8LQSh2JEGoAQtJeikD0NGdgWRUIuU6u2jaOxbKcCGnWS5kxiqzCPB9WlsCvVmsZYYn4DjTUsN8PNeKy1kq+ADda4NRx-3QKvnWPdoAFC5BouxfQOoHwxu-UVaY7QEjllILgfQJZjSXLdWtStGLwP6npZnXqi04M8FWoh6lyHET3LcFW84AmezjK+OhzDQsJwAlAB5Zdmh1xUaanhQiLEv46GwjwQQH66hIsECUS50ZuBZu6HWccbUjDOIPoBwlf8D7H0cN0hDc6g2gdcf7XlDrBWkGUQfJz-8r4KAKGudIaZDwggPlw9evDuFKA2DIszpBpOWf-jZ3zfpnOKt425jh8RgvEFC4wcL-84v+MCQOMJ7KyiLUqNkCQJJFoqlQIYRg4UCr1dJCqMoujnHBrS5B5JfWWUotYyq5QEHgNQZVUEoAA) if it's helpful for reference. This approach should help propagate those generic types downwards and support arbitrary types for the other generic parameters.

**Comment by climba03003** [comment]
I may not be actively fixing this in the coming few days. I have bunch of work stacked and planning to finish before the coming long holiday (of my country) in next week.

I will start the work again during weekend and next week.

**Comment by mcollina** [comment]
@climba03003 any updates? I would like to ship the first rc asap.

**Comment by climba03003** [comment]
> @climba03003 any updates? I would like to ship the first rc asap.

I think you can just cut the line. I don't think it can be done in a short time based on my schedule.

**Pull request closed without merging**
