### PR TITLE
Use ajv options from ajv-compiler

### PR DESCRIPTION
**Pull request by mcollina**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by zekth — APPROVED** [review]
lgtm. But flakiness on CI tests?

**Comment by climba03003** [comment]
In my local test for `pnpm`, `ajv` for devDeps is not needed.
`schema.test-d.ts` also need to adjust.

**Comment by zekth** [comment]
@climba03003 this works but isn't odd that we have references of `ajv` in tests files and not have `ajv` as dev dependency? see:
```
test/input-validation.js
test/schema-special-usage.test.js
test/schema-validation.test.js
test/internals/handleRequest.test.js
test/internals/validation.test.js
```

**Comment by climba03003** [comment]
> 
> 
> @climba03003 this works but isn't odd that we have references of `ajv` in tests files and not have `ajv` as dev dependency? see:
> 
> ```
> test/input-validation.js
> test/schema-special-usage.test.js
> test/schema-validation.test.js
> test/internals/handleRequest.test.js
> test/internals/validation.test.js
> ```

As `ajv` is provided by `@fastify/ajv-compiler`, we should assume `ajv` must exist. It is not always necessary to specify a devDeps if we know it will be packed by other packages.

**Comment by zekth** [comment]
Maybe migrating all the `require('ajv')` to `require('@fastify/ajv-compiler')` is worth a PR

**Comment by jsumners** [comment]
> It is not always necessary to specify a devDeps if we know it will be packed by other packages.

No. If the dependency is directly used in your code then the dependency should be listed in the correct section of your `package.json`.

**Comment by mcollina** [comment]
> > It is not always necessary to specify a devDeps if we know it will be packed by other packages.
> 
> No. If the dependency is directly used in your code then the dependency should be listed in the correct section of your `package.json`. 

I second this. It's ok to have it as a devDependecy, we also need it for the build config script.

**Comment by climba03003** [comment]
> 
> 
> > It is not always necessary to specify a devDeps if we know it will be packed by other packages.
> 
> No. If the dependency is directly used in your code then the dependency should be listed in the correct section of your `package.json`.

Then, we should move all `ajv` to `@fastify/ajv-compiler`, then we do not need to have maintain `ajv` in both packages (even one of them is inside `devDeps`). And we will not have version mismatch when we upgrade `@fastify/ajv-compiler` in future.

**Review by climba03003 — APPROVED** [review]
LGTM. 
Moving all the `ajv` to `@fastify/ajv-compiler` is worth doing in another PR. So, I am not blocking this to be landed.

**Comment by mcollina** [comment]
FYI, I need the build fixed asap. If we can't settle on an approach I'm reverting the ajv-compiler change.

I'm supportive of all these other changes, but they will take more time than what I have.

**Pull request merged**
