### PR TITLE
Add generic parameter for Reply send method

### PR DESCRIPTION
**Pull request by kevinrambaud**
#### Description

It covers the issue #2030 for the v3.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Can you add some tests please? There is a types folder in the test folder you can use as a reference. Thank you!

**Comment by kevinrambaud** [comment]
I added a statement using the generic type. Was it what you had in mind?

**Comment by Ethan-Arrowood** [comment]
Does adding `expectType` to the inside of the `()` in the send call work? If not then a test is unneeded

**Comment by kevinrambaud** [comment]
No, it doesn't work, `expectType` return `void`. I removed the test.

**Comment by Ethan-Arrowood** [comment]
Great work! Thank you

**Pull request merged**
