### PR TITLE
Add LGTM badge

### PR DESCRIPTION
**Pull request by trivikr**
Fastify has 0 alerts from LGTM, and has A+ grade
How about showing it in README?

#### Checklist
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
What does LGTM do, and what it indicates? We have already the snyk badge for vulnerabilities.

**Comment by trivikr** [comment]
LGTM also displays alerts for rules such as [Superfluous trailing arguments
](https://lgtm.com/rules/4860081/), [invocation of non-function](https://lgtm.com/rules/10030087/) etc

Fastify doesn't have alerts, but here are the ones for [react repo](https://lgtm.com/projects/g/facebook/react/alerts/) for example

**Comment by mcollina** [comment]
IMHO if we integrate this we should remove the Snyk badge as they do the same thing. However, I prefer a `vulnerability: 0` statement.

@fastify/fastify what do you think?

**Comment by nwoltman** [comment]
Right now I prefer the Snyk badge because it's obvious what `vulnerabilities: 0` means, whereas it's not very clear what `lgtm: 0 alerts` means (especially if you don't know what the LGTM service is).

**Comment by jsumners** [comment]
I agree with @nwoltman.

**Comment by trivikr** [comment]
All people voted for Snyk badge, so closing this PR

**Pull request closed without merging**
