### PR TITLE
Add failing test

### PR DESCRIPTION
**Pull request by allevo**
Added a failing test.
Maybe it could be a bug in avvio as https://github.com/fastify/fastify/pull/168

cc @mcollina

### CODE REVIEW

**Comment by allevo** [comment]
@mcollina the first time in my code. This time writing tests for https://github.com/fastify/fastify/pull/167

> can you just reproduce it there?

I'm not expert in `avvio` but I'll try

**Comment by allevo** [comment]
@mcollina I'm not able to reproduce on `avvio` but I suppose I'm not so expert to translate `fastify` into `avvio`

This test passes
```js
test('foo', (t) => {
  t.plan(2)

  const myObject = {}
  const app = boot(myObject)
  app.override = function (i, fn, o) {
    return i
  }
  app.onClose((instance, done) => {
    done()
  })
  Promise.resolve()
    .then(() => {
      myObject.after((instance, done) => done())
      myObject.use(function (myObject2, b, next) {
        myObject2.after((instance, done) => done())
        t.ok(myObject2)
        next()
      })
    })
    .then(() => {
      myObject.ready(function (err) {
        t.error(err)
      })
    })
})
```

IMHO, the flow should be the same, but this passes

**Comment by mcollina** [comment]
I do not understand why you are defining the routes via promises. However, removing the `return` statement from the test made it work.

These are the changes:

```
diff --git a/test/listen.test.js b/test/listen.test.js
index d52b1c9..98fff33 100644
--- a/test/listen.test.js
+++ b/test/listen.test.js
@@ -25,12 +25,14 @@ test('listen accepts a port, address, and callback', t => {
 test('listen after Promise.resolve()', t => {
   t.plan(2)
   const f = Fastify()
+
   Promise.resolve()
     .then(() => {
       f.listen(0, (err) => {
         f.server.unref()
         t.error(err)
         t.pass()
+        f.close()
       })
     })
 })
@@ -40,7 +42,8 @@ test('register after listen using Promise.resolve()', t => {
   const f = Fastify()

   const handler = (req, res) => res.send({})
-  return Promise.resolve()
+
+  Promise.resolve()
     .then(() => {
       f.get('/', handler)
       f.register((f2, options, done) => {
@@ -53,6 +56,7 @@ test('register after listen using Promise.resolve()', t => {
         fastify.server.unref()
         t.error(err)
         t.pass()
+        f.close()
       })
     })
 })
```

**Comment by mcollina** [comment]
I don't know why the previous one was causing issues. I think it was due to some bad promise interaction. Anyway, this is good to land, LGTM

**Pull request merged**
