### PR TITLE
Use forked proxy-addr

### PR DESCRIPTION
**Pull request by mcollina**
Fixes https://github.com/fastify/fastify/issues/2761

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
@mcollina Should this be labelled semver-major?

**Comment by mcollina** [comment]
Not at all.

**Comment by kibertoad** [comment]
@mcollina Our policy is that we can drop deprecated properties at any time?

**Comment by kibertoad** [comment]
Ah, sorry, misread the code, you only changed tests.

**Review by jsumners — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by L2jLiga — APPROVED** [review]
lgtm

**Pull request merged**
