### PR TITLE
types: Added separated TypeProvider

### PR DESCRIPTION
**Pull request by Bram-dc**
Fix for discussion: https://github.com/fastify/fastify/discussions/5311

### CODE REVIEW

**Comment by Bram-dc** [comment]
Recreated the PR because of a typo.

**Comment by mcollina** [comment]
cc @sinclairzx81 @fastify/typescript wdyt?

**Comment by Shyam-Chen** [comment]
```diff
    async (request, reply) => {
-     return {
+     return reply.send({
        id: 1,
-     };
+     });
    },
```

**Comment by Bram-dc** [comment]
I created a new PR with a better version that has breaking changes.

**Pull request closed without merging**
