### PR TITLE
Fixed `preHandler` from being stuck when requested

### PR DESCRIPTION
**Pull request by foyzulkarim**
## What is changed 
- Fixed `preHandler` from being stuck when requested 

Reproduce steps 
 
fastify-doc-preHandler-problem

- Added `async` alternative in `preValidation` example because handler function is using `async`

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, good spot!

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by foyzulkarim** [comment]
Hi @mcollina,  may I ask when this PR will be merged (what is the process)? I am excited. :D

**Comment by mcollina** [comment]
Once somebody else from the TS team will review it :). I'm not really an expert on TS.

**Review by L2jLiga — APPROVED** [review]
LGTM

**Pull request merged**
