### PR TITLE
Remove middleware types/Fix hook definitions

### LINKED ISSUE #2040: v3 type def clarification for `addHook` method
I've been fixing the `hooks.d.ts` part of the new types and I've hit a very difficult snag. We have two hooks `onSend` and `preSerialization` that pass through the `payload` argument to the hook handler. For best type safety, we should allow the user to specify what this is via a generic parameter. But because all of the other hook handlers do not require this generic parameter I cannot just add it to `addHook`. 

What I can do is specify the generic parameter from the specific hook handler definition; and then allow the user to pass this through to the `addHook` function. This requires the user to specify the `onSend` and `preSerialization` hooks like so:

```typescript
type TestPayloadType = {
  foo: string,
  bar: number
}

// equivalent for `onSend`
const preSerializationHook: preSerializationHookHandler<TestPayloadType> = (request, reply, payload, done) => {
  // you can ignore this code its just apart of the unit tests
  expectType<FastifyRequest>(request)
  expectType<FastifyReply>(reply)
  expectType<TestPayloadType>(payload)
  expectType<(err: FastifyError) => void>(done(new Error()))
  expectType<(err: null, res: string) => void>(done(null, 'foobar'))
  expectError(done())
}

server.addHook('preSerialization', preSerializationHook)
```

There does not seem to be a way to pass that generic in line:

```typescript
// THIS CODE IS INVALID
type TestPayloadType = {
  foo: string,
  bar: number
}

// Where would `<TestPayloadType>` go? 
server.addHook('preSerialization', (request, reply, payload, done) => {
  // ...
})
```

Also, please note that **for all other hooks** the normal way of specifying them will work:
```typescript
server.addHook('onRequest', (request, reply, done) => {
  expectType<FastifyRequest>(request)
  expectType<FastifyReply>(reply)
  expectType<(err?: FastifyError) => void>(done)
})
```

---

I've attempted to write a definition that supports passing the payload generic to the `addHook` method but could not figure it out (i believe it might be impossible). So with all of this considered, **is the previously mention specification okay?** Of course, this will be detailed in the TypeScript documentation with code examples -- and I'll include a special note in the type definition comments (editors bubble these up to the user so they can get more info without leaving the editor). 

Lastly, i'm going to make a gist with all of my type def attempts as a reference -- [will add that here when its ready.](https://gist.github.com/Ethan-Arrowood/c0294ae9533a8b1908cf9c1a0e0208c0) <-- check it out. i'll be adding to it with other attempts as I go

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added -> #1966 
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

Draft PR in conjunction with #2014 . Can also merge this work into that PR if @delvedor wants. 
Closes #2040 

Currently missing async hook function definitions. Will add those next either in this branch or another one.

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Figured out how to add async functionality pretty easily.
Cannot enforce the user to not fall into this bad pattern: `async (req, res, done) => {}` but I can have TS error out if they try to return without the `async` keyword 😄

**Comment by Ethan-Arrowood** [comment]
And figured out how to get all the hooks to work inline. Even with custom generics for the onSend and preSerialization!

**Comment by Ethan-Arrowood** [comment]
Such a productive day. Types are rocking 🎸 now, and I gained some deeper understanding of overloads and generic stuff. Latest commit completes this PR. Docs will come separately in the open TS Doc pr 😄

**Comment by Ethan-Arrowood** [comment]
Wanted to note that this PR is waiting on https://github.com/fastify/fastify/pull/2014 to be ready. I believe #2014 is blocked by https://github.com/fastify/middie/pull/36 which I believe is blocked by https://github.com/mcollina/avvio/pull/92 (haha what a chain we got here). 

I'm going to be adding docs for these types separately in #1966 soon so I just wanted to make note of the fact that the code in `next` wont reflect the new docs until this is merged.

**Comment by delvedor** [comment]
@Ethan-Arrowood I think we can mark this pr ready to review, I'm planning to merge it just after #2014.

**Comment by Ethan-Arrowood** [comment]
I'm going to do a rebase for this on monday 👍

**Comment by Ethan-Arrowood** [comment]
Okay resolved conflicts, lets let the CI run and then get this merged :smile:

**Comment by Ethan-Arrowood** [comment]
Is GitHub Actions broken? Everything is passing for me locally and I don't understand the errors in the CI 😕

**Comment by mcollina** [comment]
Just flakyness.

**Comment by Ethan-Arrowood** [comment]
@mcollina should I rebase or cherry pick something?

**Comment by mcollina** [comment]
We just need https://github.com/fastify/fastify/pull/2135 to land first.

**Comment by mcollina** [comment]
@Ethan-Arrowood can you rebase on top of next?

**Comment by Ethan-Arrowood** [comment]
okay rebased; i hope the CI works - tests and linting succeeded locally for me

**Pull request merged**
