### PR TITLE
Add test for content-type overriding inside a plugin

### PR DESCRIPTION
**Pull request by Marsup**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

Latest minor broke our server, since it now generates new parser functions every time, the hasParser comparison fails. I only included a unit test so far to show the problem, I don't know how you want to address it so I'd happily take guidance on this one and make the changes, or feel free to merge the failing test and fix it if it's faster for you.

### CODE REVIEW

**Comment by Marsup** [comment]
Sure, np :) We'd like to patch our server for the proto poisoning asap, so if you have any advice on how to fix that regression, I'll gladly take it :)

**Comment by mcollina** [comment]
@marsup you’ll need to pass along the kDefaultJSONParser property in the buildContentParser function at the end of the file. That should do the trick.

**Comment by Marsup** [comment]
@mcollina Would my last commit do the trick?

**Comment by mcollina** [comment]
Yes!

**Comment by delvedor** [comment]
> Latest minor broke our server

Sorry about that!

@mcollina should we apply this change also in `master`?

**Comment by mcollina** [comment]
> @mcollina should we apply this change also in `master`?

Yes.

**Pull request merged**
