### PR TITLE
Reply error

### PR DESCRIPTION
**Pull request by delvedor**
With this PR we are introducing a standard error response of Fastify, that is structured as the following:
```js
{
  error: String        // the http error message
  message: String      // the user error message
  statusCode: Number   // the http status code
}
```
This error is always generated by `Reply`, so I've updated the `handleRequest` to conform the error messages, as it's already happening with middlewares and hooks.

In the reply error handling I've dropped [`fast-safe-stringify`](https://github.com/davidmarkclements/fast-safe-stringify) in favor of `JSON.stringify`, since we are sure that we will not have circular objects.

___

Proposal:
As you can see [here](https://github.com/fastify/fastify/blob/98be2edec3c70cf4814f87b66f96cc8f2fa9908c/test/reply-error.test.js#L47-L50) if we want to use a status code that is not `500` we must use `reply.code` before call `done`.
We can use a shortcut and pass the status code directly to done:
```js
fastify.addHook('preHandler', (req, reply, done) => {
  done(err, 400)
})
```

Feedbacks?
Related: #85 #69

### CODE REVIEW

**Comment by mcollina** [comment]
I think we should be compatible with https://www.npmjs.com/package/boom.

**Comment by mcollina** [comment]
What happens if in `preHandler` we do not call `done()`, and we just use `Reply`?

```js
fastify.addHook('preHandler', (req, reply, done) => {
  done(err, 400)
})
```

**Comment by jsumners** [comment]
Personally, I find `boom` kind of annoying. Getting the actual error out of it is more work than should be necessary.

**Comment by delvedor** [comment]
I can agree with you @jsumners, but Boom is widely used in the community and I think that support it out of the box could be a nice feature.
I thought about create a plugin to extend reply, something like `reply.boom`, but this will not support errors generated by *middlewares* and *hooks*.

**Comment by delvedor** [comment]
@mcollina I also added the shortcut for the `done` callback if the user wants to pass a `statusCode`. If everything is ok to you I can proceed to updated the docs.

**Comment by mcollina** [comment]
please do

**Comment by delvedor** [comment]
I've also added `extendServerError` api, in this way the user can extend the standard error object! :)
```js
fastify.extendServerError(() => {
  return {
    timestamp: new Date()
  }
})

/*
  The resulting object will be:
  {
    error: String
    message: String
    statusCode: Number
    timestamp: Date
  }
*/
```

**Pull request merged**
