### PR TITLE
test: port bodyLimit.test.js

### PR DESCRIPTION
**Pull request by rstagi**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Review by Uzlopak — CHANGES_REQUESTED** [review]
while we are at it. PLease rename bodyLimit.test.js to body-limit.test.js

Thank you

**Review by Uzlopak — CHANGES_REQUESTED** [review]
RSLGTM

**Review by Uzlopak — APPROVED** [review]
RSLGTM

**Review by jsumners — APPROVED** [review]

**Pull request merged**
