### PR TITLE
Rename Getting-Started.md to 01-Getting-Started.md

### PR DESCRIPTION
**Pull request by KostyaTretyak**
I see that in the [Fastify documentation](https://fastify.dev/docs/latest/Guides/Getting-Started/), the left menu bar is displayed in alphabetical order, depending on the first letter in the file name. To change this, simply add desired number: `01-<file-name>`. Which I did in this PR, just to show that there is such a possibility. The number in the file name will not be displayed, and will only affect the display order of the titles in the left menu.

### CODE REVIEW

**Review by jsumners — CHANGES_REQUESTED** [review]
I think there is probably a different way to solve the [website](https://github.com/fastify/website) problem that is not this. But if we are going to number the files in this repo, they should _all_ be numbered.

I am not particularly in favor of numbering the files, though. It's likely to result in difficult maintenance and churn with filename renames.

**Comment by KostyaTretyak** [comment]
> there is probably a different way to solve the [website](https://github.com/fastify/website) problem that is not this

On each page of the documentation, at the bottom of the page there is a link with the title "Edit this page", which leads to this repository.

**Comment by jsumners** [comment]
> > there is probably a different way to solve the [website](https://github.com/fastify/website?rgh-link-date=2024-12-16T12%3A20%3A57Z) problem that is not this
> 
> On each page of the documentation, at the bottom of the page there is a link with the title "Edit this page", which leads to this repository.

Yes, the content of that page is located here. But the website itself is built in the repo I linked. The issue you are trying to address is how the source documentation is presented. That is, in my opinion, a function of how the website is built.

attn: @fastify/website

**Comment by KostyaTretyak** [comment]
> But if we are going to number the files in this repo, they should all be numbered.

Sorry, but I don't have time for that. I'm working on my own framework, sometimes I look at what features Fastify has, so I decided to give a little hint to my colleagues to improve their documentation.

**Review by Eomm — CHANGES_REQUESTED** [review]
I don't think this is the proper solution.

We should leverage docusaurus:
https://docusaurus.io/docs/sidebar

and generate/edit the sidebar template accordingly:
https://github.com/fastify/website/blob/main/sidebars-template.json

**Comment by jsumners** [comment]
> > But if we are going to number the files in this repo, they should all be numbered.
> 
> 
> 
> Sorry, but I don't have time for that. I'm working on my own framework, sometimes I look at what features Fastify has, so I decided to give a little hint to my colleagues to improve their documentation.

Cool. Thanks for participating.

**Pull request closed without merging**
