### PR TITLE
Added case sensitive option to definition file.

### PR DESCRIPTION
**Pull request by hhwang39**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Can you change the pr base to `master` please? 

`next` is receiving a complete type refactor very soon (#1569) and then we can start accepting type fixes there

Thank you!

**Comment by hhwang39** [comment]
Change base to master

**Comment by Ethan-Arrowood** [comment]
Can you also add this to the test file? Should be another one line addition

**Comment by hhwang39** [comment]
Are you referring to [index.ts](https://github.com/fastify/fastify/blob/master/test/types/index.ts)?
```
  const otherServer = fastify({
    ignoreTrailingSlash: true,
    bodyLimit: 1000,
    maxParamLength: 200,
    querystringParser: (str: string) => ({ str: str, strArray: [str] }),
    modifyCoreObjects: true
  })
```

**Comment by Eomm** [comment]
@hhwang39 yes to all your questions 👍

**Pull request merged**
