### PR TITLE
fix(setNotFoundHandler): return this on function call

### PR DESCRIPTION
**Pull request by RafaelGSS**
fixes: #2531 

I don't sure about the documentation of it

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
LGTM

**Comment by sergiz** [comment]
Types file was not updated (it's wrong for setErrorHandler as well) and it still indicates that the function returns void.
https://github.com/fastify/fastify/blob/3709671b73c9109ef54fa1e85de0d7b7f7946226/types/instance.d.ts#L239-L241

**Comment by RafaelGSS** [comment]
@sergiz You are right. I'll fix it.

**Pull request merged**
