### PR TITLE
Added example for custom logger

### PR DESCRIPTION
**Pull request by L2jLiga**
Added example how to use Winston as a custom logger

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
This could be another example project to add here
https://github.com/fastify/example

and write in docs a reference to that repo

**Comment by mcollina** [comment]
I think it would actually be better in the examples repo.

**Comment by L2jLiga** [comment]
@Eomm, I created PR in examples: https://github.com/fastify/example/pull/9
I was guided by https://github.com/fastify/example/pull/6

> and write in docs a reference to that repo

You mean in example section of main README.md?

**Comment by Eomm** [comment]
>  I created PR in examples

I saw it, you did a good example; btw, we must have at least two approval before marge 💪

> You mean in example section of main README.md?

Yes 👍 I would add a bullet point in the [ecosystem section](https://github.com/fastify/fastify#ecosystem)


Closing this PR since the example will be added to the https://github.com/fastify/example repo

**Pull request closed without merging**
