### PR TITLE
update type definitions for http2

### PR DESCRIPTION
**Pull request by jinwoo**
- `req` may be http2.Http2ServerRequest
- `res` may be http2.Http2ServerResponse
- `ServerOptions` may have the `http2` field

### CODE REVIEW

**Comment by evanshortiss** [comment]
@mcollina @jinwoo looking at the [http2 docs](https://github.com/fastify/fastify/blob/master/docs/HTTP2.md) and [example](https://github.com/fastify/fastify/blob/master/examples/http2.js) from fastify, do we expose anything in particular that's different for http2? If not then I think the `http2.Http2ServerRequest` and `http2.Http2ServerResponse` can be removed from the typings?

**Comment by jinwoo** [comment]
@evanshortiss Re: exposing `http2.Http2ServerRequest` and `http2.Http2ServerResponse`, sometimes apps need to access the underlying node's native request/response objects, which fastify exposes via `req.req` and `reply.res` respectively. When using http1, they are `http.IncomingMessage` and `http.ServerResponse`. But with http2, they are `http2.Http2ServerRequest` and http2.Http2ServerResponse`. So if you want your code to be type-correct, it must be type-declared correctly like that. Otherwise it's really hard to make your code compile because typecasting doesn't work between them.

I'll address your other comment soon.

**Comment by jinwoo** [comment]
@evanshortiss I added the usages of new typings. What do you think?

**Comment by evanshortiss** [comment]
@jinwoo I got a chance to better review this. So I think there's a few more complications here to get this working nicely:

1. Middleware needs to accept both `http` and `http2` types
2. `FastifyInstance.server` needs to be updated to reflect that it can be a `http2` server
3. Types should not need to be determined using any logic, it should be implicit based on the setup

Might need to do something like below for example to ensure types are correctly applied. Alternatively, we could to place things like `http.IncomingMessage | http2.Http2ServerRequest` in places?

```typescript
// Just examples here, syntax might be a little off, but use template types
declare function fastify<HTTPServer, HTTPIncoming, HTTPOutgoing>(opts?: fastify.ServerOptions): fastify.FastifyInstance<HTTPServer, HTTPIncoming, HTTPOutgoing>;

interface FastifyInstance<HTTPIncoming, HTTPOutgoing, HTTPServer> {
    server: HTTPServer

    log: pino.Logger

    /**
     * Adds a route to the server
     */
    route(opts: RouteOptions): FastifyInstance<HTTPIncoming, HTTPOutgoing, HTTPServer>

    /**
     * Defines a GET route with the given mount path, options, and handler
     */
    get(url: string, opts: RouteShorthandOptions, handler: RequestHandler): FastifyInstance<HTTPIncoming, HTTPOutgoing, HTTPServer>

    /**
     * Defines a GET route with the given mount path and handler
     */
    get(url: string, handler: RequestHandler): FastifyInstance<HTTPIncoming, HTTPOutgoing, HTTPServer>

    /**
     * Set a function that will be called whenever an error happens
     */
    setErrorHandler(handler: (error: Error, reply: FastifyReply<HTTPIncoming>) => void): void
  }
```

Then usage would be like so:

```typescript
// http2 typings will be used for request/response etc.
const server: fastify.FastifyInstance<http2.Http2Server, http2.Http2ServerRequest, http2.Http2ServerResponse> = fastify({
  https: {
    cert: readFileSync('path/to/cert.pem'),
    key: readFileSync('path/to/key.pem')
  }
})

server.get('/things', (req, reply) => {
  reply.res // this is using correct http2 types since we passed them to the server factory!
})
```

Alternatively, we could attempt to automatically figure this out like so, but I think it might be better to simply force them being passed in to keep types a little cleaner:

```typescript
declare function fastify(opts?: fastify.ServerOptionsAsHttp): fastify.FastifyInstance<http.Server, http.Incoming, http.Outgoing>;
declare function fastify(opts?: fastify.ServerOptionsAsHttp2): fastify.FastifyInstance<http2.Server, http2.Incoming, http2.Outgoing>;

interface ServerOptionsAsHttp2 extends ServerOptions {
  http2: true
}

interface ServerOptionsAsHttp extends ServerOptions {
  http2: false
}
```

What do you think?

**Comment by jinwoo** [comment]
@evanshortiss That's a very good suggestion. Updated the code. Please take a look.

One thing complicated is the fact that the server can be either secure or not, and we have four distinct cases: http, https, http2, and secure http2.

**Comment by evanshortiss** [comment]
@jinwoo wow, that was quick!

> One thing complicated is the fact that the server can be either secure or not, and we have four distinct cases: http, https, http2, and secure http2.

Agreed. That is a little messy. I think it might be best to keep the types more straightforward. The developer can pass in the types like the first suggestion and it reduces the burden on this module to manage it, right? It also is more adaptable to future changes if any occur in typings names/files.

So maybe just this?

```typescript
const server: fastify.FastifyInstance<http2.Http2SecureServer, http2.Http2ServerRequest, http2.Http2ServerResponse> = fastify({
  http2: true,
  https: {
    cert: readFileSync('path/to/cert.pem'),
    key: readFileSync('path/to/key.pem')
  }
})
```

This would also mean the syntax for the following is more intuitive vs. the current example: 

```typescript
interface DecoratedInstance extends fastify.FastifyInstance<http2.Http2SecureServer, http2.Http2ServerRequest, http2.Http2ServerResponse> {
    utility: () => void
}
```

Apologies for the back and forth, but it's good to find the optimal solutions! What are your thoughts on that? Great job so far!

**Comment by jinwoo** [comment]
@evanshortiss Thanks for the thorough review. Even though it's a little bit messy, I really like the idea that all the types are automatically set up depending on the config parameters. I'd like to leave that ability as is if you don't mind. I don't think we're going to have more http variations in a near future. Any thoughts?

**Comment by evanshortiss** [comment]
@jinwoo agreed on the HTTP version front, my main concern is surrounding if someone had added custom functions to the `http` prototypes like so:

```js
const http = require('http')
const device = require('device')

http.InomingMessage.protoype.getDeviceType = function () {
  const ua = this.headers['user-agent']

  if (ua) {
    return device(ua).type // return 'mobile', 'tablet', 'desktop' etc.
  } else {
    return 'unknown'
  }
}
```

Then they might want to do this:


```ts
interface CustomIncomingRequest extends http.IncomingRequest {
  getDeviceType: () => string
}

const server: fastify.FastifyInstance<http.Server, CustomIncomingRequest, http.OutgoingResponse> = fastify({
  http2: true,
  https: {
    cert: readFileSync('path/to/cert.pem'),
    key: readFileSync('path/to/key.pem')
  }
})

server.get('/stuff', (req, reply) => {
  console.log(`incoming request from a ${req.req.getDeviceType()}`)
})
```

I'm ok with the current implementation, but might need to alter in the future. Could you make sure the `examples/typescript-server.ts` is also updated? Thing we're good to merge after that 👍

**Comment by jinwoo** [comment]
@evanshortiss That's a good point. Couldn't think about custom objects.

I added a fallback version of `fastify()`, which I think will address that concern. Also added a test case for that. It needs a typecasting like below but does work:
```typescript
  interface CustomIncomingMessage extends http.IncomingMessage {
    getDeviceType: () => string;
  }
  const customServer: fastify.FastifyInstance<http.Server, CustomIncomingMessage, http.ServerResponse> =
      fastify({} as fastify.ServerOptions);
```

Please let me know what you think.

**Comment by jinwoo** [comment]
Got a better idea. I moved the fallback version to the top and now we don't need the typecasting for `fastify()` calls with no arguments. When having some options there, you may still need typecasting for the `opts` argument.

**Comment by evanshortiss** [comment]
@jinwoo nice, I think that's a nice workaround. I have a PR open for TypeScript docs, so I will add some of this information in there.

Thank you for the awesome work on this. LGTM @mcollina  👍

**Comment by jinwoo** [comment]
Thanks, @evanshortiss , for great reviews. They were very helpful.

**Pull request merged**
