### PR TITLE
Fixed an error that occurred when sending an empty body as a buffer

### PR DESCRIPTION
**Pull request by strelov1**
Fixed an error that occurred when sending an empty body as a buffer object.

This was happening when using the @fastify/aws-lambda adapter in the Serverless Framework.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Would you mind adding a test?

**Comment by strelov1** [comment]
> Would you mind adding a test?

Done

**Review by metcoder95 — APPROVED** [review]
LGTM

**Comment by strelov1** [comment]
> LGTM

Sorry failed the test plan. Could you approve it again?

**Comment by mcollina** [comment]
Still failing on coverage

**Comment by Eomm** [comment]
I would try a typed array to fullfill the coverage

**Comment by strelov1** [comment]
> Still failing on coverage

It seems the tests do not cover the new conditions, possibly because the Buffer object cannot be passed in the same way as in the original tests. I'm investigating how it's called in @fastify/aws-lambda and will rewrite the tests.

**Comment by strelov1** [comment]
> LGTM

Could you please approve once again, I've added the correct test.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by strelov1** [comment]
> lgtm

Sorry, I hit the button to update branch

**Comment by strelov1** [comment]
I anybody happy to merge it?

**Review by Eomm — APPROVED** [review]

**Pull request merged**
