### PR TITLE
fix: allow uppercase requestdHeader

### PR DESCRIPTION
**Pull request by Uzlopak**
converts the requestIdHeader configuration value to lowercase at server initializiation

Case in discord, where dev passed the cloudflares `CF-RAY` headername to fastify, but didnt work. The dev needed to lowercase the headername to `cf-ray` to get it working. This PR ensures a better DX.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by yogeshwar607** [comment]
@Uzlopak @climba03003 After merging of this PR , started getting below error with tracestack

Screenshot 2023-07-17 at 18 19 23

We are using[ fastify-ajv-compiler](https://github.com/fastify/ajv-compiler) with below schema check so would suggest you to better analyse the impact. For us rolling back to previous version works. 

PS: Looking into why this happens originally and will update in case i find more details on this 

``` 
export const authorizationSchema = {
  $id: 'authorizationSchema',
  headers: {
    type: 'object',
    properties: {
      Authorization: {
        type: 'string',
        minLength: 20
      }
    },
    required: ['Authorization']
  }
}
```

**Comment by Uzlopak** [comment]
I dont see any connection between your reported error and my change. Actually it should not have any effect on existing code at all.

**Comment by Uzlopak** [comment]
Please open a new issue and if possible a reproduction which results in your issue.

**Pull request merged**
