### PR TITLE
fix ready returns

### LINKED ISSUE #2343: typescript definition for ready() is wrong
## 🐛 Bug Report

fastify.ready() resolves with no value, but d.ts declares to return Promise<FastifyInstance>

## To Reproduce

```ts
let server: FastifyInstance;
server = await fastify().ready();
```
this code compiles, but `server` is undefined

## Expected behavior

Either:
1. TS fails to compile (fix the signature to be Promise<void>)
1. or `ready()` resolves with the correct instance (fix the implementation)

## Your Environment

- *node version*: 12
- *fastify version*: >=2.15
- *os*: Mac

### PR DESCRIPTION
**Pull request by Eomm**
Fix #2343 

Missing encapsulation checks

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
is already fixed in v3?

**Comment by Eomm** [comment]
Yes, it is with avvio 7.1.2

I will add the same tests on master

**Comment by iansu** [comment]
It looks like this fix hasn't been released yet. Dependabot is trying to upgrade my app due to the just published security alert and this is breaking it. Any idea when a new version of 2.x will be published?

**Comment by mcollina** [comment]
This fix was released in v2.15.2 23 days ago: https://github.com/fastify/fastify/commit/e513a59b7fc80ec7d9e80e3c097e4d3576c055d4.

**Comment by iansu** [comment]
Weird. For some reason Dependabot was trying to upgrade to 2.15.1. I manually changed to 2.15.2 and everything works correctly.

**Pull request merged**
