### PR TITLE
chore: auto-merge dependabot updates

### PR DESCRIPTION
**Pull request by salmanm**
The config update tells dependabot to merge the PRs automatically without requiring an approval (once the CI is green)

Just need to make sure the below config is turned on in dependabot settings page.
Screenshot 2020-11-02 at 19 09 05

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
I've asked @salmanm to come up with this config. The reason is that I'm spending a few minutes every day to land all the changes... and I would love to _not_ do that. I normally land them if the CI is passing, so a human check is not going to do much more.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
Worth a shot I suppose.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by zekth — APPROVED** [review]
lgtm. As fastify code is pretty well covered i think it's ok to have it.

**Pull request merged**
