### PR TITLE
Fix link to Pino options

### PR DESCRIPTION
**Pull request by jsumners**
This PR updates the link to the Pino options documentation. It also changes it from a "here" link to a descriptive link.

Looking at the GH diff, it also seems some line endings got corrected.

### CODE REVIEW

**Comment by delvedor** [comment]
Hi, thanks for the correction!
Can you please restore the double space at the end of the lines? Is used by markdown for go to a new line:)

**Comment by jsumners** [comment]
@delvedor VS Code did that on save. Would you accept an extra new line?

**Comment by delvedor** [comment]
An extra new line is not a problem for me, just the newlines where VS removes the spaces, because if you see the [preview](https://github.com/jsumners/fastify/blob/d3c62668226fd4e78abb24a9e8c15d92fe467223/README.md) is a little bit harder to read :)

**Comment by jsumners** [comment]
@delvedor corrections added.

**Comment by delvedor** [comment]
Perfect, thank you! :)

**Pull request merged**
