### PR TITLE
Chore(Workflow): Update website.yml

### LINKED ISSUE #4732: broken Circle CI integration
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The Circle CI token need to be updated.
The API endpoint also need to be updated.

image

The website build trigger from `fastify/fastify` is broken since March.
That means whenever new document updated in here will not reflect in the website unless we manually run the build step on `fastify/website` or PR is merged in `fastify/website`.

Shell script for `v2` endpoint required to be tested by anyone who has Circle CI access.
[Circle CI Document](https://circleci.com/docs/api/v2/index.html#operation/triggerPipeline)
```sh
curl -X POST \
  -H 'Content-Type: application/json' \
  -H 'Circle-Token: ${{ secrets.circleci_token }}' \
  -d '{"branch":"master"}' \
  "https://circleci.com/api/v2/project/gh/fastify/website/pipeline"
```

cc @mcollina @luisorbaiceta @lmammino

### PR DESCRIPTION
**Pull request by luisorbaiceta**
Update to v2 of the CircleCI api
## Note:

This PR can only be merged once the Personal api token is created in the CircleCI website and added to the Github secrets of this repo.

Closes #4732

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
@mcollina could you add the secret?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I don't have time to do any devops work right now for this.

@lmammino could you take a look?

**Review by mcollina — APPROVED** [review]
lgtm, this has been set up

**Comment by luisorbaiceta** [comment]
I see a project API keys has been created but this workflow won't work unless the key set as a Github secret is a Personal CircleCI token. Has this been done? See linked issue for more reference

**Pull request merged**
