### PR TITLE
docs: add fastify-webpack-hot (fixes #3792)

### LINKED ISSUE #3792: Document fastify-webpack-hot
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

https://github.com/gajus/fastify-webpack-hot is a new Fastify plugin:

> A [Fastify](https://github.com/fastify/fastify) plugin for serving files emitted by [Webpack](https://github.com/webpack/webpack) with Hot Module Replacement (HMR).

It replaces `webpack-dev-server` and `webpack-hot-middleware`:

> `webpack-dev-server` and `webpack-hot-middleware` were built for [express](https://npmjs.com/package/express) framework and as such they require compatibility plugins to work with Fastify. Additionally, both libraries are being maintained with intent to support legacy webpack versions (all the way to webpack v1). As a result, they contain a lot of bloat that makes them slower and harder to maintain.
> 
> `fastify-webpack-hot` is built from the ground up leveraging the latest APIs of Fastify and webpack, and it encompasses functionality of both libraries. It is faster and easier to maintain.

### PR DESCRIPTION
**Pull request by gajus**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by gajus** [comment]
Didn't want to conflate unrelated changes in this PR, but we should probably remove [fastify-webpack-hmr](https://github.com/lependu/fastify-webpack-hmr) – the latter is just a [wrapper](https://github.com/lependu/fastify-webpack-hmr/blob/master/plugin.js) for `webpack-dev-server` and `webpack-hot-middleware`.

**Review by luisorbaiceta — CHANGES_REQUESTED** [review]
Please, follow alphabetical order 🙏

**Comment by gajus** [comment]
> Please, follow alphabetical order 🙏Thanks!

Done

**Review by mcollina — APPROVED** [review]
lgtm

**Review by luisorbaiceta — APPROVED** [review]
lgtm!

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
