### PR TITLE
fix: add logger.setBindings for mocked logger

### PR DESCRIPTION
**Pull request by mattyod**
Add the `setBindings()` to the stub methods for Pino logger when no logger is specified during Fastify instantiation. Allowing that method to be called in components during testing.

Also added an optional type for this method.

Closes https://github.com/fastify/fastify/issues/5605

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by metcoder95 — COMMENTED** [review]
Can you add some tests to it?

**Comment by mattyod** [comment]
that cover it?

**Review by climba03003 — CHANGES_REQUESTED** [review]
If setBinding can be `undefined`, I don't think we should expect it exist in the null logger.
The current null logger is the minimal logger interface which match my expectation.

**Comment by mattyod** [comment]
It can't be undefined, calling it does not cause an error and does not return anything. I can just assert that it exists and is a function, like the other assertions, but that does lower the functions called statistic for that file to 90%. So this test covered that.

I felt that calling the function negated the need for a `typeof function` assertion as well but I can add one if you feel the current mechanism is too subtle.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
please target the main branch, not v4.x. We'll do the backport.

**Comment by mattyod** [comment]
Closing as a rebase onto main is a bit messy.

**Pull request closed without merging**
