### PR TITLE
plugin for autogenerate crud route

### PR DESCRIPTION
**Pull request by paranoiasystem**
plugin for autogenerate crud route, it's use mongoose model

### CODE REVIEW

**Comment by RafaelGSS** [comment]
Maybe you can create unit tests, please?

**Comment by paranoiasystem** [comment]
@RafaelGSS I have add a simple unit test

**Comment by mcollina** [comment]
I would not use `fastify-plugin`, and let the internal logic of fastify to handle the prefix.

It really need more tests, one for each declared route.

**Comment by paranoiasystem** [comment]
I have written all test, all works good. @mcollina if you believe is better don't use ```fastify-plugin```, I can change part of my code from 

```js
module.exports = fp(plugin, {
  name: 'fastify-autocrud'
})
```

to

```js
module.exports = plugin
```

and change all routes to let the internal logic to handle the prefix.

**Comment by paranoiasystem** [comment]
I have change my code, I have add all test for all route and the coverage percentage. Check the repo https://github.com/paranoiasystem/fastify-autocrud and let me let me know if other stuff need to fix.

**Pull request merged**
