### PR TITLE
Always flatten the string before sending it out

### PR DESCRIPTION
**Pull request by mcollina**
Double the througput in some JSON-heavy cases.

@darahayes

### CODE REVIEW

**Comment by allevo** [comment]
Some days ago, I saw a library that implements it (yes for just `Number(str)`)

**Comment by mcollina** [comment]
My colleague @davidmarkclements  found it out: https://github.com/davidmarkclements/flatstr :).
For pino: http://npm.im/pino

**Comment by allevo** [comment]
ah! wow! small world!

So, why will we not use `flatstr` ?

:+1:  for the string check

**Comment by davidmarkclements** [comment]
yeah @mcollina , why will we not use `flatstr` ? 😢

hi @allevo :wave:

**Comment by mcollina** [comment]
@davidmarkclements done!

@allevo does that count as a LGTM?

**Comment by allevo** [comment]
@mcollina is there a performance penalty for a little string? I suppose not, but we should be sure

The flatstr benchmarks don't mention it @davidmarkclements

**Comment by delvedor** [comment]
I remember we used `flatstr` directly in `fast-json-stringify` and the benchmarks didn't change at the time. What has changed?

Same question of @allevo, what happens in case of small strings?

**Comment by allevo** [comment]
Or, what happens if we apply flatstr twice?

**Comment by delvedor** [comment]
As far as I know nothing, because the string has already been flattened, so is not useful.
If you have time look the `flatstr` documentation, is very well written and interesting!

**Comment by mcollina** [comment]
It fixed a regression were we had a 2x drop in throughput. I'll add a benchmark.

**Comment by darahayes** [comment]
For those interested this gist show details of the regression and also shows benchmark results

https://gist.github.com/darahayes/2549a062ed3e1467a46792ce41d1b0e1

**Comment by allevo** [comment]
@darahayes thank you! 

Actually without this PR the req/sec is about 6k against 14k without schema (very bad!). Applying this PR the req/sec is 18k against 16k without schema

Applying multiple time `flatstr` the result doesn't change despite https://github.com/davidmarkclements/flatstr/pull/2

**Pull request merged**
