### PR TITLE
Update Ecosystem.md

### PR DESCRIPTION
**Pull request by love-lena**
Add love-lena/fastify-mqtt to community ecosystem page

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by love-lena** [comment]
All tests pass, benchmarks look good, plugin is documented and tested. 
I am planning to add more tests + TS support to the plugin, but if its okay for that to not be included in v1.0.0, this is ready for merge.

**Review by Eomm — APPROVED** [review]
I just dropped some few suggestion 👍🏽

**Comment by love-lena** [comment]
@Eomm thanks for the suggestions + approving the PR!

**Pull request merged**
