### PR TITLE
docs: add reply lifecycle

### PR DESCRIPTION
**Pull request by Eomm**
Improve #2687 

This PR add a "reply lifecycle" that aims to explain what is happening when devs write `reply.send(<something>)`.

The stars 🌟 would like to emphasize the possible entry point to this flow

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
What do you mean by "any uncaught errors"? We do not install a `uncaughtException` handler globally. Errors that ends in our errorHandler are specifically tied to a single request.

**Comment by Eomm** [comment]
I mean when in handler function (even hooks) the user run bad code sync or async:

```
const shouldBeAString = null
reply.send(shouldBeAString.toUpperCase())
```

**Comment by mcollina** [comment]
That's not uncaught, there are catches in place to actually catch those errors.

**Comment by Eomm** [comment]
Unchaugt by the user, could we find a clearer wording that is not too long?

**Comment by Eomm** [comment]
@mcollina Would be `unexpected exception` clearer?

**Comment by mcollina** [comment]
We catch:

1. rejection in the promise chain returned by the route
2. errors thrown synchronously by routes and hooks

I would differentiate between 1 and 2. In 1, this is expected - users are encouraged to throw inside their routes and not wrap them in a try-catch, like they have to do in Express and others right now. In 2, this is a safety measure for newbies that should not be relied upon - I was -1 in adding it and I lost :(. It might be good to just document 1.

We do not catch:

1. uncaughtExceptions
2. unhandledRejections

There is not a good term for this.

**Comment by Eomm** [comment]
> There is not a good term for this.

I have tried to communicate these steps adding a more exhaustive paragraph introducing the `return` `throw` and `send` wording that represents the keyword used by users

**Comment by mcollina** [comment]
JSON rendering depends on the serialization flow, that bit in the diagram is not entirely correct.

**Comment by Eomm** [comment]
> JSON rendering depends on the serialization flow, that bit in the diagram is not entirely correct.

I think that would too many information to add, maybe I could replace `reply sent` with `2xx` or `4xx-5xx` as lifecycle of the request does?

Or add a note about that `reply sent` mean hide the serialization lifecycle (since there is the serializer and the json schema that takes action)

**Comment by mcollina** [comment]
> Or add a note about that reply sent mean hide the serialization lifecycle (since there is the serializer and the json schema that takes action)

Go for this.

**Comment by Eomm** [comment]
Done

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
