### PR TITLE
fix(v4): update .npmignore

### PR DESCRIPTION
**Pull request by Eomm**
Fixes: https://github.com/fastify/fastify/issues/5536

I think we should bump a new release, 4 MB are too much

### CODE REVIEW

**Review by gurgunday — APPROVED** [review]
I agree with adding .tap

**Review by jsumners — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@Eomm CI is failing, could you investigate and fix?

**Comment by climba03003** [comment]
See #5540

**Pull request merged**
