### PR TITLE
fix: adjust schema compiler type

### PR DESCRIPTION
**Pull request by RafaelGSS**
Ref #2880 

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by evanshortiss** [comment]
I tested this PR. Works nicely with:

```ts
import fastify, { ContextConfigDefault, FastifyRequest } from 'fastify'
import Joi from 'joi'

const app = fastify({ logger: true })

type HelloBody = { name: string }

app.route<{ Body: HelloBody }, ContextConfigDefault, Joi.Schema>({
  method: 'POST',
  url: '/hello',
  schema: {
    body: Joi.object({
      name: Joi.string().default('World')
    })
  },
  handler: (request: FastifyRequest<{ Body: HelloBody }>, reply) => {
    reply.send(`Hello, ${request.body.name}`)
  },
  validatorCompiler: ({ schema }) => (data: any) => schema.validate(data)
})

app.listen('3000')
```

**Comment by mcollina** [comment]
@evanshortiss do you lgtm it?

**Comment by evanshortiss** [comment]
@mcollina 👍 from me. Very nice work by @RafaelGSS

**Review by climba03003 — APPROVED** [review]

**Review by evanshortiss — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
