### PR TITLE
Allow payload modifications

### PR DESCRIPTION
**Pull request by StarpTech**
Supports the syntax in https://github.com/fastify/fastify/issues/400#issuecomment-340389561 with minimal core modification.

``` js
fastify.addHook('onSend', (request, reply, payload, next) => {
  next(null, { foo: 'bar' })
})
```

Or with async/await

```js
fastify.addHook('onSend', async (request, reply, payload) => {
  return { foo: 'bar' }
})
```

- The first value which is passed to the handler or returned is taken as new payload, this is equal to reply `sent` semantic.
- Tests are served later
- An error is logged when the payload was overridden multiple times

### CODE REVIEW

**Comment by StarpTech** [comment]
Please let us define how it should work and what we cam except. Make a proposal on the related issue. I solved this issue with the basic informations from the tickets.

**Comment by StarpTech** [comment]
@delvedor the payload can be manipulated as often as you want. You always work with the original data and don't propagate the change through the pipeline.

**Comment by mcollina** [comment]
@StarpTech sorry, I have not had time to flash my ideas into writing. It's definitely ok if you want to take this one!

My idea in how to implement this feature is to use https://github.com/mcollina/fastfall to wrap all the functions. When a `onSend` hook is registered, we can wrap it in another function with the signature `onSendWrap(payload, cb(null, payload))`. We can also store the last payload in the state, so calling the callback with undefined is supported.

**Comment by StarpTech** [comment]
@mcollina thanks for sharing. What's your expectation from the behavior of onSend? 
- should it be possible to modify the payload on each hook?
- should the change be propagated through the pipe ?

**Comment by delvedor** [comment]
> should it be possible to modify the payload on each hook?

Yes

> should the change be propagated through the pipe ?

I answer with an example.
I have two hooks, A and B.
If A changes the payload, B should get the updated payload.

In other words, the payload should be updated sequentially, we would not provide a "merge" functionality at the end of the hooks.

**Comment by allevo** [comment]
I'm not convinced. In this way each hook depends on the previous one.

**Comment by mcollina** [comment]
with fastfall you can reuse the callback, so that the first argument is always the payload.

**Comment by StarpTech** [comment]
@mcollina could you answer the questions from above https://github.com/fastify/fastify/pull/427#issuecomment-341649472

**Comment by StarpTech** [comment]
Close in favour of https://github.com/fastify/fastify/pull/447

**Pull request closed without merging**
