### PR TITLE
Add key signature for string keys (like '2xx') in response schema

### PR DESCRIPTION
**Pull request by kuritkaj**

### CODE REVIEW

**Comment by evanshortiss** [comment]
Hi @kuritkaj, so my understanding is this is because you'd rather have the ability to do:

```
{
  '200': {}
}
```

vs. 

```
{
  200: {}
}
```

I assume there's some use case where quotes are necessary?

**Comment by evanshortiss** [comment]
@kuritkaj I'm in favour of this. Personally, I was trying to think why not use numbers, but giving people a string option is totally sensible also since ultimately the "key" is the same. Could you add a new entry in the `test/types` file. We can merge after that 👍

**Comment by kuritkaj** [comment]
Hi!

I have seen in the validation documentation that it is possible to define the response schema also for multiple status codes. So instead of defining schema for code 200 and 201 you can do use the '2xx' key. And for this purpose I have updated the typing.

So this case should be covered in tests already.

**Comment by evanshortiss** [comment]
Thanks @kuritkaj - nice find!

**Pull request merged**
