### PR TITLE
docs(example): add a complete typescript example

### PR DESCRIPTION
**Pull request by hardfist**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by hardfist** [comment]
fixs https://github.com/fastify/fastify/issues/1349

**Comment by RafaelGSS** [comment]
Nice work! How we can add it in some location of our docs?

**Comment by hardfist** [comment]
@RafaelGSS  oh, I need to ignore the compiled file, it works now

**Comment by hardfist** [comment]
> Nice work! How we can add it in some location of our docs?
> 

maybe I should update the typescript docs?

**Comment by mcollina** [comment]
I think this could go in https://github.com/fastify/example? It seems a better venue than this repo.

**Comment by RafaelGSS** [comment]
I agree with @mcollina.
And I think that can be referenced [here](https://github.com/fastify/fastify/blob/master/docs/TypeScript.md#typescript)

**Comment by hardfist** [comment]
ok, I don't know https://github.com/fastify/example 's existence, but it seems that there's already a typescript example there, if you think it's ok to put this example there, I will move to there

**Comment by RafaelGSS** [comment]
let us know here when to change please :smile:

**Comment by Eomm** [comment]
Closing due the PR can be submitted to https://github.com/fastify/example repo 💪

**Pull request closed without merging**
