### PR TITLE
Add npmignore

### PR DESCRIPTION
**Pull request by allevo**
Exclude `example` and `tools/website.sh`

See https://github.com/fastify/fastify/issues/768

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by delvedor** [comment]
@mcollina I'm also a user of `node_modules` but our test suite has become pretty big, as well as the example folder.
Why not ship just the code and the documentation?

**Comment by jsumners** [comment]
I agree with @mcollina. It's why I'm switching to [pnpm](http://pnpm.js.org) (note: `tap` is currently bugged using this package manager due to https://github.com/isaacs/own-or-env/pull/2) over `npm` now that it is more mature. I routinely reference the `node_modules` directory for modules that I have directly depended upon.

Including the tests is helpful because they illustrate how the code is supposed to work. This is particularly helpful in Fastify's case because Fastify's code can be *very* difficult to follow.

**Comment by jsumners** [comment]
Anyone else have an opinion? @fastify/fastify

**Comment by corbinu** [comment]
I would say I really like my node_modules as small and uncluttered as possible. If I need to see the rest of the files I switch it to a git dependency until I have sorted out the issue. I would be for this.

**Comment by allevo** [comment]
This PR was been opened a month ago.

I'd like to keep node_modules as minimal as possible. 

Tomorrow I'll close this if no one adds a comment

**Pull request closed without merging**
