### PR TITLE
pull_request_target test

### PR DESCRIPTION
**Pull request by mcollina**
This is a test PR that _should_ fail, but now pull_request_target jobs runs with the full source code of the base branch, so it should pass.

### CODE REVIEW

**Comment by mcollina** [comment]
Ops, this did not work as expected :(

**Comment by jsumners** [comment]
Do we know anyone at GitHub that can clarify this for us?

**Comment by mcollina** [comment]
I'm unsure. However it's pretty clear how it works _right now_. Given all the security changes that happened I think we are good.

**Comment by Eomm** [comment]
> This is a test PR that should fail, but now pull_request_target jobs runs with the full source code of the base branch, so it should pass.

I think it may change the behaviour if it is executed from a fork or from a repository's branch

**Pull request closed without merging**
