### PR TITLE
Preserve validation errors from Ajv as an array

### PR DESCRIPTION
**Pull request by nasplachkov**
Does the same as before, but adds one more property **validation** that has the Ajv error as is. Without stringifying it.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please rebase and add a unit test?

**Comment by nasplachkov** [comment]
It shouldn't be breaking anything. Same output as before. Only ajv will have that property, though. Joi seems to return an error instance straight away. 
Is there an use case I'm missing?

**Comment by mcollina** [comment]
@nasplachkov no real deal, it will end up in v0.36.0. I'm just being conservative.

**Comment by vadim-shilov** [comment]
Hello!
Use fastify v1.10.x.
The "validation" property is absent in the response object.

Fragment of test log:
```
Difference:
- Expected
+ Received

  Object {
    "body": Object {
      "error": "Bad Request",
      "message": "body should have required property 'refreshToken'",
      "statusCode": 400,
-     "validation": Any<Array>,
    },
    "status": 400,
  }
```
Is it ok?

**Comment by mcollina** [comment]
You might want to open a new issue.

**Pull request merged**
