### PR TITLE
(v3.x) feat: reply trailers support

### PR DESCRIPTION
**Pull request by climba03003**
Backport #3794 and #3814 to `v3` branch.
I think the setting of backport CI has some problem. It received 403 when it try to push the commit.
https://github.com/fastify/fastify/runs/5710246658?check_suite_focus=true

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@climba03003 could you add also https://github.com/fastify/fastify/pull/3814 here?

**Comment by climba03003** [comment]
cherry-picked #3814

**Review by mcollina — APPROVED** [review]
lgtm

**Review by xtx1130 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
