### PR TITLE
Add test for checking multipart request using form-data module

### PR DESCRIPTION
**Pull request by allevo**
The injection using `form-data` module doesn't work properly.

A test is added.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Ouch! Would you be able to send a fix to https://github.com/fastify/light-my-request?

**Comment by mcollina** [comment]
I think this can land now. Can you also update the minimum version of light-my-request to 2.0.3 in package.json?

**Comment by allevo** [comment]
Done

**Comment by allevo** [comment]
CI restarted. Now it is green.

**Pull request merged**
