### PR TITLE
fix #3099

### LINKED ISSUE #3099: reply handling
## 💥 Regression Report

I think it should be related to the reply simplification.
https://github.com/fastify/fastify-nextjs/pull/260

Not sure if it is only test case related only or production related. I am not using this plugin but it is worth knowing the test is currently failed.

## Last working version

Worked up to version: 3.15.1

Stopped working in version: 3.16.1

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #3099

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
cc @climba03003

**Comment by mcollina** [comment]
cc @sergiz

**Review by climba03003 — APPROVED** [review]
I have run the test for `fastify-nextjs` against the fix. It resolve the issue. LGTM.

**Comment by sergiz** [comment]
LGTM. The `this.sent` check is kinda redundant now since the whole condition cannot be true without `this[kReplySentOverwritten]` being true (and when it is true, `this.sent` will be true as well).

**Pull request merged**
