### PR TITLE
allow nullable option for use cases like #1709

### PR DESCRIPTION
**Pull request by adrai**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Sorry if I'm paranoid: could change the default config of AJV a breaking change?
This could be archived using a `setSchemaCompiler` or a plugin (that add a `setSchemaCompiler`)

**Comment by adrai** [comment]
idk, all existing tests passed and I added an additional test

**Comment by Eomm** [comment]
Of course, this PR is OK!
The case is that someone used that kay without knowing it (copy-paste damn 😅).

And for what I learned some weeks ago, also the deprecated api in node.js, before to be cut off, the core maintainers think also on those users that continue to use it through some popular module that applies some monkey patching or still uses a deprecated api.

**Comment by mcollina** [comment]
@delvedor what do you think? Is this semver-major or not?
I think it's not, because if someone specified `nullable: true`, that's their _intention_ anyway.

**Comment by mcollina** [comment]
@delvedor yes exactly. Are you ok for this to land?

**Pull request merged**
